-- Queue one durable ZarKebab Investor notification whenever an absence is
-- deleted. The immutable audit row is the idempotency boundary because the
-- original absence row no longer exists after an undo.

create table if not exists public.salary_absence_undo_notification_deliveries (
  id                    bigint generated by default as identity primary key,
  audit_id              bigint not null unique
                        references public.accounting_record_audit(id) on delete restrict,
  absence_id            uuid not null unique,
  salary_profile_id     uuid not null
                        references public.employee_salary_profiles(id) on delete restrict,
  absence_date          date not null,
  employee_name         text not null default '',
  actor_id              uuid references public.profiles(id) on delete set null,
  actor_name            text not null default '',
  target_key            text not null default 'salary_events',
  status                text not null default 'not_attempted'
                        check (status in ('not_attempted', 'pending', 'sent', 'failed', 'skipped')),
  telegram_chat_id      text,
  telegram_message_id   text,
  error_message         text not null default '',
  attempted_at          timestamptz,
  sent_at               timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

alter table public.salary_absence_undo_notification_deliveries enable row level security;
revoke all on table public.salary_absence_undo_notification_deliveries from anon, authenticated;

create or replace function public.queue_salary_absence_undo_investor_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_salary_profile_id uuid;
  v_absence_date date;
  v_employee_name text := '';
begin
  if new.entity_type <> 'salary_absence' or new.action <> 'delete' then
    return new;
  end if;

  v_salary_profile_id := nullif(new.old_record ->> 'salary_profile_id', '')::uuid;
  v_absence_date := nullif(new.old_record ->> 'absence_date', '')::date;

  select coalesce(nullif(trim(employee_name), ''), '')
  into v_employee_name
  from public.employee_salary_profiles
  where id = v_salary_profile_id;

  insert into public.salary_absence_undo_notification_deliveries (
    audit_id, absence_id, salary_profile_id, absence_date, employee_name,
    actor_id, actor_name, target_key, status
  ) values (
    new.id, new.entity_id::uuid, v_salary_profile_id, v_absence_date,
    coalesce(v_employee_name, ''), new.changed_by,
    coalesce(new.changed_by_name, ''), 'salary_events', 'not_attempted'
  )
  on conflict (audit_id) do nothing;

  return new;
end;
$$;

drop trigger if exists queue_salary_absence_undo_investor_notification
  on public.accounting_record_audit;
create trigger queue_salary_absence_undo_investor_notification
after insert on public.accounting_record_audit
for each row execute function public.queue_salary_absence_undo_investor_notification();

revoke all on function public.queue_salary_absence_undo_investor_notification() from public;
notify pgrst, 'reload schema';
