import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { functionBody, readSource, root, sourceFiles } from './helpers/sourceGuard.js'

test('expenses page is feature-gated, persisted, and included in owner reports net income', () => {
  const app = readSource('src/App.jsx')
  const sidebar = readSource('src/components/UnifiedSidebar.jsx')
  const permissions = readSource('src/lib/permissions.js')
  const expenses = readSource('src/pages/Expenses.jsx')
  const expenseLib = readSource('src/lib/expenses.js')
  const accountingLib = readSource('src/lib/accounting.js')
  const salaries = readSource('src/pages/Salaries.jsx')
  const employees = readSource('src/pages/Employees.jsx')
  const employeeHistory = readSource('src/pages/EmployeeSalaryHistory.jsx')
  const salaryHistoryLib = readSource('src/lib/salaryHistory.js')
  const monthlyEstimate = readSource('src/pages/MonthlyEstimate.jsx')
  const reports = readSource('src/pages/Reports.jsx')
  const migration = readSource('supabase/048_expenses.sql')
  const salaryMigration = readSource('supabase/054_employee_salary_profiles.sql')
  const salaryUpgradeMigration = readSource('supabase/055_employee_salary_rate_amount_upgrade.sql')
  const salaryProfileEndDateMigration = readSource('supabase/056_employee_salary_profile_end_date.sql')
  const salaryBonusMigration = readSource('supabase/057_employee_salary_bonuses.sql')
  const salaryFineMigration = readSource('supabase/099_employee_salary_fines.sql')
  const salaryCompatMigration = readSource('supabase/058_employee_salary_daily_amount_compat.sql')
  const expenseIncomeMigration = readSource('supabase/059_expense_income_entries.sql')
  const salaryManualNamesMigration = readSource('supabase/060_employee_salary_manual_names.sql')
  const salaryDropPeriodMigration = readSource('supabase/062_drop_salary_payment_period_columns.sql')
  const salaryAbsenceMigration = readSource('supabase/063_employee_salary_absences.sql')
  const salarySafeDeleteMigration = readSource('supabase/076_employee_salary_safe_delete.sql')
  const ownerOnlyMigration = readSource('supabase/049_owner_only_expenses.sql')
  const roleAccessMigration = readSource('supabase/077_four_role_feature_access.sql')
  const health = readSource('scripts/check-db-health.js')

  assert.match(permissions, /key: 'expenses'/)
  assert.match(permissions, /function canEditFeature/)
  assert.match(roleAccessMigration, /feature_access_write_expenses/)
  assert.match(roleAccessMigration, /public\.current_staff_can_write\('expenses'\)/)
  assert.match(app, /const Expenses = lazy\(\(\) => import\('\.\/pages\/Expenses'\)\)/)
  assert.match(app, /const Salaries = lazy\(\(\) => import\('\.\/pages\/Salaries'\)\)/)
  assert.match(app, /const MonthlyEstimate = lazy\(\(\) => import\('\.\/pages\/MonthlyEstimate'\)\)/)
  assert.match(app, /const EmployeeSalaryHistory = lazy\(\(\) => import\('\.\/pages\/EmployeeSalaryHistory'\)\)/)
  assert.match(app, /path="\/admin\/accounting"/)
  assert.match(app, /path="\/admin\/accounting\/salaries"/)
  assert.match(app, /path="\/admin\/accounting\/estimate"/)
  assert.match(app, /path="\/admin\/expenses" element=\{<Navigate to="\/admin\/accounting" replace \/>/)
  assert.match(app, /path="\/admin\/expenses\/salaries" element=\{<Navigate to="\/admin\/accounting\/salaries" replace \/>/)
  assert.match(app, /path="\/admin\/expenses\/estimate" element=\{<Navigate to="\/admin\/accounting\/estimate" replace \/>/)
  assert.match(app, /<LazyProtectedRoute page="expenses"><Expenses \/><\/LazyProtectedRoute>/)
  assert.match(app, /<LazyProtectedRoute page="expenses"><Salaries \/><\/LazyProtectedRoute>/)
  assert.match(app, /<LazyProtectedRoute page="expenses"><MonthlyEstimate \/><\/LazyProtectedRoute>/)
  assert.match(app, /path="\/admin\/accounting\/employees\/:employeeId\/history"[\s\S]*<LazyProtectedRoute page="expenses"><EmployeeSalaryHistory \/><\/LazyProtectedRoute>/)
  assert.match(sidebar, /key: 'expenses'/)
  assert.match(sidebar, /path: '\/admin\/accounting'/)
  assert.match(expenses, /\.from\('expenses'\)/)
  assert.match(expenses, /entry_type/)
  assert.match(expenses, /getAccountingPageSummary/)
  assert.match(expenses, /INCOME_CATEGORIES/)
  assert.match(expenses, /EXPENSE_ENTRY_TYPES/)
  assert.match(expenseLib, /export const MANUAL_EXPENSE_CATEGORIES = EXPENSE_CATEGORIES\.filter\(category => \([\s\S]*category\.key === 'salary_one_time'[\s\S]*category\.key !== 'other'/)
  assert.match(expenses, /form\.entry_type === 'income' \? INCOME_CATEGORIES : MANUAL_EXPENSE_CATEGORIES/)
  assert.match(expenses, /investor_support/)
  assert.match(expenses, /formatMoneyInput\(form\.amount\)/)
  assert.match(expenses, /normalizeMoneyInput\(event\.target\.value\)/)
  assert.match(expenses, /const \[dateFrom, setDateFrom\] = useState\(\(\) => todayExpenseDate\(\)\.slice\(0, 8\) \+ '01'\)/)
  assert.match(expenses, /const \[activeRangeKey, setActiveRangeKey\] = useState\('month'\)/)
  assert.match(expenses, /function selectQuickRange\(key\)/)
  assert.match(expenses, /setActiveRangeKey\(key\)/)
  assert.match(expenses, /previousMonth: 'Previous month'/)
  assert.match(expenses, /yesterday: 'Yesterday'/)
  assert.match(expenses, /previousCurrentWeek: 'Previous & current week'/)
  assert.match(expenses, /const range = getAccountingQuickRange\(key\)/)
  assert.match(expenses, /setDateFrom\(range\.dateFrom\)/)
  assert.match(expenses, /setDateTo\(range\.dateTo\)/)
  assert.match(accountingLib, /export function getAccountingQuickRange/)
  assert.match(expenses, /function setCustomRange\(from, to\)/)
  assert.match(expenses, /setActiveRangeKey\('custom'\)/)
  assert.match(expenses, /<DateRangePicker/)
  assert.match(expenses, /const canAdd = canEditFeature\(profile \|\| \{ role \}, 'expenses'\)/)
  assert.match(expenses, /const canDelete = canEditFeature\(profile \|\| \{ role \}, 'expenses'\)/)
  assert.match(expenses, /getAccountingPageSummaryFromOrderSummary\([\s\S]*paidOrderSummary,[\s\S]*filteredExpenses,[\s\S]*dateFrom,[\s\S]*dateTo/)
  assert.match(accountingLib, /summarizeExpenseCashflowFromIncome\([\s\S]*normalizedOrderSummary\.paymentMethodIncome/)
  assert.match(expenses, /<MethodBalancesDisclosure rows=\{cashflow\.rows\} lang=\{lang\} labels=\{l\} \/>/)
  const methodBalancesDisclosure = functionBody(expenses, 'MethodBalancesDisclosure')
  assert.match(methodBalancesDisclosure, /const \[open, setOpen\] = useState\(false\)/)
  assert.match(methodBalancesDisclosure, /aria-expanded=\{open\}/)
  assert.match(methodBalancesDisclosure, /open \? labels\.showLess : labels\.more/)
  assert.match(methodBalancesDisclosure, /\{open && \(/)
  assert.doesNotMatch(expenses, /exportExpensesCsv|downloadCsv|<Download|l\.export/)
  assert.match(expenses, /label=\{l\.cafeIncome\} value=\{loading \? '—' : formatCurrency\(cafeIncome\)\}/)
  assert.match(accountingLib, /getCafeIncomeForRange\(orders, dateFrom, dateTo\)/)
  assert.match(expenses, /value=\{loading \? '—' : formatCurrency\(selectedRangeCafeIncome\.averageDaily\)\}/)
  assert.match(expenses, /loyaltyIncome: 'Loyalty income'/)
  assert.match(expenses, /sub=\{loading \? '' : `\$\{l\.loyaltyIncome\}: \$\{formatCurrency\(loyaltyIncome\)\}`\}/)
  assert.match(expenses, /label=\{l\.investorSupport\}[\s\S]*value=\{loading \? '—' : formatCurrency\(investorSupportTotal\)\}/)
  assert.doesNotMatch(expenses, /Investor income|Доход инвестора|Investor daromadi/)
  assert.match(expenses, /normalizeExpenseEntryType\(expense\.entry_type\) === 'income' &&[\s\S]*expense\.category === 'investor_support'/)
  assert.match(expenses, /await Promise\.all\(\[expensePromise, orderPromise, employeeMealPromise, salaryPromise\]\)/)
  assert.match(expenses, /if \(requestId !== loadRequestRef\.current\) return[\s\S]*setExpenses\([\s\S]*setPaidOrderSummary\([\s\S]*setSalaryProfiles\([\s\S]*setLoading\(false\)/)
  assert.match(expenses, /setPaidOrderSummary\(\{\}\)/)
  assert.doesNotMatch(expenses, /mergePaidOrderHistory|state\.orders|paidHistoryOrders/)
  assert.match(accountingLib, /otherIncomeTotal: Math\.max\(0, incomeSummary\.total - investorSupportTotal\)/)
  assert.match(expenses, /grid gap-3 sm:grid-cols-2 lg:grid-cols-4/)
  assert.doesNotMatch(expenses, /xl:grid-cols-7/)
  assert.match(expenses, /const ACCOUNTING_SECTION_GRID = 'grid items-start gap-5 lg:grid-cols-2'/)
  assert.match(expenses, /const HISTORY_SECTION_GRID = 'grid items-stretch gap-5 lg:grid-cols-2'/)
  assert.match(expenses, /aria-labelledby="accounting-period-heading"/)
  assert.match(expenses, /aria-labelledby="accounting-overview-heading"/)
  assert.match(expenses, /aria-labelledby="accounting-operations-heading"/)
  assert.match(expenses, /aria-labelledby="accounting-activity-heading"/)
  assert.match(expenses, /<DateRangePicker[\s\S]*rangeKey=\{activeRangeKey\}/)
  assert.ok((expenses.match(/aria-pressed=\{active\}/g) || []).length >= 2)
  assert.match(expenses, /disabled=\{loading\}/)
  assert.match(expenses, /role="alert"/)
  assert.match(expenses, /role="status" aria-live="polite"/)
  assert.match(expenses, /ExpenseCategoryChart/)
  assert.match(expenses, /l\.moneyFlow/)
  assert.match(expenses, /function openCategoryHistory\(category\)/)
  assert.match(expenses, /navigate\(`\/admin\/accounting\/history\?\$\{params\.toString\(\)\}`\)/)
  assert.match(functionBody(expenses, 'ExpenseCategoryChart'), /onClick=\{\(\) => onCategoryClick\?\.\(key\)\}/)
  const accountingHistory = readSource('src/pages/AccountingHistory.jsx')
  assert.match(accountingHistory, /useSearchParams\(\)/)
  assert.match(accountingHistory, /filterAccountingHistoryRows\(displayRows, \{ type, category, query, lang \}\)/)
  assert.match(accountingHistory, /value=\{category\}/)
  assert.match(expenses, /titleAmount=\{investorSupportTotal\}/)
  assert.match(functionBody(expenses, 'ExpenseHistorySection'), /titleAmount/)
  assert.match(functionBody(expenses, 'ExpenseHistorySection'), /titleAmount !== undefined/)
  assert.match(functionBody(expenses, 'ExpenseHistorySection'), /formatCurrency\(titleAmount\)/)
  const expenseHistory = functionBody(expenses, 'ExpenseHistorySection')
  assert.match(expenseHistory, /formatLongDate\(expense\.expense_date, lang, expense\.expense_date\)/)
  assert.match(expenseHistory, /formatTime\(expense\.created_at, '—'\)/)
  assert.doesNotMatch(expenseHistory, /formatTime\(expense\.expense_date/)
  assert.match(expenses, /EXPENSE_CATEGORIES/)
  assert.match(expenses, /EXPENSE_PAYMENT_METHODS/)
  assert.match(expenses, /navigate\('\/admin\/accounting\/salaries'\)/)
  assert.match(expenses, /navigate\('\/admin\/accounting\/estimate'\)/)
  assert.match(expenses, /getTotalSalaryDue/)
  assert.match(expenseLib, /export function getSalaryBalance\(salaryProfile, dateTo = todayExpenseDate\(\)\)/)
  assert.match(functionBody(expenseLib, 'getSalaryBalance'), /return accrued - getSalaryPaidAmount\(salaryProfile, dateTo\) - getSalaryFineAmount\(salaryProfile, dateTo\)/)
  assert.match(functionBody(expenseLib, 'getSalaryDue'), /Math\.max\(0, getSalaryBalance\(salaryProfile, dateTo\)\)/)
  assert.match(employees, /label=\{l\.balance\}[\s\S]*formatCurrency\(salaryBalance\)/)
  assert.match(salaries, /hint=\{selectedTransactionProfile \? `\$\{l\.balance\}: \$\{formatCurrency\(selectedTransactionBalance\)\}` : ''\}/)
  assert.ok((salaries.match(/due > 0 \? String\(due\) : ''/g) || []).length >= 2)
  assert.match(expenseLib, /export function getMonthlySalaryCommitment\(salaryProfile, asOfDate = todayExpenseDate\(\)\)/)
  assert.match(expenseLib, /export function getTotalMonthlySalaryCommitment\(salaryProfiles = \[\], asOfDate = todayExpenseDate\(\)\)/)
  assert.match(expenseLib, /if \(!salaryProfile \|\| salaryProfile\.is_active === false\) return 0/)
  assert.match(expenseLib, /return getSalaryAccruedAmount\(salaryProfile, monthStart, monthEnd\)/)
  assert.match(expenseLib, /export function allocateMonthlySalaryToDate/)
  assert.match(salaries, /getTotalMonthlySalaryCommitment/)
  assert.match(salaries, /const transactionSalaryProfiles = useMemo/)
  assert.match(salaries, /canRecordSalaryTransaction\([\s\S]*transactionForm\.entry_type/)
  assert.match(salaries, /transactionSalaryProfiles\.map\(item =>/)
  assert.match(salaries, /item\.is_active === false[\s\S]*formatCurrency\(getSalaryBalance/)
  assert.match(salaries, /monthlyPayroll:/)
  assert.match(salaries, /const monthlyPayrollTotal = useMemo\(\(\) => getTotalMonthlySalaryCommitment\(salaryProfiles, today\), \[salaryProfiles, today\]\)/)
  assert.match(salaries, /value=\{loading \? '—' : formatCurrency\(monthlyPayrollTotal\)\}/)
  assert.match(salaries, /l\.quickActions/)
  assert.match(salaries, /l\.salarySettings/)
  assert.ok(
    salaries.indexOf('aria-labelledby="salary-operations-heading"') < salaries.indexOf('aria-labelledby="salary-settings-heading"'),
    'daily salary operations should appear before salary setup'
  )
  assert.doesNotMatch(salaries, /className=\{SECTION_GRID\}/)
  assert.match(salaries, /salary-operations-heading[\s\S]*className="grid items-stretch gap-4"/)
  assert.match(salaries, /const \[salarySetupMode, setSalarySetupMode\] = useState\('add'\)/)
  assert.match(salaries, /\{ key: 'add',[\s\S]*\{ key: 'change',[\s\S]*\{ key: 'kpi'/)
  assert.match(salaries, /salary-settings-heading[\s\S]*grid w-full min-w-0 items-stretch gap-4[\s\S]*h-full w-full min-w-0[\s\S]*lg:col-span-2/)
  assert.ok((salaries.match(/h-11 self-end items-center/g) || []).length >= 3)
  assert.match(salaries, /aria-pressed=\{active\}/)
  assert.match(salaries, /function MetricCard/)
  assert.match(salaries, /function SectionHeading/)
  assert.doesNotMatch(salaries, /xl:grid-cols-\[minmax\(0,1fr\)_382px\]/)
  assert.doesNotMatch(monthlyEstimate, /loadAccountingPaidOrderSummary|overallExpenses|overallPaidOrderSummary|overviewRows|function Kpi/)
  assert.match(monthlyEstimate, /getMonthlyEstimateMethodRows\(paidOrders, incomeEntries, allActualExpenseRows\)/)
  assert.match(monthlyEstimate, /methodFlow/)
  assert.match(monthlyEstimate, /moneyCame/)
  assert.match(monthlyEstimate, /moneyWent/)
  assert.match(monthlyEstimate, /investorInvestedTotal/)
  assert.match(monthlyEstimate, /productsSpentTotal/)
  assert.match(monthlyEstimate, /cafePaidIn/)
  assert.match(monthlyEstimate, /productsSpent/)
  assert.match(monthlyEstimate, /rentRemaining/)
  assert.match(monthlyEstimate, /byCategory\.products_bazaar/)
  assert.match(monthlyEstimate, /recordedRentTotal/)
  assert.match(monthlyEstimate, /const expenseBreakdownCards = \[/)
  assert.match(monthlyEstimate, /const salaryPaymentTotal = summarizeExpenses\(salaryPaymentRows\)\.total/)
  assert.match(monthlyEstimate, /const salaryFineTotal = salaryProfiles\.reduce/)
  assert.match(monthlyEstimate, /absenceDaysTotal/)
  assert.match(monthlyEstimate, /recordedUtilitiesTotal/)
  assert.match(monthlyEstimate, /function BreakdownCard/)
  assert.match(monthlyEstimate, /getEstimatedMonthlyExpenseSummary\(salaryProfiles, cutoffEnd/)
  assert.match(monthlyEstimate, /getSelectedMonthSalaryOperatingSummary\(salaryProfiles, cutoffEnd\)/)
  assert.match(monthlyEstimate, /const salaryExpectedRemaining = salaryOperatingSummary\.remainingSalary/)
  assert.match(monthlyEstimate, /const rentExpectedRemaining = Math\.max\(0, monthlyEstimate\.monthlyRentUzs - recordedRentTotal\)/)
  assert.match(monthlyEstimate, /const utilitiesExpectedRemaining = Math\.max\(0, monthlyEstimate\.monthlyUtilitiesUzs - recordedUtilitiesTotal\)/)
  assert.match(monthlyEstimate, /const employeeMealEstimate = useMemo/)
  assert.match(monthlyEstimate, /employeeMealsRemaining/)
  assert.match(monthlyEstimate, /const expectedMonthOutflow = totalOutflow[\s\S]*- salaryPaymentTotal[\s\S]*\+ salaryOperatingSummary\.expectedSalaryCost[\s\S]*\+ rentExpectedRemaining[\s\S]*\+ utilitiesExpectedRemaining/)
  assert.match(monthlyEstimate, /expectedMonthSpent[\s\S]*formatCurrency\(expectedMonthOutflow\)/)
  assert.doesNotMatch(monthlyEstimate, /employeeArrearsRemaining|employeeRemainingTotal|employeeOpeningArrears|remainingCommitmentsUzs|plannedMonthOutflowUzs/)
  assert.doesNotMatch(monthlyEstimate, /formatUsd/)
  assert.doesNotMatch(monthlyEstimate, /monthlyRentUsd/)
  assert.match(monthlyEstimate, /buildSalaryPaymentExpenseRows/)
  assert.match(monthlyEstimate, /buildSalaryBonusExpenseRows/)
  assert.match(monthlyEstimate, /\.from\('employee_salary_fines'\)/)
  assert.match(expenses, /salaryDue/)
  assert.match(expenses, /salaryDueMonthEnd/)
  assert.match(expenses, /const payableSalaryProfiles = useMemo\([\s\S]*salaryProfiles\.filter\(salaryProfile => !salaryProfile\.deleted_at\)/)
  assert.match(expenses, /getTotalSalaryDue\(payableSalaryProfiles, salaryDueDate\)/)
  assert.match(expenses, /const salaryMonthEndDate = getSalaryMonthEndDate\(salaryDueDate\)/)
  assert.match(expenses, /getTotalSalaryDue\(payableSalaryProfiles, salaryMonthEndDate\)/)
  assert.match(expenses, /formatLongDate\(salaryMonthEndDate, lang, salaryMonthEndDate\)/)
  assert.match(expenseLib, /export function getSalaryMonthEndDate/)
  assert.match(expenses, /buildSalaryBonusExpenseRows/)
  assert.match(expenses, /buildSalaryPaymentExpenseRows/)
  assert.match(functionBody(expenseLib, 'buildSalaryPaymentExpenseRows'), /created_at: payment\.created_at/)
  assert.match(functionBody(expenseLib, 'buildSalaryBonusExpenseRows'), /created_at: bonus\.created_at/)
  assert.match(salaries, /value=\{transactionForm\.payment_method\}/)
  assert.match(salaries, /payment_method:\s*transactionForm\.payment_method \|\| salaryProfile\.payment_method \|\| 'cash'/)
  assert.match(expenses, /const salaryExpenses = useMemo\(\(\) => \(\s*buildSalaryPaymentExpenseRows\(salaryProfiles, dateFrom, dateTo\)/)
  assert.match(expenses, /const salaryBonusExpenses = useMemo\(\(\) => \(\s*buildSalaryBonusExpenseRows\(salaryProfiles, dateFrom, dateTo\)/)
  assert.match(expenses, /const allExpenses = useMemo\(\(\) => \(\s*\[\.\.\.salaryExpenses, \.\.\.salaryBonusExpenses, \.\.\.employeeMealExpenses, \.\.\.expenses\]\s*\.sort\(/)
  assert.match(expenses, /b\.expense_date\.localeCompare\(a\.expense_date\)[\s\S]*String\(b\.created_at \|\| ''\)\.localeCompare\(String\(a\.created_at \|\| ''\)\)/)
  assert.match(employees, /const activeEmployees = useMemo\(\(\) => employees\.filter\(item => item\.is_active !== false\), \[employees\]\)/)
  assert.match(employees, /const absentTodayEmployeeIds = useMemo\(\(\) => new Set\(/)
  assert.match(employees, /getSalaryAbsenceDates\(employee\)\.has\(today\)/)
  assert.match(employees, /Number\(absentTodayEmployeeIds\.has\(b\.id\)\) - Number\(absentTodayEmployeeIds\.has\(a\.id\)\)/)
  assert.match(employees, /label=\{l\.absentToday\} value=\{absentTodayCount\} danger=\{absentTodayCount > 0\}/)
  assert.match(employees, /absentToday\s*\?\s*'border-red-300 bg-red-50\/80 ring-2 ring-red-100'/)
  assert.match(employees, /absentToday \? l\.absentToday : l\.active/)
  assert.match(expenseLib, /export function getSalaryAbsenceForDate\(salaryProfile, date = todayExpenseDate\(\)\)/)
  assert.match(employees, /const todayAbsence = getSalaryAbsenceForDate\(employee, today\)/)
  assert.match(employees, /absentToday && \(/)
  assert.match(employees, /onClick=\{\(\) => undoEmployeeAbsence\(employee\)\}/)
  assert.match(employees, /confirmUndoAbsence \? l\.confirm : l\.undoAbsence/)
  const undoEmployeeAbsence = functionBody(employees, 'undoEmployeeAbsence')
  assert.match(undoEmployeeAbsence, /if \(!canManage \|\| !employee\?\.id\) return/)
  assert.match(undoEmployeeAbsence, /getSalaryAbsenceForDate\(employee, today\)/)
  assert.match(undoEmployeeAbsence, /confirmActionKey !== key/)
  assert.match(undoEmployeeAbsence, /\.from\('employee_salary_absences'\)[\s\S]*\.delete\(\)[\s\S]*\.eq\('id', absence\.id\)[\s\S]*\.eq\('salary_profile_id', employee\.id\)[\s\S]*\.eq\('absence_date', today\)[\s\S]*\.select\('id'\)/)
  assert.match(undoEmployeeAbsence, /deleteError \|\| !data\?\.length/)
  assert.match(undoEmployeeAbsence, /await loadEmployees\(\)/)
  assert.match(employees, /const \[inactiveExpanded, setInactiveExpanded\] = useState\(false\)/)
  assert.match(employees, /employees[\s\S]*\.filter\(item => item\.is_active === false\)[\s\S]*String\(b\.ended_at \|\| ''\)\.localeCompare\(String\(a\.ended_at \|\| ''\)\)/)
  assert.match(employees, /aria-expanded=\{inactiveExpanded\}/)
  assert.match(employees, /inactiveExpanded \? inactiveEmployees\.map/)
  assert.match(employees, /md:col-span-2 xl:col-span-3/)
  assert.match(employees, /const activeDailySalary = useMemo\(\(\) => \(\s*activeEmployees\.reduce\(\(sum, item\) => sum \+ getDailySalaryAmount\(item, today\), 0\)\s*\), \[activeEmployees, today\]\)/)
  assert.match(employees, /label=\{l\.activeDaily\} value=\{formatCurrency\(activeDailySalary\)\}/)
  assert.match(expenseLib, /export function isGeneratedSalaryExpense\(expense\)/)
  assert.match(expenseLib, /export function getExpenseHistoryDeleteTarget\(expense\)/)
  assert.match(functionBody(expenseLib, 'getExpenseHistoryDeleteTarget'), /employee_salary_bonuses/)
  assert.match(functionBody(expenseLib, 'getExpenseHistoryDeleteTarget'), /isGeneratedSalaryExpense\(expense\)/)
  assert.match(functionBody(expenses, 'deleteExpense'), /getExpenseHistoryDeleteTarget\(expense\)/)
  assert.match(functionBody(expenses, 'deleteExpense'), /\.from\(target\.table\)/)
  assert.match(functionBody(expenses, 'deleteExpense'), /!data\?\.length/)
  assert.match(functionBody(expenses, 'ExpenseHistorySection'), /getExpenseHistoryDeleteTarget\(expense\)/)
  assert.doesNotMatch(expenses, /buildSalaryExpenseRows\(salaryProfiles, dateFrom, dateTo\)/)
  assert.match(expenses, /\.from\('employee_salary_profiles'\)/)
  assert.match(expenses, /\.from\('employee_salary_absences'\)/)
  assert.match(expenses, /\.from\('employee_salary_fines'\)/)
  assert.match(salaries, /\.from\('employee_salary_profiles'\)/)
  assert.match(salaries, /\.from\('employee_salary_rates'\)/)
  assert.match(salaries, /\.from\('employee_salary_payments'\)/)
  assert.match(salaries, /\.from\('employee_salary_bonuses'\)/)
  assert.match(salaries, /\.from\('employee_salary_fines'\)/)
  assert.match(salaries, /\.from\('employee_salary_absences'\)/)
  assert.match(salaries, /\.from\('employee_salary_rates'\)\.delete\(\)/)
  assert.match(employeeHistory, /payment: 'employee_salary_payments'/)
  assert.match(employeeHistory, /fine: 'employee_salary_fines'/)
  assert.match(salaries, /const \[absenceForm, setAbsenceForm\]/)
  assert.match(salaries, /async function addAbsence/)
  assert.match(employeeHistory, /async function deleteHistoryEntry/)
  assert.match(salaries, /const absenceAlreadyRecorded = Boolean\(/)
  assert.match(salaries, /absenceAlreadyRecorded && \([\s\S]*role="alert"[\s\S]*\{l\.absenceDuplicate\}/)
  assert.match(salaries, /disabled=\{[^}]*absenceAlreadyRecorded[^}]*\}/)
  assert.match(functionBody(salaries, 'addAbsence'), /getSalaryAbsenceDates\(salaryProfile\)\.has\(absenceDate\)/)
  assert.match(functionBody(salaries, 'addAbsence'), /writeError\.code === '23505' \? l\.absenceDuplicate : writeError\.message/)
  assert.match(salaries, /\['payment', 'bonus', 'fine', 'absence'\]/)
  assert.match(employeeHistory, /l\.absences/)
  assert.match(salaries, /absence_date/)
  assert.match(salaries, /removeSalaryProfile/)
  assert.match(salaries, /buildSalaryRatePayload/)
  assert.match(salaries, /employee_name/)
  assert.match(salaries, /profile_id: null/)
  assert.match(salaries, /effectiveFrom: form\.joined_at/)
  assert.match(salaries, /effectiveDate: 'Effective date'/)
  assert.match(salaries, /label=\{l\.effectiveDate\}/)
  assert.match(salaries, /daily_amount:/)
  assert.match(salaries, /l\.bonus/)
  assert.match(salaries, /const \[changeForm, setChangeForm\]/)
  assert.match(salaries, /SALARY_RATE_UNITS/)
  assert.match(salaries, /rate_unit/)
  assert.match(salaries, /PAGE_SIZE = 12/)
  assert.match(salaries, /toggleSalaryProfileActive/)
  assert.match(salaries, /buildSalaryReactivationAbsenceRows/)
  assert.match(salaries, /\.upsert\(absenceRows, \{ onConflict: 'salary_profile_id,absence_date', ignoreDuplicates: true \}\)/)
  assert.match(salaries, /ended_at/)
  assert.match(salaries, /deleted_at/)
  assert.match(functionBody(salaries, 'removeSalaryProfile'), /\.update\(\{[\s\S]*deleted_at: new Date\(\)\.toISOString\(\),[\s\S]*\}\)/)
  assert.doesNotMatch(functionBody(salaries, 'removeSalaryProfile'), /\.delete\(\)/)
  assert.match(salaries, /pagedSalaryProfiles/)
  assert.match(salaries, /getSalaryDue/)
  assert.match(salaries, /l\.paymentBonus/)
  assert.match(salaries, /const \[transactionForm, setTransactionForm\]/)
  assert.match(salaries, /entry_type: 'payment'/)
  assert.match(salaries, /onClick=\{\(\) => addRate\(\)\}/)
  assert.match(salaries, /onClick=\{addTransaction\}/)
  assert.match(salaryHistoryLib, /export function buildSalaryHistoryEntries/)
  assert.match(salaryHistoryLib, /entryType: 'payment'/)
  assert.match(salaryHistoryLib, /entryType: 'bonus'/)
  assert.match(salaryHistoryLib, /entryType: 'fine'/)
  assert.match(salaryHistoryLib, /entryType: 'absence'/)
  assert.match(salaries, /fineReason/)
  assert.match(salaries, /entry_type === 'bonus'[\s\S]*?bonusComment[\s\S]*?transactionForm\.note/)
  assert.match(salaries, /autoCorrect="off"/)
  assert.match(salaries, /autoCapitalize="none"/)
  assert.match(salaries, /spellCheck=\{false\}/)
  assert.match(salaries, /data-gramm="false"/)
  assert.match(salaries, /reason,\s*created_by:/)
  assert.match(salaries, /transactionForm\.entry_type === 'fine' && !transactionForm\.note\.trim\(\)/)
  assert.doesNotMatch(employees, /deleteEmployee|employee-delete-|<Trash2/)
  assert.match(employees, /const canEditName = canManage && isOwner/)
  assert.match(employees, /const \[editingNameId, setEditingNameId\] = useState\(null\)/)
  assert.match(employees, /onClick=\{\(\) => startNameEdit\(employee\)\}/)
  assert.match(functionBody(employees, 'startNameEdit'), /if \(!canEditName \|\| !employee\?\.id\) return/)
  assert.match(functionBody(employees, 'saveEmployeeName'), /if \(!canEditName \|\| !employee\?\.id/)
  assert.match(functionBody(employees, 'saveEmployeeName'), /\.update\(\{ employee_name: nextName \}\)/)
  assert.match(functionBody(employees, 'saveEmployeeName'), /\.eq\('id', employee\.id\)/)
  assert.match(employeeHistory, /const isOwner = normalizeRole\(profile\?\.role \|\| state\.user\?\.role\) === 'owner'/)
  assert.match(employeeHistory, /const canDeleteHistory = canManage && isOwner/)
  assert.match(functionBody(employeeHistory, 'deleteHistoryEntry'), /HISTORY_TABLE_BY_TYPE\[entry\.entryType\]/)
  assert.match(employeeHistory, /payment: 'employee_salary_payments'/)
  assert.match(employeeHistory, /bonus: 'employee_salary_bonuses'/)
  assert.match(employeeHistory, /fine: 'employee_salary_fines'/)
  assert.match(employeeHistory, /absence: 'employee_salary_absences'/)
  assert.match(employeeHistory, /onDelete=\{\(\) => deleteHistoryEntry\(entry\)\}/)
  assert.match(employeeHistory, /Trash2/)
  assert.match(salaries, /if \(!payment\) return null/)
  assert.match(salaries, /if \(!event\) return null/)
  assert.ok((salaries.match(/\}\)\.filter\(Boolean\)/g) || []).length >= 2)
  assert.match(salaries, /const telegramDeliveryTypeStyles = \{[\s\S]*payment:[\s\S]*border-l-\[#ff5a00\][\s\S]*bonus:[\s\S]*border-l-blue-500[\s\S]*fine:[\s\S]*border-l-red-500[\s\S]*absence:[\s\S]*border-l-violet-500/)
  assert.match(salaries, /telegramDeliveryTypeStyles\[delivery\.eventType\]/)
  assert.match(salaries, /border-l-4[\s\S]*typeStyle\.card/)
  assert.match(salaries, /const deliveryValue = delivery\.eventType === 'rate'/)
  assert.match(salaries, /const deliveryDate = delivery\.eventDate/)
  assert.match(salaries, /delivery\.employeeName[\s\S]*—[\s\S]*deliveryValue/)
  assert.match(salaries, /deliveryValue && deliveryDate[\s\S]*·[\s\S]*deliveryDate/)
  const salaryNotificationCleanup = readSource('supabase/124_cleanup_deleted_salary_notification_deliveries.sql')
  assert.match(salaryNotificationCleanup, /cleanup_deleted_salary_event_telegram_delivery/)
  assert.match(salaryNotificationCleanup, /after delete on public\.employee_salary_bonuses/)
  assert.match(salaryNotificationCleanup, /after delete on public\.employee_salary_fines/)
  assert.match(salaryNotificationCleanup, /after delete on public\.employee_salary_absences/)
  assert.match(salaryNotificationCleanup, /after delete on public\.employee_salary_rates/)
  assert.match(salaryNotificationCleanup, /delete from public\.employee_salary_group_notification_deliveries delivery/)
  assert.match(employees, /buildSalaryReactivationAbsenceRows/)
  assert.match(employees, /normalizeSalaryEndDate/)
  assert.match(employees, /useRef/)
  assert.match(employees, /const \[deactivateDates, setDeactivateDates\] = useState\(\{\}\)/)
  assert.match(functionBody(employees, 'toggleEmployeeActive'), /ended_at: normalizeSalaryEndDate\(employee, deactivateDates\[employee\.id\], today\)/)
  assert.match(employees, /<DateInput[\s\S]*value=\{deactivateDate\}[\s\S]*max=\{today\}[\s\S]*lang=\{lang\}[\s\S]*setDeactivateDates/)
  assert.match(functionBody(employees, 'DateInput'), /const inputRef = useRef\(null\)/)
  assert.match(functionBody(employees, 'DateInput'), /onPointerDown=\{openPicker\}/)
  assert.match(functionBody(employees, 'DateInput'), /input\.showPicker\(\)/)
  assert.match(functionBody(employees, 'DateInput'), /formatLongDate\(value, lang, value\)/)
  assert.match(functionBody(employees, 'DateInput'), /type="date"/)
  assert.match(functionBody(employees, 'DateInput'), /text-transparent caret-transparent/)
  assert.match(employees, /\.filter\(employee => !employee\.deleted_at\)/)
  assert.match(employees, /\.from\('employee_salary_fines'\)/)
  assert.match(salaryHistoryLib, /createdAt: payment\.created_at/)
  assert.match(salaryHistoryLib, /createdAt: bonus\.created_at/)
  assert.match(salaryHistoryLib, /createdAt: fine\.created_at/)
  assert.match(salaryHistoryLib, /\.sort\(compareSalaryTransactionsNewestFirst\)/)
  assert.match(employeeHistory, /formatTime\(entry\.createdAt/)
  assert.match(salaryHistoryLib, /entryType: 'fine'/)
  assert.match(employees, /navigate\(`\/admin\/accounting\/employees\/\$\{employee\.id\}\/history`\)/)
  assert.doesNotMatch(employees, /historyOpenId|fixed inset-y-0 right-0/)
  assert.match(employeeHistory, /const \{ employeeId \} = useParams\(\)/)
  assert.ok((employeeHistory.match(/\.eq\('salary_profile_id', employeeId\)/g) || []).length >= 5)
  assert.match(employeeHistory, /buildSalaryHistoryCalendar/)
  assert.match(employeeHistory, /useSearchParams\(\)/)
  assert.match(employees, /\.upsert\(absenceRows, \{ onConflict: 'salary_profile_id,absence_date', ignoreDuplicates: true \}\)/)
  assert.doesNotMatch(salaries, /const \[bonusForm, setBonusForm\]/)
  assert.doesNotMatch(salaries, /const \[rateForms, setRateForms\]/)
  assert.doesNotMatch(salaries, /onClick=\{addBonus\}/)
  assert.doesNotMatch(salaries, /onClick=\{\(\) => addRate\(item\)\}/)
  assert.doesNotMatch(salaries, /onClick=\{\(\) => addPayment\(item\)\}/)
  assert.doesNotMatch(salaries, /System account|Аккаунт в системе|Tizim akkaunti/)
  assert.doesNotMatch(salaries, /Payment schedule|График выплат|To‘lov jadvali/)
  assert.match(reports, /const canViewExpenses = canViewPage\(profile \|\| \{ role: state\.user\?\.role \}, 'expenses'\)/)
  assert.match(reports, /buildSalaryPaymentExpenseRows\(salaryProfiles, dateFrom, dateTo\)/)
  assert.match(reports, /buildSalaryBonusExpenseRows/)
  assert.match(reports, /\.from\('employee_salary_absences'\)/)
  assert.match(reports, /entry_type/)
  assert.match(reports, /const allExpenses = useMemo\([\s\S]*\[\.\.\.salaryExpenses, \.\.\.salaryBonusExpenses, \.\.\.employeeMealExpenses, \.\.\.expenses\]/)
  assert.match(reports, /summarizeExpenses\(allExpenses\)/)
  assert.match(reports, /const cashflowLeft = kpiRevenue - expenseSummary\.total/)
  assert.match(reports, /const netIncome = cashflowLeft/)
  assert.match(reports, /\{canViewExpenses && \(/)
  assert.match(migration, /create table if not exists public\.expenses/)
  assert.match(migration, /entry_type\s+text not null default 'expense'/)
  assert.match(migration, /category in/)
  assert.match(migration, /investor_support/)
  assert.match(migration, /other_income/)
  assert.match(migration, /payment_method in \('cash', 'card', 'terminal'\)/)
  assert.match(expenseIncomeMigration, /add column if not exists entry_type text/)
  assert.match(expenseIncomeMigration, /expenses_entry_type_check/)
  assert.match(expenseIncomeMigration, /investor_support/)
  assert.match(migration, /owner_read_expenses/)
  assert.match(migration, /owner_insert_expenses/)
  assert.match(migration, /owner_delete_expenses/)
  assert.doesNotMatch(migration, /current_staff_has_role\(array\['owner','admin'/)
  assert.match(ownerOnlyMigration, /drop policy if exists "staff_read_expenses"/)
  assert.match(ownerOnlyMigration, /owner_read_expenses/)
  assert.match(ownerOnlyMigration, /owner_insert_expenses/)
  assert.match(ownerOnlyMigration, /owner_delete_expenses/)
  assert.doesNotMatch(ownerOnlyMigration, /current_staff_has_role\(array\['owner','admin'/)
  assert.match(salaryMigration, /create table if not exists public\.employee_salary_profiles/)
  assert.match(salaryMigration, /profile_id\s+uuid references public\.profiles\(id\) on delete set null/)
  assert.match(salaryMigration, /create unique index if not exists idx_employee_salary_profiles_profile_id_unique/)
  assert.match(salaryMigration, /create table if not exists public\.employee_salary_rates/)
  assert.match(salaryMigration, /create table if not exists public\.employee_salary_payments/)
  assert.match(salaryMigration, /effective_from/)
  assert.match(salaryMigration, /rate_unit/)
  assert.match(salaryMigration, /pay_schedule in \('daily', 'twice_weekly', 'monthly'\)/)
  assert.match(salaryUpgradeMigration, /add column if not exists amount integer/)
  assert.match(salaryUpgradeMigration, /add column if not exists rate_unit text/)
  assert.match(salaryUpgradeMigration, /coalesce\(amount, daily_amount\)/)
  assert.match(salaryUpgradeMigration, /rate_unit in \('daily', 'monthly'\)/)
  assert.match(salaryProfileEndDateMigration, /add column if not exists ended_at date/)
  assert.match(salaryProfileEndDateMigration, /ended_at is null or ended_at >= joined_at/)
  assert.match(salaryBonusMigration, /create table if not exists public\.employee_salary_bonuses/)
  assert.match(salaryBonusMigration, /payment_method in \('cash', 'card', 'terminal'\)/)
  assert.match(salaryFineMigration, /create table if not exists public\.employee_salary_fines/)
  assert.match(salaryFineMigration, /reason\s+text not null check \(length\(trim\(reason\)\) > 0\)/)
  assert.match(salaryFineMigration, /current_staff_can_access\('expenses'\)/)
  assert.match(salaryFineMigration, /current_staff_can_write\('expenses'\)/)
  assert.match(salaryFineMigration, /when 'employee_salary_fines' then 'salary_fine'/)
  assert.match(salaryFineMigration, /after insert or update or delete on public\.employee_salary_fines/)
  assert.match(salaryCompatMigration, /add column if not exists daily_amount integer/)
  assert.match(salaryCompatMigration, /alter column daily_amount drop not null/)
  assert.match(salaryManualNamesMigration, /alter column profile_id drop not null/)
  assert.match(salaryManualNamesMigration, /drop constraint if exists employee_salary_profiles_profile_id_key/)
  assert.match(salaryManualNamesMigration, /where profile_id is not null/)
  assert.match(salaryDropPeriodMigration, /drop column if exists period_from/)
  assert.match(salaryDropPeriodMigration, /drop column if exists period_to/)
  assert.match(salaryAbsenceMigration, /create table if not exists public\.employee_salary_absences/)
  assert.match(salaryAbsenceMigration, /salary_profile_id uuid not null references public\.employee_salary_profiles\(id\) on delete cascade/)
  assert.match(salaryAbsenceMigration, /absence_date\s+date not null/)
  assert.match(salaryAbsenceMigration, /idx_employee_salary_absences_profile_date_unique/)
  assert.match(salaryAbsenceMigration, /owner_read_employee_salary_absences/)
  assert.match(salaryAbsenceMigration, /owner_write_employee_salary_absences/)
  assert.match(salarySafeDeleteMigration, /add column if not exists deleted_at timestamptz/)
  assert.doesNotMatch(salarySafeDeleteMigration, /delete from public\.employee_salary_profiles/i)
  assert.doesNotMatch(salarySafeDeleteMigration, /on delete cascade/i)
  assert.match(health, /checkTable\('expenses'/)
  assert.match(health, /entry_type, expense_date/)
  assert.match(health, /checkTable\('employee_salary_profiles'/)
  assert.match(health, /checkTable\('employee_salary_rates'/)
  assert.match(health, /checkTable\('employee_salary_payments'/)
  assert.doesNotMatch(health, /period_from/)
  assert.doesNotMatch(health, /period_to/)
  assert.match(health, /checkTable\('employee_salary_bonuses'/)
  assert.match(health, /checkTable\('employee_salary_fines'/)
  assert.match(health, /checkTable\('employee_salary_absences'/)
  assert.match(health, /joined_at, ended_at, deleted_at, pay_schedule/)
  assert.match(health, /amount, rate_unit/)
})

test('all accounting summary includes paid cafe income', () => {
  const history = readSource('src/pages/AccountingHistory.jsx')
  const accountingLib = readSource('src/lib/accounting.js')

  assert.match(history, /getAccountingHistoryPageSummary/)
  assert.match(history, /groupAccountingHistoryRows/)
  assert.match(history, /filterAccountingHistoryRows/)
  assert.match(history, /const \[period, setPeriod\] = useState\(\(\) => hasLinkedRange \? 'linked' : 'thisMonth'\)/)
  assert.match(history, /period === 'linked'[\s\S]*\{ dateFrom: requestedFrom, dateTo: requestedTo \}/)
  assert.match(history, /getAccountingHistoryRange\(period\)/)
  assert.match(history, /\['thisMonth', 'lastMonth', 'allTime'\]/)
  assert.match(history, /getAccountingHistoryPageSummary\(rows, accountingOrders, dateFrom, dateTo\)/)
  assert.match(history, /\.gte\('expense_date', dateFrom\)\.lte\('expense_date', dateTo\)/)
  assert.match(history, /\.gte\('paid_date', dateFrom\)\.lte\('paid_date', dateTo\)/)
  assert.match(history, /\.gte\('bonus_date', dateFrom\)\.lte\('bonus_date', dateTo\)/)
  assert.doesNotMatch(history, /\.from\('employee_salary_rates'\)/)
  assert.match(history, /\.from\('employee_salary_absences'\)/)
  assert.match(history, /buildFinalizedEmployeeMealExpenseRows/)
  assert.match(history, /\.from\('employee_daily_meal_expenses'\)/)
  assert.doesNotMatch(history, /state\.settings\?\.averageDailyEmployeeMealUzs/)
  assert.match(history, /xl:grid-cols-7/)
  assert.match(history, /\{l\.cafeIncome\}/)
  assert.match(history, /formatCurrency\(cafeIncomeSummary\.total\)/)
  assert.match(history, /formatCurrency\(salaryExpensesTotal\)/)
  assert.match(history, /formatCurrency\(employeeMealExpensesTotal\)/)
  assert.match(history, /formatCurrency\(productBazaarExpensesTotal\)/)
  assert.match(history, /formatCurrency\(otherExpensesTotal\)/)
  assert.match(history, /\{l\.investorSupport\}/)
  assert.match(history, /formatCurrency\(investorSupportTotal\)/)
  assert.doesNotMatch(history, /\{l\.totalIncome\}/)
  assert.match(history, /\}, \[dateFrom, dateTo\]\)/)
  assert.doesNotMatch(history, /\[dateFrom, dateTo, l\./)
  assert.match(accountingLib, /export function getAccountingExpenseBreakdown/)
  assert.match(accountingLib, /productBazaarExpensesTotal: summarizeExpenses\(productBazaarRows\)\.total/)
  assert.match(history, /expensePromise\.then\(expenseResult => \{[\s\S]*setExpenseRows\([\s\S]*setLoading\(false\)/)
  assert.match(history, /groupAccountingHistoryRows\(visibleRows, rows, accountingOrders\)/)
  assert.match(accountingLib, /totalExpenses: summarizeExpenses\(dayRows\)\.total/)
  assert.match(accountingLib, /const cafeIncomeSummary = getCafeIncomeForRange\(orders, group\.date, group\.date\)/)
  assert.match(accountingLib, /cafeIncome: cafeIncomeSummary\.total/)
  assert.match(accountingLib, /loyaltyIncome: cafeIncomeSummary\.loyaltyTotal/)
  assert.match(history, /\{l\.loyaltyIncome\}: \{formatCurrency\(group\.loyaltyIncome\)\}/)
  assert.match(history, /\{l\.totalExpenses\}: \{formatCurrency\(group\.totalExpenses\)\}/)
  assert.match(history, /row\.is_salary_payment \|\| row\.is_salary_bonus[\s\S]*border-l-red-500 bg-red-50\/30[\s\S]*bg-red-100 text-red-700/)
  assert.match(history, /row\.category === 'products_bazaar'[\s\S]*border-l-purple-500 bg-purple-50\/30/)
  assert.match(history, /normalizeExpenseEntryType\(row\.entry_type\) === 'income'[\s\S]*border-l-purple-500 bg-purple-50\/30/)
  assert.match(history, /return \{ row: 'border-l-orange-500 bg-orange-50\/30'/)
  assert.match(history, /\{l\.totalExpenses\}[\s\S]*text-red-600/)
  assert.match(history, /\{l\.productBazaarExpenses\}[\s\S]*text-purple-600/)
  assert.match(history, /\{l\.otherExpenses\}[\s\S]*text-\[#ff5a00\]/)
  assert.match(history, /getAccountingHistoryDeleteTarget\(row\)/)
  assert.match(history, /formatTime\(row\.created_at, '—'\)/)
  assert.doesNotMatch(history, /formatTime\(row\.expense_date/)
  assert.match(history, /async function removeRow\(row\)/)
  assert.match(history, /confirmDeleteId !== row\.id/)
  assert.match(history, /\.from\(target\.table\)[\s\S]*\.delete\(\)[\s\S]*\.select\('id'\)/)
  assert.match(history, /<Trash2 size=\{14\} \/>/)
  assert.match(accountingLib, /employee_salary_payments/)
  assert.match(accountingLib, /employee_salary_bonuses/)
})

test('accounting corrections and deletions leave an immutable database audit trail', () => {
  const migration = readSource('supabase/084_accounting_record_audit.sql')
  const health = readSource('scripts/check-db-health.js')

  assert.match(migration, /create table if not exists public\.accounting_record_audit/)
  assert.match(migration, /old_record\s+jsonb/)
  assert.match(migration, /new_record\s+jsonb/)
  assert.match(migration, /after insert or update or delete on public\.expenses/)
  assert.match(migration, /after insert or update or delete on public\.employee_salary_payments/)
  assert.match(migration, /after insert or update or delete on public\.employee_salary_bonuses/)
  assert.match(migration, /before update or delete on public\.accounting_record_audit/)
  assert.match(migration, /Accounting audit records are immutable/)
  assert.match(migration, /current_staff_can_access\('expenses'\)/)
  assert.match(health, /checkTable\('accounting_record_audit'/)
})

test('Accounting overview uses a summary while historical pages retain complete paid pagination', () => {
  const historyLoader = readSource('src/lib/orderHistory.js')
  const accountingSummaryLoader = readSource('src/lib/accountingSummary.js')
  const accountingSummaryMigration = readSource('supabase/109_accounting_paid_order_summary.sql')
  const db = readSource('src/lib/db.js')
  const accounting = readSource('src/pages/Expenses.jsx')
  const allAccounting = readSource('src/pages/AccountingHistory.jsx')
  const estimate = readSource('src/pages/MonthlyEstimate.jsx')
  const reports = readSource('src/pages/Reports.jsx')
  const dashboard = readSource('src/pages/AdminDashboard.jsx')

  assert.match(historyLoader, /\.gte\('paid_at', bounds\.instantFrom\)/)
  assert.match(historyLoader, /\.lt\('paid_at', bounds\.instantToExclusive\)/)
  assert.match(historyLoader, /\.range\(from, to\)/)
  assert.match(historyLoader, /collectPagedRows/)
  assert.match(accounting, /loadAccountingPaidOrderSummary\(dateFrom, dateTo/)
  assert.doesNotMatch(accounting, /loadPaidOrdersForRange|mergePaidOrderHistory|state\.orders/)
  assert.match(accountingSummaryLoader, /\.rpc\('get_accounting_paid_order_summary'/)
  assert.match(accountingSummaryLoader, /if \(!error\) return data \|\| \{\}/)
  assert.match(accountingSummaryLoader, /isMissingAccountingSummaryRpc\(error\)/)
  assert.match(accountingSummaryMigration, /with paid_orders as materialized/)
  assert.match(accountingSummaryMigration, /'cafe_income'/)
  assert.match(accountingSummaryMigration, /'payment_method_income'/)
  assert.match(allAccounting, /loadPaidOrdersForRange\(dateFrom, dateTo\)/)
  assert.match(allAccounting, /mergePaidOrderHistory\(paidHistoryOrders, state\.orders, dateFrom, dateTo\)/)
  assert.match(accounting, /collectPagedRows/)
  assert.match(allAccounting, /collectPagedRows/)
  assert.match(accounting, /if \(requestId !== loadRequestRef\.current\) return/)
  assert.match(estimate, /loadPaidOrdersForRange\(monthStart, monthEnd\)/)
  assert.doesNotMatch(estimate, /loadAccountingPaidOrderSummary|ACCOUNTING_HISTORY_START_DATE/)
  assert.match(estimate, /mergePaidOrderHistory\(paidHistoryOrders, state\.orders, monthStart, cutoffEnd\)/)
  assert.match(estimate, /if \(requestId !== loadRequestRef\.current\) return/)
  assert.match(reports, /loadOrdersForRange\(dateFrom, dateTo\)/)
  assert.match(reports, /mergeOrderHistory\(historyOrders, state\.orders, dateFrom, dateTo\)/)
  assert.match(dashboard, /loadPaidOrdersForRange\(dashboardHistoryRange\.dateFrom, dashboardHistoryRange\.dateTo\)/)
  assert.match(dashboard, /dateFrom: `\$\{Number\(today\.slice\(0, 4\)\) - 1\}-01-01`/)
  assert.match(db, /loadPaidOrdersForRange\(today, today\)/)
  assert.match(db, /loadActiveOrders\(\)/)
  assert.doesNotMatch(db, /loadOrdersForRange\(yearStart, today\)/)
  assert.doesNotMatch(db, /const yearStart =/)
  assert.doesNotMatch(db, /\.gte\('created_at', startOfYear\(\)\)/)
})

test('Daily Bazaar filter toolbar uses one responsive range calendar with internal presets', () => {
  const source = readSource('src/pages/DailyBazaar.jsx')
  const rangePicker = readSource('src/components/DateRangePicker.jsx')
  const toolbar = source.slice(
    source.indexOf('function RangeAndFilters'),
    source.indexOf('function BazaarEntryForm')
  )
  const dateInput = source.slice(source.indexOf('function FormattedDateInput'))

  assert.match(toolbar, /aria-labelledby="bazaar-range-heading"/)
  assert.match(toolbar, /rangeSummary = dateFrom === dateTo/)
  assert.match(source, /import DateRangePicker from '\.\.\/components\/DateRangePicker'/)
  assert.match(toolbar, /<DateRangePicker/)
  assert.match(rangePicker, /role="dialog" aria-label=\{l\.selectDateRange\}/)
  assert.match(rangePicker, /function MonthCalendar/)
  assert.match(rangePicker, /buildRangeCalendar\(monthKey\)/)
  assert.match(rangePicker, /previousCurrentWeek/)
  assert.match(rangePicker, /currentNextWeek/)
  assert.match(rangePicker, /onClick=\{applyDraft\}/)
  assert.match(toolbar, /border-t border-\[#EEF0F3\] pt-3/)
  assert.match(toolbar, /lg:grid-cols-\[minmax\(200px,260px\)_minmax\(220px,280px\)_minmax\(260px,1fr\)\]/)
  assert.match(toolbar, /id="bazaar-history-search"/)
  assert.match(toolbar, /sm:col-span-2 lg:col-span-1/)
  assert.doesNotMatch(toolbar, /AnimatedSearch/)
  assert.doesNotMatch(toolbar, /\{ key: 'week', label: l\.week \}/)
  assert.doesNotMatch(toolbar, /<FormattedDateInput value=\{dateFrom\}/)
  assert.doesNotMatch(toolbar, /min-w-\[130px\]/)
  assert.match(dateInput, /right-10[^\n]+text-ellipsis/)
})
