import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { functionBody, readSource, root, sourceFiles } from './helpers/sourceGuard.js'

test('Catering public page is routed and has Russian SEO and contact CTAs', () => {
  const app = readSource('src/App.jsx')
  const page = readSource('src/pages/CateringPage.jsx')

  assert.match(app, /path="\/catering"/)
  assert.match(page, /Кейтеринг и корпоративное питание от Zar Kebab/)
  assert.match(page, /Кейтеринг и корпоративное питание в Ташкенте \| Zar Kebab/)
  assert.match(page, /tel:\+998905095545/)
  assert.match(page, /https:\/\/www\.instagram\.com\/zarkebab/)
  assert.match(page, /Ташкент, Матбуотчилар, 17/)
  assert.match(page, /кейтеринг Ташкент, корпоративное питание Ташкент/)
})

test('PublicMenu supports direct product links and copyable item URLs', () => {
  const app = readSource('src/App.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const productCards = readSource('src/components/MenuProductCards.jsx')
  const menuLinks = readSource('src/lib/menuLinks.js')

  assert.match(app, /path="\/menu\/item\/:itemId"/)
  assert.match(app, /path="\/premium-menu\/item\/:itemId"/)
  assert.match(publicMenu, /useParams/)
  assert.match(publicMenu, /findMenuItemByLinkKey\(displayItems, itemId\)/)
  assert.match(publicMenu, /navigate\(getMenuItemPublicPath\(item, menuBasePath\)\)/)
  assert.match(publicMenu, /premium \? '\/premium-menu' : '\/menu'/)
  assert.match(publicMenu, /const showDetailOverlay = Boolean\(detailItem\)/)
  assert.match(publicMenu, /showDetailOverlay && \(/)
  assert.match(publicMenu, /fixed inset-0 z-\[80\]/)
  assert.match(publicMenu, /languageControl=\{premium/)
  assert.match(productCards, /languageControl = null/)
  assert.match(productCards, /\{languageControl\}/)
  assert.doesNotMatch(publicMenu, /if \(detailItem\) \{/)
  assert.match(productCards, /linkBasePath = '\/menu'/)
  assert.match(productCards, /getMenuItemPublicUrl\(item, globalThis\.location\?\.origin, linkBasePath\)/)
  assert.match(productCards, /copyTextToClipboard/)
  assert.match(productCards, /<Copy size=\{15\}/)
  assert.match(productCards, /<Copy size=\{14\}/)
  assert.match(menuLinks, /external_id \|\| item\?\.externalId \|\| item\?\.id/)
  assert.match(menuLinks, /basePath = '\/menu'/)
  assert.match(menuLinks, /\$\{normalizedBase\}\/item\/\$\{encodeURIComponent\(key\)\}/)
})

test('Premium public menu uses tourist pricing without duplicating menu items', () => {
  const app = readSource('src/App.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')

  assert.match(app, /path="\/premium-menu"/)
  assert.match(publicMenu, /export default function PublicMenu\(\{ premium = false, searchMode = false \}\)/)
  assert.match(publicMenu, /const \[premiumLang, setPremiumLang\] = useState\('en'\)/)
  assert.match(publicMenu, /useState\(\(\) => premium \? 'USD' : getDefaultMenuCurrency\(\)\)/)
  assert.match(publicMenu, /const lang = premium \? premiumLang : appLang/)
  assert.match(publicMenu, /premium \? <LanguageSwitcher value=\{lang\} onChange=\{setPremiumLang\} \/> : <LanguageSwitcher \/>/)
  assert.match(publicMenu, /getMenuItemForPriceMode\(item, 'tourist'\)/)
  assert.match(publicMenu, /Premium Menu/)
  assert.doesNotMatch(publicMenu, new RegExp('20% ' + 'higher'))
  assert.doesNotMatch(publicMenu, /Turistlar uchun 20% yuqori narxlar/)
  assert.doesNotMatch(publicMenu, /Цены для туристов на 20% выше/)
  assert.doesNotMatch(publicMenu, new RegExp('Live ' + 'rates'))
  assert.doesNotMatch(publicMenu, new RegExp('Saved ' + 'rates'))
})

test('MenuCategoryScroller collapsed chips do not overlap expanded category cards', () => {
  const source = readSource('src/components/MenuCategoryScroller.jsx')

  assert.doesNotMatch(source, /-mt-\[61px\]/)
  assert.match(source, /const COLLAPSED_BAR_HEIGHT = 56/)
  assert.match(source, /flex h-10 w-auto/)
  assert.match(source, /py-1\.5/)
  assert.match(source, /const COLLAPSE_SHOW_OFFSET = 61/)
  assert.match(source, /const COLLAPSE_HIDE_OFFSET = 28/)
  assert.match(source, /maxHeight: collapsedPosition === 'fixed' \|\| collapsed \? COLLAPSED_BAR_HEIGHT : 0/)
  assert.doesNotMatch(source, /height: collapsed \? COLLAPSED_BAR_HEIGHT/)
  assert.match(source, /setCollapsed\(isCollapsed =>/)
  assert.match(source, /scrollOffset \+ 8/)
  assert.doesNotMatch(source, /\+ 82/)
  assert.match(source, /aria-pressed=\{active\}/)
  assert.match(source, /min-w-\[92px\] w-\[92px\]/)
  assert.match(source, /text-\[10\.5px\]/)
  assert.match(source, /object-cover object-center/)
  assert.doesNotMatch(source, /scale-\[1\.04\] object-cover object-top/)
  assert.match(source, /rounded-\[18px\]/)
  assert.match(source, /shadow-none ring-1 ring-inset ring-\[#ff5a1f\]\/10/)
  assert.doesNotMatch(source, /shadow-\[0_8px_18px_rgba\(255,90,31,0\.16\)\]/)
  assert.match(source, /active \? 'bg-transparent' : 'bg-\[#F8FAFC\]'/)
  assert.doesNotMatch(source, /rounded-t-\[16px\]/)
  assert.doesNotMatch(source, /rounded-b-\[16px\]/)
  assert.match(source, /if \(scrollToCategory\(category\.id\)\) \{/)
  assert.match(source, /const stickyBarOffset = collapsed && collapsedPosition === 'sticky'/)
  assert.match(source, /getMenuCategoryScrollTarget\(\{/)
  assert.match(source, /pendingCategoryRef\.current = category\.id/)
  assert.match(source, /pendingCategoryTimerRef\.current = window\.setTimeout/)
  assert.match(source, /return true/)
  assert.match(source, /if \(!section\) return false/)
})

test('MenuCategoryScroller scrolls inside the nearest app content scroller', () => {
  const source = readSource('src/components/MenuCategoryScroller.jsx')

  assert.match(source, /function findScrollContainer/)
  assert.match(source, /overflowY/)
  assert.match(source, /scrollContainerRef\?\.current \|\| findScrollContainer\(sentinelRef\.current\) \|\| window/)
  assert.match(source, /scrollContainerRef\?\.current \|\| findScrollContainer\(sentinelRef\.current\) \|\| document\.documentElement/)
})

test('Admin menu pins collapsed categories to its AppShell scroll area', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const scroller = readSource('src/components/MenuCategoryScroller.jsx')

  assert.match(adminMenu, /sectionPrefix="admin-menu-category"[\s\S]*scrollContainerRef=\{shellScrollRef\}/)
  assert.match(adminMenu, /sectionPrefix="admin-menu-category"[\s\S]*collapsedPosition="fixed"/)
  assert.match(scroller, /const \[fixedInsets, setFixedInsets\] = useState\(null\)/)
  assert.match(scroller, /const rootRect = scroller\.getBoundingClientRect\(\)/)
  assert.match(scroller, /top: fixedInsets\?\.top \?\? topOffset/)
  assert.match(scroller, /left: fixedInsets\.left, right: fixedInsets\.right/)
})

test('PublicMenu enables tappable fixed collapsed categories', () => {
  const source = readSource('src/pages/PublicMenu.jsx')

  assert.match(source, /const headerRef = useRef\(null\)/)
  assert.match(source, /getBoundingClientRect\(\)\.height/)
  assert.match(source, /new ResizeObserver\(updateHeaderOffset\)/)
  assert.match(source, /<header ref=\{headerRef\}/)
  assert.match(source, /collapsedPosition="fixed"/)
  assert.match(source, /collapsedClassName="z-50/)
  assert.match(source, /scrollOffset=\{64\}/)
  assert.match(source, /px-3 pb-5 pt-3 sm:px-6 sm:pt-5/)
  assert.match(source, /hidden grid-cols-\[1fr_auto_1fr\] items-center gap-3 lg:grid/)
  assert.match(source, /flex items-center gap-2\.5 justify-self-center sm:gap-3/)
  assert.match(source, /relative flex h-11 items-center justify-between lg:hidden/)
  assert.match(source, /text-\[7px\][^"\n]*min-\[360px\]:text-\[8px\][^"\n]*min-\[400px\]:text-\[10px\][^>]*>Zar Kebab<\/span>/)
  assert.doesNotMatch(source, /min-\[460px\]:inline/)
  assert.match(source, /function CompactCurrencySelect/)
  assert.match(source, /min-\[400px\]:hidden/)
  assert.match(source, /MENU_CURRENCIES\.map\(currency => \(\{ value: currency, label: currency \}\)\)/)
  assert.doesNotMatch(source.slice(source.indexOf('<header ref={headerRef}'), source.indexOf('</header>')), /PublicContactButtons/)
  assert.match(source, /className="mb-5 mt-0 rounded-\[22px\]/)
  assert.match(source, /function MobileSearchPage/)
  assert.match(source, /const \[mobileSearchOpen, setMobileSearchOpen\] = useState\(false\)/)
  assert.match(source, /setMobileSearchOpen\(true\)/)
  assert.match(source, /<MobileSearchPage/)
  assert.match(source, /if \(searchMode\) \{[\s\S]*<MobileSearchPage[\s\S]*open[\s\S]*categories=\{categoryCards\}/)
  assert.match(source, /open=\{mobileSearchOpen\}/)
  assert.match(source, /function MenuSectionHeader\(\{ title, tone = 'default' \}\)/)
  assert.match(source, /<div className="h-px min-w-0 flex-1 bg-\[#C9C9C9\]"/)
  assert.match(source, /<MenuSectionHeader title=\{getCategoryName\(section\.cat, lang\)\} \/>/)
  assert.match(source, /<MenuSectionHeader title=\{dealsTitle\} tone="deal" \/>/)
  assert.doesNotMatch(source, /\{section\.items\.length\} \{lang/)
  assert.doesNotMatch(source, /\{dealItems\.length\} \{lang/)
  assert.match(source, /const searchResults = useMemo/)
  assert.match(source, /items=\{searchResults\}/)
  assert.match(source, /items: displayItems\.filter\(item => item\.category_id === cat\.id\)/)
  assert.match(source, /displayItems\.length === 0/)
  assert.doesNotMatch(source, /items=\{filteredItems\}/)
  assert.doesNotMatch(source, /import AnimatedSearch/)
  assert.doesNotMatch(source, /className="hidden sm:flex sm:max-w-\[420px\]"/)
  assert.doesNotMatch(source, /floatingMaxWidth=\{720\}/)
  assert.doesNotMatch(source, /variant="overlay"/)
  assert.match(source, /displayCategories\.filter\(category => \(itemCounts\[category\.id\] \|\| 0\) > 0\)/)
  assert.doesNotMatch(source, /px-4 py-5 sm:px-6/)
  assert.doesNotMatch(source, /className="mb-7 mt-3 rounded-\[28px\]/)
})

test('public search has its own route, filters by one category, and vacancies have detail routes', () => {
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const vacancies = readSource('src/pages/PublicVacancies.jsx')
  const app = readSource('src/App.jsx')

  assert.match(app, /path="\/search"[^\n]*<PublicMenu searchMode \/>/)
  assert.match(publicMenu, /const \[searchCategoryId, setSearchCategoryId\] = useState\('all'\)/)
  assert.match(publicMenu, /searchCategoryId === 'all' \|\| item\.category_id === searchCategoryId/)
  assert.match(publicMenu, /categories=\{categoryCards\}/)
  assert.match(publicMenu, /aria-pressed=\{active\}/)
  assert.match(publicMenu, /onClick=\{\(\) => onSelectCategory\(category\.id\)\}/)
  assert.match(publicMenu, /onSelectCategory=\{setSearchCategoryId\}/)
  assert.doesNotMatch(publicMenu, /function openCategoryFromSearch/)
  assert.match(app, /path="\/vacancies\/:vacancyId"/)
  assert.match(vacancies, /useParams\(\)/)
  assert.match(vacancies, /selectedPosition\.responsibilities/)
  assert.match(vacancies, /selectedPosition\.requirements/)
  assert.match(vacancies, /to=\{`\/vacancies\/\$\{key\}`\}/)
  assert.match(vacancies, /animatedNavigate\(event, selectedPosition \? '\/vacancies' : '\/menu'\)/)
  assert.match(vacancies, /selectedPosition \? copy\.backToVacancies : copy\.back/)
  assert.doesNotMatch(vacancies, /animatedNavigate\(event, -1\)/)
  assert.match(vacancies, /key: 'hostess'/)
  assert.match(vacancies, /Rus tilida erkin gaplasha olish — majburiy/)
  assert.match(vacancies, /Tajriba bo‘lsa yaxshi, tajribasiz nomzodlarga ish o‘rgatiladi/)
  assert.doesNotMatch(vacancies, /key: 'cashier'/)
})

test('the Zar Kebab public website defaults to Russian once and then preserves visitor choice', () => {
  const helpers = readSource('src/store/reducerHelpers.js')
  const loader = functionBody(helpers, 'loadInitialLang')

  assert.match(loader, /hostname === 'zarkebab\.uz'/)
  assert.match(loader, /hostname === 'www\.zarkebab\.uz'/)
  assert.match(loader, /zk_public_default_lang_ru_v1/)
  assert.match(loader, /localStorage\.setItem\('zk_lang', 'ru'\)/)
  assert.match(loader, /localStorage\.getItem\('zk_lang'\) \|\| 'ru'/)
})

test('menu item discounts use old_price for display and public deals', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const productCards = readSource('src/components/MenuProductCards.jsx')
  const telegram = readSource('src/pages/TelegramMiniApp.jsx')
  const dbHealth = readSource('src/lib/dbHealth.js')
  const schema = readSource('supabase/003_pos_schema.sql')
  const migration = readSource('supabase/036_menu_item_old_price.sql')

  assert.match(adminMenu, /old_price: ''/)
  assert.match(adminMenu, /old_price: Math\.max\(0, Math\.round\(numberFromMoneyInput\(form\.old_price\)\)\)/)
  assert.match(adminMenu, /onChange=\{setF\('old_price'\)\}/)
  assert.match(productCards, /line-through/)
  assert.match(productCards, /text-red-600/)
  assert.match(telegram, /getMenuPricing/)
  assert.match(publicMenu, /const dealItems = useMemo/)
  assert.match(publicMenu, /id="public-menu-deals"/)
  assert.match(publicMenu, /key=\{`deal-\$\{item\.id\}`\}/)
  assert.match(schema, /old_price\s+integer\s+not null default 0/)
  assert.match(migration, /add column if not exists old_price integer not null default 0/)
  assert.match(dbHealth, /'old_price'/)
})

test('menu costs stay private, snapshot onto sold items, and drive profit outputs', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const dashboard = readSource('src/pages/AdminDashboard.jsx')
  const accountingPage = readSource('src/pages/Expenses.jsx')
  const accounting = readSource('src/lib/accounting.js')
  const db = readSource('src/lib/db.js')
  const telegramApi = readSource('api/telegram/order-status.js')
  const telegramMessage = readSource('api/telegram/_lib/orderStatusMessages.js')
  const profit = readSource('src/lib/profit.js')
  const migration = readSource('supabase/098_menu_item_costs_and_profit.sql')
  const variantMigration = readSource('supabase/100_menu_variant_costs_and_accounting_profit.sql')
  const accountingSummaryMigration = readSource('supabase/114_freeze_historical_order_prices_and_costs.sql')
  const atomicCreationMigration = readSource('supabase/102_atomic_menu_item_cost_creation.sql')
  const mediaGalleryMigration = readSource('supabase/103_menu_item_media_gallery.sql')
  const dbHealth = readSource('src/lib/dbHealth.js')
  const cliHealth = readSource('scripts/check-db-health.js')

  assert.match(adminMenu, /cost_price: ''/)
  assert.match(adminMenu, /cost_price: Math\.max\(0, Math\.round\(numberFromMoneyInput\(form\.cost_price\)\)\)/)
  assert.match(adminMenu, /onChange=\{setF\('cost_price'\)\}/)
  assert.match(adminMenu, /hasValidNewItemCost = itemModal !== 'new' \|\| hasRequiredMenuItemCost\(form\.cost_price\)/)
  assert.match(adminMenu, /itemModal === 'new' && requiredCost === null/)
  assert.match(adminMenu, /costRequired=\{itemModal === 'new'\}/)
  assert.match(adminMenu, /required=\{costRequired\}/)
  assert.match(migration, /create table if not exists public\.menu_item_costs/)
  assert.match(migration, /revoke all on public\.menu_item_costs from anon/)
  assert.match(migration, /current_staff_can_access_any\(array\['dashboard','menu'\]\)/)
  assert.match(migration, /create trigger trg_snapshot_order_item_cost/)
  assert.match(migration, /new\.cost_price := \(/)
  assert.match(variantMigration, /add column if not exists variant_costs jsonb/)
  assert.match(variantMigration, /current_staff_can_access_any\(array\['dashboard','menu','expenses'\]\)/)
  assert.match(variantMigration, /item_cost\.variant_costs \? selection\.value/)
  assert.match(atomicCreationMigration, /create or replace function public\.create_menu_item_with_cost\(payload jsonb\)/)
  assert.match(atomicCreationMigration, /real_cost <= 0/)
  assert.match(atomicCreationMigration, /insert into public\.menu_item_costs/)
  assert.match(mediaGalleryMigration, /create_menu_item_with_media_and_cost/)
  assert.match(mediaGalleryMigration, /public\.create_menu_item_with_cost\(/)
  assert.match(dbHealth, /media_urls/)
  assert.match(dbHealth, /create_menu_item_with_media_and_cost/)
  assert.match(cliHealth, /media_urls/)
  assert.match(cliHealth, /create_menu_item_with_media_and_cost/)
  assert.match(db, /select\('menu_item_id, cost_price, variant_costs'\)/)
  assert.match(db, /variant_costs: normalizeVariantCosts\(variantCosts \?\? _variantCostsAlias\)/)
  assert.match(adminMenu, /cost: lang === 'uz' \? 'Haqiqiy tannarx'/)
  assert.match(adminMenu, /variant_costs: editorToVariantCosts\(form\.option_groups_editor\)/)
  assert.match(adminMenu, /function ProfitMarginPreview/)
  assert.match(adminMenu, /getSaleProfitSummary\(numberFromMoneyInput\(price\), numberFromMoneyInput\(cost\)\)/)
  assert.match(adminMenu, /summary\.markupPct/)
  assert.match(adminMenu, /markup: 'Наценка'/)
  assert.match(adminMenu, /<ProfitMarginPreview price=\{form\.price\} cost=\{form\.cost_price\} lang=\{lang\}/)
  assert.match(adminMenu, /<ProfitMarginPreview price=\{option\.price\} cost=\{effectiveCost\} lang=\{lang\} inheritedCost=\{!hasOwnCost\}/)
  assert.match(profit, /getOrderRevenueTotal\(order\) - getOrderCostTotal\(order, menuItemMap\)/)
  assert.match(profit, /export function getOrderProfitMarginPct/)
  assert.match(profit, /export function getOrderItemCostPrice\(item\)[\s\S]*return snapshotCost \?\? 0/)
  assert.doesNotMatch(profit, /menuItemFor\(|getSelectedVariantCost\(/)
  assert.match(dashboard, /label=\{`\$\{l\.netProfit\} · \$\{currentKpiPeriodLabel\}`\}/)
  assert.match(dashboard, /getSaleProfitSummary\(\s*currentRevenue,\s*currentRevenue - currentNetProfit\s*\)\?\.marginPct/)
  assert.match(dashboard, /value=\{formatCurrencyWithPercentage\(periodNetProfit, periodProfitMargin, lang\)\}/)
  assert.match(accounting, /const costTotal = getOrdersCostTotal\(paidOrders, menuItemMap\)/)
  assert.match(accounting, /const netProfit = normalizedOrderSummary\.cafeIncome - normalizedOrderSummary\.costTotal/)
  assert.match(accounting, /profitMarginPct/)
  assert.match(accounting, /getSaleProfitSummary\(\s*normalizedOrderSummary\.cafeIncome,\s*normalizedOrderSummary\.costTotal\s*\)\?\.marginPct/)
  assert.match(accountingSummaryMigration, /greatest\(0, sold_item\.cost_price::numeric\)/)
  assert.doesNotMatch(accountingSummaryMigration, /left join public\.menu_item_costs/)
  assert.match(accountingSummaryMigration, /disable trigger guard_paid_order_items/)
  assert.match(accountingSummaryMigration, /exception[\s\S]*enable trigger guard_paid_order_items/)
  assert.match(accountingSummaryMigration, /trigger\.tgenabled[\s\S]*paid_order_items_guard_state/)
  assert.match(accountingSummaryMigration, /enable replica trigger guard_paid_order_items/)
  assert.match(accountingSummaryMigration, /enable always trigger guard_paid_order_items/)
  assert.match(accountingPage, /value=\{loading \? '—' : formatCurrencyWithPercentage\(netProfit, profitMarginPct, lang\)\}/)
  assert.match(accountingPage, /tone=\{netProfit >= 0 \? 'green' : 'red'\}\s+emphasizeValue/)
  assert.match(accountingPage, /const valueTone = emphasizeValue \? valueTones\[tone\]/)
  assert.match(telegramApi, /dailyNetProfitTotal/)
  assert.match(telegramApi, /dailyProfitMarginPct/)
  assert.match(telegramApi, /orderNetProfit/)
  assert.match(telegramApi, /orderProfitMarginPct/)
  assert.match(telegramApi, /getOrderProfitMarginPct\(order\)/)
  assert.match(telegramApi, /getSaleProfitSummary\(revenueTotal, costTotal\)/)
  assert.match(telegramApi, /hasCompleteOrderItemCostCoverage\(items = \[\]\)/)
  assert.match(telegramApi, /getOrderNetProfit\(order\)/)
  assert.match(telegramApi, /const costTotal = getOrdersCostTotal\(orders\)/)
  assert.doesNotMatch(telegramApi, /\.from\('menu_item_costs'\)/)
  assert.match(telegramApi, /revenueTotal - costTotal/)
  assert.match(telegramMessage, /Чистая прибыль:/)
  assert.match(telegramMessage, /Доход:/)
  assert.match(telegramMessage, /dailyProfitMarginPct/)
  assert.doesNotMatch(telegramMessage, /· Заказ|· Сегодня|Маржа прибыли/)
  assert.doesNotMatch(telegramMessage, /`Официант:/)
  assert.doesNotMatch(telegramMessage, /`Закрыл:/)
  assert.match(dbHealth, /menu_item_costs/)
  assert.match(cliHealth, /menu_item_costs/)
})

test('AdminMenu product editor formats price inputs while storing digits', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const moneyInput = readSource('src/lib/moneyInput.js')
  const moneyField = functionBody(adminMenu, 'MoneyField')
  const pricingFields = functionBody(adminMenu, 'PricingFields')
  const optionEditor = functionBody(adminMenu, 'OptionGroupsEditor')

  assert.match(moneyInput, /export function normalizeMoneyInput/)
  assert.match(moneyInput, /export function formatMoneyInput/)
  assert.match(moneyInput, /export function numberFromMoneyInput/)
  assert.match(adminMenu, /import \{ formatMoneyInput, normalizeMoneyInput, numberFromMoneyInput \} from '\.\.\/lib\/moneyInput'/)
  assert.match(moneyField, /type="text"/)
  assert.match(moneyField, /inputMode="numeric"/)
  assert.match(moneyField, /value=\{formatMoneyInput\(value\)\}/)
  assert.match(moneyField, /onChange=\{event => onChange\(\{ target: \{ value: normalizeMoneyInput\(event\.target\.value\) \} \}\)\}/)
  assert.match(adminMenu, /price: numberFromMoneyInput\(form\.price\)/)
  assert.match(pricingFields, /<MoneyField label=\{`\$\{labels\.current\} \(UZS\$\{priceUnit\}\)`\} value=\{form\.price\} onChange=\{setF\('price'\)\}/)
  assert.match(pricingFields, /<MoneyField label=\{`\$\{labels\.old\} \(UZS\)`\} value=\{form\.old_price\} onChange=\{setF\('old_price'\)\}/)
  assert.match(pricingFields, /label=\{`\$\{labels\.cost\} \(UZS\$\{priceUnit\}\)\$\{costRequired \? ' \*' : ''\}`\}[\s\S]*value=\{form\.cost_price\}[\s\S]*onChange=\{setF\('cost_price'\)\}/)
  assert.match(pricingFields, /\{labels\.private\}/)
  assert.match(pricingFields, /techCardCost \? labels\.techCardHint : labels\.hint/)
  assert.match(adminMenu, /<PricingFields form=\{form\} setF=\{setF\} lang=\{lang\}/)
  assert.match(optionEditor, /<MoneyField[\s\S]*label=\{labels\.price\}[\s\S]*updateOption\(optionIndex, \{ price: event\.target\.value \}\)/)
  assert.match(optionEditor, /xl:grid-cols-\[minmax\(0,1fr\)_auto\]/)
  assert.match(optionEditor, /grid min-w-0 gap-3 sm:grid-cols-3/)
  assert.match(optionEditor, /\{labels\.visibility\}/)
  assert.equal((optionEditor.match(/mb-1\.5 flex h-10 items-end text-\[11px\] font-black leading-4/g) || []).length, 4)
  assert.doesNotMatch(optionEditor, /lg:grid-cols-\[minmax\(0,1fr\)_minmax\(0,1fr\)_minmax\(0,1fr\)_auto_40px\]/)
  assert.doesNotMatch(adminMenu, /<Field label=\{`\$\{lang === 'uz' \? 'Hozirgi narx'[\s\S]*type="number"/)
  assert.doesNotMatch(adminMenu, /<Field label=\{`\$\{lang === 'uz' \? 'Eski narx'[\s\S]*type="number"/)
})

test('menu items expose generated immutable external provider ids', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const db = readSource('src/lib/db.js')
  const reducer = readSource('src/store/menuReducer.js')
  const dbHealth = readSource('src/lib/dbHealth.js')
  const schema = readSource('supabase/003_pos_schema.sql')
  const migration = readSource('supabase/037_menu_item_external_id.sql')
  const immutableMigration = readSource('supabase/038_generate_immutable_menu_item_external_ids.sql')

  assert.match(adminMenu, /external_id: ''/)
  assert.match(adminMenu, /generateMenuExternalId\(\)/)
  assert.doesNotMatch(adminMenu, /onChange=\{setF\('external_id'\)\}/)
  assert.match(adminMenu, /function ExternalIdBadge/)
  assert.match(adminMenu, /externalId\.includes\(q\)/)
  assert.match(db, /delete fields\.external_id/)
  assert.match(reducer, /external_id: i\.external_id \|\| action\.payload\.external_id \|\| ''/)
  assert.match(schema, /external_id\s+text\s+not null default public\.generate_menu_item_external_id\(\)/)
  assert.match(schema, /idx_menu_items_external_id_unique/)
  assert.match(schema, /trg_menu_items_external_id/)
  assert.match(migration, /add column if not exists external_id text not null default public\.generate_menu_item_external_id\(\)/)
  assert.match(immutableMigration, /update public\.menu_items/)
  assert.match(immutableMigration, /new\.external_id := coalesce\(nullif\(old\.external_id, ''\), public\.generate_menu_item_external_id\(\)\)/)
  assert.match(migration, /where external_id <> ''/)
  assert.match(dbHealth, /'external_id'/)
})

test('starter cafe menu expansion seeds polished categories and items', () => {
  const migration = readSource('supabase/030_starter_cafe_menu_expansion.sql')
  const repairMigration = readSource('supabase/031_fix_starter_menu_image_urls.sql')

  for (const category of ['combos', 'sides', 'desserts']) {
    assert.match(migration, new RegExp(`'${category}'`))
  }

  for (const item of [
    'zk_mixed_grill',
    'zk_family_grill_set',
    'zk_takeaway_box',
    'zk_shorva',
    'zk_plov',
    'zk_qurutob',
    'zk_fries',
    'zk_ayran',
    'zk_baklava',
  ]) {
    assert.match(migration, new RegExp(`'${item}'`))
  }

  assert.match(migration, /on conflict \(id\) do nothing/)
  assert.doesNotMatch(migration, /source\.unsplash\.com/)
  assert.doesNotMatch(repairMigration, /source\.unsplash\.com/)
  assert.match(repairMigration, /update public\.menu_categories/)
  assert.match(repairMigration, /update public\.menu_items/)
  assert.match(repairMigration, /'combos'/)
  assert.match(repairMigration, /'zk_mixed_grill'/)
})

test('Qurutoba parent name stays neutral because portions are required variants', () => {
  const migration = readSource('supabase/086_fix_qurutoba_parent_name.sql')

  assert.match(migration, /external_id = 'MI-1C334BBA79'/)
  assert.match(migration, /set[\s\S]*name_en = 'Qurutoba'\s+where/)
})

test('ImageLoadShimmer keeps slow menu images loading after timeout', () => {
  const source = readSource('src/components/ImageLoadShimmer.jsx')

  assert.match(source, /timeoutMs = 12000/)
  assert.match(source, /setTimedOut\(true\)/)
  assert.doesNotMatch(source, /setTimeout\(\(\) => setFailed\(true\)/)
  assert.match(source, /<img[\s\S]*src=\{src\}/)
  assert.match(source, /decoding="async"/)
})

test('menu items support and display nutrition values', () => {
  const schema = readSource('supabase/003_pos_schema.sql')
  const migration = readSource('supabase/032_menu_item_kcal.sql')
  const gramsMigration = readSource('supabase/033_menu_item_grams.sql')
  const millilitresMigration = readSource('supabase/034_menu_item_millilitres.sql')
  const stockMigration = readSource('supabase/050_menu_item_stock_count.sql')
  const dbHealth = readSource('src/lib/dbHealth.js')
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const categoryScroller = readSource('src/components/MenuCategoryScroller.jsx')
  const productCards = readSource('src/components/MenuProductCards.jsx')
  const cartPanel = readSource('src/components/CartPanel.jsx')
  const cashierBill = readSource('src/pages/CashierBill.jsx')
  const reports = readSource('src/pages/Reports.jsx')
  const telegramMiniApp = readSource('src/pages/TelegramMiniApp.jsx')
  const nutrition = readSource('src/lib/nutrition.js')

  assert.match(schema, /kcal\s+integer\s+not null default 0/)
  assert.match(schema, /grams\s+integer\s+not null default 0/)
  assert.match(schema, /millilitres\s+integer\s+not null default 0/)
  assert.match(schema, /stock_count\s+integer\s+not null default 0/)
  assert.match(migration, /add column if not exists kcal integer not null default 0/)
  assert.match(migration, /menu_items_kcal_nonnegative/)
  assert.match(migration, /'zk_mixed_grill', 1650/)
  assert.match(gramsMigration, /add column if not exists grams integer not null default 0/)
  assert.match(gramsMigration, /menu_items_grams_nonnegative/)
  assert.match(gramsMigration, /'zk_mixed_grill', 900/)
  assert.match(millilitresMigration, /add column if not exists millilitres integer not null default 0/)
  assert.match(millilitresMigration, /menu_items_millilitres_nonnegative/)
  assert.match(millilitresMigration, /'m12', 500/)
  assert.match(stockMigration, /add column if not exists stock_count integer not null default 0/)
  assert.match(stockMigration, /menu_items_stock_count_nonnegative/)
  assert.match(schema, /'m1'[\s\S]*?80000, 450, 0, 980/)
  assert.match(migration, /'zk_family_grill_set', 3200/)
  assert.match(gramsMigration, /'zk_family_grill_set', 1900/)
  assert.match(dbHealth, /'kcal'/)
  assert.match(dbHealth, /'grams'/)
  assert.match(dbHealth, /'millilitres'/)
  assert.match(dbHealth, /'stock_count'/)
  assert.match(nutrition, /function gramsLabel/)
  assert.match(nutrition, /function millilitresLabel/)
  assert.match(nutrition, /millilitres >= 1000/)
  assert.match(adminMenu, /setF\('kcal'\)/)
  assert.match(adminMenu, /setF\('grams'\)/)
  assert.match(adminMenu, /setF\('millilitres'\)/)
  assert.match(adminMenu, /setF\('stock_count'\)/)
  assert.match(adminMenu, /Math\.max\(0, Math\.round\(Number\(form\.kcal\) \|\| 0\)\)/)
  assert.match(adminMenu, /Math\.max\(0, Math\.round\(Number\(form\.grams\) \|\| 0\)\)/)
  assert.match(adminMenu, /Math\.max\(0, Math\.round\(Number\(form\.millilitres\) \|\| 0\)\)/)
  assert.match(adminMenu, /Math\.max\(0, Math\.round\(Number\(form\.stock_count\) \|\| 0\)\)/)
  assert.match(adminMenu, /stock_count: i\.stock_count \?\? i\.stockCount \?\? 0/)
  assert.match(adminMenu, /Shelf count/)
  assert.match(categoryScroller, /text-\[11px\] font-black tabular-nums/)
  for (const source of [adminMenu, productCards, cartPanel, cashierBill, reports, telegramMiniApp]) {
    assert.match(source, /kcalLabel/)
    assert.match(source, /gramsLabel/)
    assert.match(source, /millilitresLabel/)
  }
})

test('menu items support required option variants with parent product ids', () => {
  const schema = readSource('supabase/003_pos_schema.sql')
  const optionMigration = readSource('supabase/071_menu_item_option_groups.sql')
  const selectedOptionsMigration = readSource('supabase/072_order_item_selected_options.sql')
  const dbHealth = readSource('src/lib/dbHealth.js')
  const dbHealthScript = readSource('scripts/check-db-health.js')
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const productCards = readSource('src/components/MenuProductCards.jsx')
  const waiterOrder = readSource('src/pages/WaiterOrder.jsx')
  const cartReducer = readSource('src/store/cartReducer.js')
  const cartPanel = readSource('src/components/CartPanel.jsx')
  const cashierBill = readSource('src/pages/CashierBill.jsx')
  const cashierTables = readSource('src/pages/CashierTables.jsx')
  const kitchenCheckReceipt = readSource('src/pages/KitchenCheckReceipt.jsx')
  const db = readSource('src/lib/db.js')
  const rpc = readSource('supabase/070_price_modes.sql')

  assert.match(schema, /option_groups\s+jsonb\s+not null default '\[\]'::jsonb/)
  assert.match(schema, /selected_options jsonb\s+not null default '\{\}'::jsonb/)
  assert.match(optionMigration, /add column if not exists option_groups jsonb not null default '\[\]'::jsonb/)
  assert.match(selectedOptionsMigration, /add column if not exists selected_options jsonb not null default '\{\}'::jsonb/)
  assert.match(dbHealth, /'option_groups'/)
  assert.match(dbHealth, /'selected_options'/)
  assert.match(dbHealthScript, /stock_count, option_groups/)
  assert.match(dbHealthScript, /is_counter_item, selected_options/)
  assert.match(adminMenu, /function OptionGroupsEditor/)
  assert.match(adminMenu, /option_groups_editor/)
  assert.match(adminMenu, /Add variant/)
  assert.match(adminMenu, /Name \(UZ\)/)
  assert.match(adminMenu, /Name \(RU\)/)
  assert.match(adminMenu, /Name \(EN\)/)
  assert.match(adminMenu, /public_hidden: option\.public_hidden === true/)
  assert.match(adminMenu, /waiter_hidden: option\.waiter_hidden === true/)
  assert.match(adminMenu, /public_hidden: !!option\.public_hidden/)
  assert.match(adminMenu, /waiter_hidden: !!option\.waiter_hidden/)
  assert.match(adminMenu, /Public menu/)
  assert.match(adminMenu, /Waiter menu/)
  assert.doesNotMatch(adminMenu, /Option categories JSON|Категории вариантов JSON|Variant kategoriyalari JSON/)
  assert.doesNotMatch(adminMenu, /Category name|Option count|Option name/)
  assert.match(productCards, /export function getMenuItemOptionGroups/)
  assert.match(productCards, /audience = 'public'/)
  assert.match(productCards, /includeUnavailable = false/)
  assert.match(productCards, /option\?\.available !== false/)
  assert.match(productCards, /audience === 'waiter' \? !waiterHidden : !publicHidden/)
  assert.match(productCards, /includeUnavailable \|\| option\.available/)
  assert.match(productCards, /includeUnavailable: true/)
  assert.match(productCards, /No variants are currently available/)
  assert.match(productCards, /export function menuItemRequiresOptions/)
  assert.match(productCards, /export function getOrderItemOptionLines/)
  assert.match(productCards, /translatedNames\.includes\(normalizeComparableText\(rowName\)\)/)
  assert.match(productCards, /function normalizeComparableText\(value\)/)
  assert.match(productCards, /export function getManualOrderNotes/)
  assert.match(productCards, /type="radio"/)
  assert.match(productCards, /\{optionGroups\.length > 0 && \(/)
  assert.match(productCards, /const optionSectionTitle/)
  assert.match(productCards, /const shouldShowOptionSectionTitle/)
  assert.match(productCards, /\{shouldShowOptionSectionTitle && \(/)
  assert.match(productCards, /disabled=\{readOnly\}/)
  assert.doesNotMatch(productCards, /!\s*readOnly && optionGroups\.length > 0/)
  assert.match(productCards, /missingRequiredOptions/)
  assert.match(productCards, /const selectedOptionBasePrice = optionGroups\.reduce/)
  assert.match(productCards, /calculateUnitPrice\(selectedOptionBasePrice, itemPriceMode\)/)
  assert.match(productCards, /onAddToCart\(item, qty, finalNotes, selectedOptions, selectedOptionBasePrice\)/)
  assert.match(productCards, /optionNoteLine/)
  assert.match(waiterOrder, /menuItemRequiresOptions\(item, menuAudience\)/)
  assert.match(waiterOrder, /getMenuItemOptionGroups\(item, lang, \{ audience: menuAudience \}\)\.length > 0/)
  assert.match(waiterOrder, /quantity: normalizeMenuQuantity\(qty, item\)/)
  assert.match(waiterOrder, /currentQty=\{getMenuItemOptionGroups\(detailItem, lang, \{ audience: menuAudience \}\)\.length > 0 \? 0/)
  assert.match(waiterOrder, /map\[i\.menu_item_id\] = \(map\[i\.menu_item_id\] \|\| 0\) \+ \(Number\(i\.quantity\) \|\| 0\)/)
  assert.match(waiterOrder, /if \(menuItemRequiresOptions\(item, menuAudience\) \|\| isMenuItemSoldByWeight\(item\)\) \{\s*openDetail\(item\)/)
  assert.match(functionBody(waiterOrder, 'handleDecrement'), /if \(menuItemRequiresOptions\(item, menuAudience\) \|\| isMenuItemSoldByWeight\(item\)\) \{\s*openDetail\(item\)[\s\S]*return/)
  assert.match(kitchenCheckReceipt, /getManualOrderNotes\(item, menuItem, lang\)/)
  assert.match(waiterOrder, /cart_item_key/)
  assert.match(waiterOrder, /menu_item_id: pricedItem\.id/)
  assert.match(waiterOrder, /selected_options: hasSelectedOptions \? selectedOptions : \{\}/)
  assert.match(waiterOrder, /const displayName = menuItem \? getItemName\(menuItem, lang\) : item\.name/)
  assert.match(waiterOrder, /<p className="truncate text-\[12px\] font-black text-\[#1F2937\]">\{displayName\}<\/p>/)
  assert.match(cartReducer, /function getCartItemKey/)
  assert.match(cartReducer, /const addQuantity = normalizeMenuQuantity\(action\.payload\?\.quantity, action\.payload\)/)
  assert.match(cartReducer, /case 'UPDATE_CART_ITEM_FIELDS'/)
  assert.match(cartPanel, /function getCartItemKey/)
  assert.match(cartPanel, /const displayName = menuItem \? getItemName\(menuItem, lang\) : item\.name/)
  assert.match(cartPanel, /getOrderItemOptionLines\(item, menuItem, lang\)/)
  assert.match(cartPanel, /getManualOrderNotes\(item, menuItem, lang\)/)
  assert.match(cashierBill, /getOrderItemOptionLines\(item, mi, lang\)/)
  assert.match(cashierBill, /getManualOrderNotes\(item, mi, lang\)/)
  assert.match(cashierTables, /getOrderItemOptionLines\(item, mi, lang\)/)
  assert.match(db, /selected_options: i\.selected_options \|\| i\.selectedOptions \|\| \{\}/)
  assert.match(rpc, /selected_options/)
})
