import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { functionBody, readSource, root, sourceFiles } from './helpers/sourceGuard.js'

test('AdminMenu keeps upload errors inside the matching media fields', () => {
  const source = readSource('src/pages/AdminMenu.jsx')
  const imageField = functionBody(source, 'ImageUploadField')
  const galleryField = functionBody(source, 'MediaGalleryField')

  assert.match(imageField, /\{error && <p[^}]+>\{error\}<\/p>\}/)
  assert.match(galleryField, /\{error && <p[^}]+>\{error\}<\/p>\}/)
})

test('AdminMenu accepts verified images and product video without client recompression', () => {
  const source = readSource('src/pages/AdminMenu.jsx')
  const validator = functionBody(source, 'validateMenuImage')
  const uploadField = functionBody(source, 'MediaGalleryField')

  assert.match(validator, /allowVideo \? MENU_PRODUCT_MEDIA_TYPES : MENU_IMAGE_TYPES/)
  assert.match(validator, /allowedTypes\.has/)
  assert.match(validator, /MENU_PRODUCT_MEDIA_TYPES/)
  assert.match(validator, /MAX_MENU_MEDIA_BYTES/)
  assert.doesNotMatch(validator, /image\/svg\+xml/)
  assert.match(validator, /return file/)
  assert.match(uploadField, /file: validateMenuImage\(file, true\)/)
  assert.match(uploadField, /accept=\{MENU_PRODUCT_MEDIA_ACCEPT\}/)
  assert.match(uploadField, /multiple/)
  assert.match(uploadField, /className="relative aspect-square overflow-hidden bg-orange-50"/)
  assert.match(uploadField, /containerClassName="h-full w-full"/)
  assert.doesNotMatch(uploadField, /aspect-video/)
  assert.match(uploadField, /controls=\{isMenuVideoUrl\(url\)\}/)
  assert.doesNotMatch(source, /compressMenuImage/)
  assert.doesNotMatch(source, /MENU_IMAGE_TARGET_SIZE/)
  assert.doesNotMatch(source, /MAX_MENU_IMAGE_BYTES/)
  assert.doesNotMatch(source, /canvasToBlob/)
  assert.doesNotMatch(source, /isAlreadyValidMenuWebp/)
})

test('R2 menu image uploads use long-lived immutable browser caching', () => {
  const r2 = readSource('api/menu-image/_lib/r2.js')

  assert.match(r2, /CacheControl: 'public, max-age=31536000, immutable'/)
})

test('R2 menu media uploads verify supported image and video signatures without recompression', () => {
  const r2 = readSource('api/menu-image/_lib/r2.js')
  const upload = readSource('api/menu-image/upload.js')

  assert.match(r2, /ALLOWED_IMAGE_TYPES\.has/)
  assert.match(r2, /ALLOWED_VIDEO_TYPES\.has/)
  assert.match(r2, /matchesImageSignature/)
  assert.match(r2, /matchesVideoSignature/)
  assert.match(r2, /Image contents do not match the declared file type/)
  assert.match(r2, /Video contents do not match the declared file type/)
  assert.doesNotMatch(r2, /image\/svg\+xml/)
  assert.match(r2, /extensionForContentType\(contentType\)/)
  assert.match(upload, /await assertMenuMediaFile\(file, \{ allowVideo: type === 'product' \}\)/)
  assert.match(upload, /contentType: file\.contentType/)
  assert.doesNotMatch(r2, /import sharp from 'sharp'/)
  assert.doesNotMatch(r2, /MENU_IMAGE_TARGET_SIZE/)
  assert.doesNotMatch(r2, /MAX_MENU_IMAGE_BYTES/)
  assert.doesNotMatch(r2, /contentType !== 'image\/webp'/)
  assert.doesNotMatch(r2, /file\.buffer\.length >/)
  assert.doesNotMatch(r2, /metadata\(\)/)
})

test('customer menu surfaces render uploaded video and animated image media safely', () => {
  const menuMedia = readSource('src/components/MenuMedia.jsx')
  const mediaHelpers = readSource('src/lib/menuMedia.js')
  const productCards = readSource('src/components/MenuProductCards.jsx')
  const telegramMenu = readSource('src/pages/TelegramMiniApp.jsx')

  assert.match(mediaHelpers, /MENU_VIDEO_MIME_TYPES/)
  assert.match(mediaHelpers, /video\/mp4/)
  assert.match(mediaHelpers, /video\/webm/)
  assert.match(mediaHelpers, /export function isMenuVideoUrl/)
  assert.match(menuMedia, /if \(!isMenuVideoUrl\(src\)\)/)
  assert.match(menuMedia, /<video/)
  assert.match(menuMedia, /playsInline/)
  assert.match(menuMedia, /controls=\{controls\}/)
  assert.match(menuMedia, /onError=\{\(\) => setVideoFailed\(true\)\}/)
  assert.match(productCards, /controls=\{isMenuVideoUrl\(displayedMediaUrl\)\}/)
  assert.match(productCards, /getMenuItemMediaUrls\(item\)/)
  assert.match(productCards, /setActiveMediaUrl\(url\)/)
  assert.match(productCards, /hasVideo/)
  assert.match(telegramMenu, /<MenuMedia/)
})

test('R2 deletion and upload stay inside flat menu image prefixes', () => {
  const r2 = readSource('api/menu-image/_lib/r2.js')

  assert.match(r2, /MENU_OBJECT_KEY_PATTERN/)
  assert.match(r2, /normalizeMenuObjectKey\(key\)/)
  assert.match(r2, /return normalizeMenuObjectKey\(value\)/)
  assert.match(r2, /return normalizeMenuObjectKey\(url\.pathname\.slice\(basePath\.length\)\)/)
})

test('AdminMenu cleans up replaced or cancelled uploaded menu images', () => {
  const source = readSource('src/pages/AdminMenu.jsx')
  const uploadField = functionBody(source, 'ImageUploadField')
  const galleryField = functionBody(source, 'MediaGalleryField')
  const adminMenu = functionBody(source, 'AdminMenu')

  assert.match(uploadField, /const previousUrl = value/)
  assert.match(uploadField, /onUploadComplete\?\.\(\{ newUrl: data\.url, previousUrl \}\)/)
  assert.match(galleryField, /onUploadComplete\?\.\(\{ newUrl: data\.url, previousUrl: '' \}\)/)
  assert.match(galleryField, /function removeUrl\(url\)/)
  assert.match(galleryField, /function makeCover\(url\)/)
  assert.match(galleryField, /aria-label=\{`\$\{t\(lang, 'deleteMedia'\)\} \$\{index \+ 1\}`\}/)
  assert.match(adminMenu, /uploadedItemImageUrlsRef = useRef\(new Set\(\)\)/)
  assert.match(adminMenu, /uploadedCatImageUrlsRef = useRef\(new Set\(\)\)/)
  assert.match(adminMenu, /async function cleanupTrackedUploads/)
  assert.match(adminMenu, /async function handleTrackedUpload/)
  assert.match(adminMenu, /cleanupTrackedUploads\(uploadedItemImageUrlsRef, mediaUrls\)/)
  assert.match(adminMenu, /oldMediaUrls[\s\S]*\.filter\(url => !keptMediaUrls\.has\(url\)\)[\s\S]*deleteMenuImageFromR2\(url\)/)
  assert.match(adminMenu, /onClose=\{closeItemModal\}/)
  assert.match(adminMenu, /onClick=\{closeCatModal\}/)
  assert.match(adminMenu, /onUploadComplete=\{upload => handleTrackedUpload\(uploadedItemImageUrlsRef, upload\)\}/)
  assert.match(adminMenu, /onUploadComplete=\{upload => handleTrackedUpload\(uploadedCatImageUrlsRef, upload\)\}/)
})

test('menu image optimization script targets real 600px WebP files under 100 KB', () => {
  const pkg = JSON.parse(readSource('package.json'))
  const script = readSource('scripts/optimize-menu-images.js')

  assert.equal(pkg.scripts['optimize:menu-images'], 'node scripts/optimize-menu-images.js')
  assert.match(script, /import sharp from 'sharp'/)
  assert.match(script, /const DEFAULT_TARGET_BYTES = 100 \* 1024/)
  assert.match(script, /const MENU_IMAGE_TARGET_SIZE = 600/)
  assert.match(script, /const targetDimension = MENU_IMAGE_TARGET_SIZE/)
  assert.match(script, /fit: 'cover'/)
  assert.match(script, /position: 'center'/)
  assert.match(script, /width: targetDimension/)
  assert.match(script, /height: targetDimension/)
  assert.match(script, /\.webp\(\{\s*quality,/)
  assert.match(script, /isRealWebp\(image\.buffer\) && image\.buffer\.length <= targetBytes/)
  assert.match(script, /Dimensions: \$\{targetDimension\}x\$\{targetDimension\}px/)
  assert.match(script, /Rerun with --apply to update images/)
})

test('menu image optimization apply mode rejects publishable keys before uploads', () => {
  const script = readSource('scripts/optimize-menu-images.js')

  assert.match(script, /\^sb_publish/i)
  assert.match(script, /Use the private service_role key/)
  assert.match(script, /async function assertApplyCanUpdateRows/)
  assert.match(script, /Apply preflight failed/)
  assert.ok(script.indexOf('if (apply) await assertApplyCanUpdateRows()') < script.indexOf('const totals = {'))
})

test('ImageLoadShimmer shows cached images that loaded before onLoad fires', () => {
  const source = readSource('src/components/ImageLoadShimmer.jsx')

  assert.match(source, /useRef/)
  assert.match(source, /const imageRef = useRef\(null\)/)
  assert.match(source, /image\?\.complete && image\.naturalWidth > 0/)
  assert.match(source, /setLoaded\(true\)/)
  assert.match(source, /ref=\{imageRef\}/)
})

test('AdminMenu item descriptions support multiline text and bold markup', () => {
  const source = readSource('src/pages/AdminMenu.jsx')
  const body = functionBody(source, 'DescriptionField')

  assert.match(source, /Bold/)
  assert.match(body, /<textarea/)
  assert.match(body, /rows=\{4\}/)
  assert.match(body, /\*\*\$\{selected\}\*\*/)
  assert.match(source, /<DescriptionField label=\{t\(lang, 'descUz'\)\}/)
  assert.doesNotMatch(source, /<Field label=\{t\(lang, 'descUz'\)\}/)
})

test('menu product descriptions render new lines and bold safely', () => {
  const source = readSource('src/components/MenuProductCards.jsx')

  assert.match(source, /function FormattedMenuText/)
  assert.match(source, /function FadingMenuDescription/)
  assert.match(source, /WebkitMaskImage/)
  assert.match(source, /maskImage/)
  assert.match(source, /overflow-hidden whitespace-nowrap/)
  assert.match(source, /split\('\\n'\)/)
  assert.match(source, /<strong/)
  assert.match(source, /whitespace-pre-wrap/)
  assert.match(source, /function plainMenuText/)
  assert.doesNotMatch(source, /text-\[#8A94A6\] line-clamp-1/)
  assert.doesNotMatch(source, /text-\[#9CA3AF\] line-clamp-1/)
})

test('AdminMenu sortable item card does not reference upload error state', () => {
  const source = readSource('src/pages/AdminMenu.jsx')
  const body = functionBody(source, 'SortableItemCard')

  assert.doesNotMatch(body, /\berror\b/)
})

test('AdminMenu has one upload error render per media field', () => {
  const source = readSource('src/pages/AdminMenu.jsx')
  const matches = source.match(/\{error && <p/g) || []

  assert.equal(matches.length, 2)
})

test('AdminMenu preserves menu scroll when returning from product editor', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const appShell = readSource('src/components/AppShell.jsx')
  const openEditItem = functionBody(adminMenu, 'openEditItem')
  const openNewItem = functionBody(adminMenu, 'openNewItem')

  assert.match(appShell, /function AppShell\(\{ children, title, contentRef \}\)/)
  assert.match(appShell, /<main ref=\{contentRef\}/)
  assert.match(adminMenu, /const ADMIN_MENU_SCROLL_KEY = 'zar-admin-menu-scroll-top'/)
  assert.match(adminMenu, /const shellScrollRef = useRef\(null\)/)
  assert.match(adminMenu, /saveAdminMenuScrollPosition\(shellScrollRef\.current\?\.scrollTop \|\| 0\)/)
  assert.match(openEditItem, /saveMenuListScrollBeforeProductNavigation\(\)[\s\S]*navigate\(`\/admin\/menu\/product\/\$\{encodeURIComponent\(i\.id\)\}`\)/)
  assert.match(openNewItem, /saveMenuListScrollBeforeProductNavigation\(\)[\s\S]*navigate\('\/admin\/menu\/product\/new'\)/)
  assert.match(adminMenu, /takeSavedAdminMenuScrollPosition\(\)/)
  assert.match(adminMenu, /scroller\.scrollTop = savedScrollTop/)
  assert.match(adminMenu, /clearSavedAdminMenuScrollPosition\(\)/)
  assert.match(adminMenu, /window\.requestAnimationFrame\(\(\) => restore\(\)\)/)
  assert.match(adminMenu, /<AppShell title=\{t\(lang, 'menu'\)\} contentRef=\{shellScrollRef\}>/)
})

test('AdminMenu categories use a dedicated responsive editor page', () => {
  const app = readSource('src/App.jsx')
  const adminMenu = readSource('src/pages/AdminMenu.jsx')

  assert.match(app, /path="\/admin\/menu\/category\/:categoryId"/)
  assert.match(adminMenu, /const isCategoryEditorPage = !!categoryId/)
  assert.match(adminMenu, /navigate\('\/admin\/menu\/category\/new'\)/)
  assert.match(adminMenu, /navigate\(`\/admin\/menu\/category\/\$\{encodeURIComponent\(c\.id\)\}`\)/)
  assert.match(adminMenu, /if \(isCategoryEditorPage\) \{[\s\S]*Manage category names, image, and menu visibility/)
  assert.match(adminMenu, /Live preview/)
  assert.match(adminMenu, /Choose where this category appears/)
  assert.match(adminMenu, /disabled=\{!canSaveCatForm\}/)
  assert.match(adminMenu, /navigate\('\/admin\/menu\?tab=categories'\)/)
  assert.doesNotMatch(adminMenu, /\{catModal && \(\s*<Modal/)
})

test('PublicMenu is read-only for QR customers', () => {
  const app = readSource('src/App.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const productCards = readSource('src/components/MenuProductCards.jsx')

  assert.match(app, /path="\/menu"\s+element=\{<PublicMenu \/>\}/)
  assert.match(app, /path="\/premium-menu"\s+element=\{<PublicMenu premium \/>\}/)
  assert.doesNotMatch(app, /PublicMenuRoute/)
  assert.doesNotMatch(publicMenu, /useAuth/)
  assert.doesNotMatch(publicMenu, /LogIn/)
  assert.doesNotMatch(publicMenu, /\/login/)
  assert.match(publicMenu, /readOnly/)
  assert.match(productCards, /readOnly = false/)
  assert.match(productCards, /const inCart = !readOnly && qty > 0/)
  assert.match(productCards, /\{readOnly \? null : inCart \?/)
  assert.match(productCards, /!\s*readOnly && \(/)
})

test('PublicMenu exposes public contact actions', () => {
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const languageSwitcher = readSource('src/components/LanguageSwitcher.jsx')

  assert.match(publicMenu, /const PUBLIC_CONTACTS = \{/)
  assert.match(publicMenu, /https:\/\/t\.me\/zarkebab/)
  assert.match(publicMenu, /tel:\+998905095545/)
  assert.match(publicMenu, /https:\/\/www\.instagram\.com\/zarkebab/)
  assert.match(publicMenu, /aria-label=\{PUBLIC_CONTACTS\.telegram\.label\}/)
  assert.match(publicMenu, /<Send size=\{16\}/)
  assert.match(publicMenu, /<Phone size=\{16\}/)
  assert.match(publicMenu, /<Instagram size=\{16\}/)
  assert.match(publicMenu, /premium \? <LanguageSwitcher value=\{lang\} onChange=\{setPremiumLang\} \/> : <LanguageSwitcher \/>/)
  assert.match(languageSwitcher, /className = ''/)
  assert.match(languageSwitcher, /compact = false/)
  assert.match(languageSwitcher, /\$\{className\}/)
  assert.match(publicMenu, /import \{ ArrowLeft, ChevronDown/)
  assert.match(publicMenu, /<ChevronDown size=\{13\} strokeWidth=\{3\}/)
  assert.match(languageSwitcher, /import \{ ChevronDown \} from 'lucide-react'/)
  assert.match(languageSwitcher, /<ChevronDown size=\{13\} strokeWidth=\{3\}/)
  assert.match(publicMenu, /icon=\{Coins\}/)
  assert.match(publicMenu, /"so'm UZS"/)
  assert.match(publicMenu, /'\$ USD'/)
  assert.match(publicMenu, /'€ EUR'/)
  assert.doesNotMatch(publicMenu, /🇺🇿|🇺🇸|🇪🇺/)
  assert.match(languageSwitcher, /uz: 'UZ'/)
  assert.match(languageSwitcher, /ru: 'RU'/)
  assert.match(languageSwitcher, /en: 'EN'/)
  assert.doesNotMatch(publicMenu, /PUBLIC_CONTACTS\.phone\.label\}<\/span>/)
  assert.match(languageSwitcher, /uz: '🇺🇿'/)
  assert.match(languageSwitcher, /ru: '🇷🇺'/)
  assert.match(languageSwitcher, /en: '🇬🇧'/)
  assert.match(languageSwitcher, /\{LANGUAGE_FLAGS\[l\]\} \{LANGUAGE_LABELS\[l\]\}/)
})

test('public and waiter menu cards stay dense enough for tablet browsing', () => {
  const productCards = readSource('src/components/MenuProductCards.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const waiterOrder = readSource('src/pages/WaiterOrder.jsx')

  assert.match(productCards, /relative aspect-square w-full flex-shrink-0 overflow-hidden bg-orange-50/)
  assert.match(productCards, /group flex h-full flex-col/)
  assert.match(productCards, /showCompactPublicCard \? 'mt-auto mb-0 items-end pt-2'/)
  assert.match(productCards, /pricing\.discounted \? 'text-red-600' : 'text-\[#ff5a00\]'/)
  assert.match(productCards, /showCompactPublicCard \? 'text-\[13px\] sm:text-\[15px\]'/)
  assert.match(productCards, /text-\[11px\] leading-snug text-\[#8A94A6\] sm:min-h-\[16px\] sm:text-\[12px\]/)
  assert.match(productCards, /showCompactPublicCard \? 'text-\[15px\] sm:text-\[19px\]'/)
  assert.match(publicMenu, /grid grid-cols-2 gap-3 sm:gap-4 md:grid-cols-3 xl:grid-cols-4/)
  assert.match(waiterOrder, /density="compact"/)
  assert.doesNotMatch(productCards, /aspect-\[4\/3\]|aspect-\[2\/1\]/)
  assert.doesNotMatch(productCards, /showCompactPublicCard \? 'text-\[#0F1F33\]'/)
})

test('cashier-only menu items are hidden from customer menus but available to cashier quick items', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const waiterOrder = readSource('src/pages/WaiterOrder.jsx')
  const telegram = readSource('src/pages/TelegramMiniApp.jsx')
  const cashierBill = readSource('src/pages/CashierBill.jsx')
  const cashierTables = readSource('src/pages/CashierTables.jsx')
  const menuItems = readSource('src/lib/menuItems.js')
  const publicSql = readSource('supabase/009_guest_public_menu.sql')
  const migration = readSource('supabase/052_cashier_only_menu_items.sql')
  const health = readSource('scripts/check-db-health.js')

  assert.match(menuItems, /function isCashierOnlyItem/)
  assert.match(menuItems, /function isCustomerMenuItem/)
  assert.match(adminMenu, /cashier_only/)
  assert.match(adminMenu, /Hide from public menu/)
  assert.match(adminMenu, /Скрыть из публичного меню/)
  assert.match(adminMenu, /show_in_cashier_quick_items: true/)
  assert.match(adminMenu, /cashier_only: false/)
  assert.match(adminMenu, /filterAvail === 'cashier_only'/)
  assert.match(adminMenu, /value="cashier_only"/)
  assert.match(adminMenu, /Только у кассира/)
  assert.doesNotMatch(adminMenu, /Show only to cashier/)
  assert.doesNotMatch(adminMenu, /Показывать только кассиру/)
  assert.doesNotMatch(adminMenu, /Needs preparation when added/)
  assert.doesNotMatch(adminMenu, /Отправлять на подготовку при добавлении/)
  assert.match(publicMenu, /isCustomerMenuItem\(item, now\)/)
  assert.match(waiterOrder, /isWaiterMenuItem\(item, visibilityNow\)/)
  assert.match(telegram, /isCustomerMenuItem\(item, now\)/)
  assert.match(cashierBill, /filter\(isCashierQuickItem\)/)
  assert.match(cashierTables, /filter\(isCashierQuickItem\)/)
  assert.match(cashierBill, /filter\(isActiveMenuItem\)[\s\S]*filter\(isCashierQuickItem\)/)
  assert.match(cashierTables, /filter\(isActiveMenuItem\)[\s\S]*filter\(isCashierQuickItem\)/)
  assert.match(cashierTables, /ADD_QUICK_ITEM_TO_ORDER/)
  assert.match(cashierTables, /onAddQuickItem/)
  assert.match(publicSql, /coalesce\(i\.cashier_only, false\) = false/)
  assert.match(migration, /add column if not exists cashier_only/)
  assert.match(migration, /Public: read available menu items/)
  assert.match(migration, /coalesce\(i\.cashier_only, false\) = false/)
  assert.match(health, /cashier_only/)
})

test('public-hidden menu items stay available to waiter table ordering', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const waiterOrder = readSource('src/pages/WaiterOrder.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const telegram = readSource('src/pages/TelegramMiniApp.jsx')
  const menuItems = readSource('src/lib/menuItems.js')
  const migration = readSource('supabase/079_menu_item_public_hidden.sql')
  const health = readSource('scripts/check-db-health.js')

  assert.match(menuItems, /function isPublicHiddenMenuItem/)
  assert.match(menuItems, /function isWaiterMenuItem/)
  assert.match(menuItems, /function isCustomerMenuItem[\s\S]*!isPublicHiddenMenuItem\(item\)/)
  assert.match(adminMenu, /public_hidden/)
  assert.match(adminMenu, /Hide from public menu/)
  assert.match(adminMenu, /filterAvail === 'public_hidden'/)
  assert.match(waiterOrder, /isWaiterMenuItem\(item, visibilityNow\)/)
  assert.doesNotMatch(waiterOrder, /isCustomerMenuItem\(item\)/)
  assert.match(publicMenu, /isCustomerMenuItem\(item, now\)/)
  assert.match(telegram, /isCustomerMenuItem\(item, now\)/)
  assert.match(migration, /add column if not exists public_hidden boolean not null default false/)
  assert.match(migration, /coalesce\(i\.public_hidden, false\) = false/)
  assert.match(health, /public_hidden/)
})

test('hidden menu categories are hidden from customer-facing menus only', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const waiterOrder = readSource('src/pages/WaiterOrder.jsx')
  const telegram = readSource('src/pages/TelegramMiniApp.jsx')
  const menuItems = readSource('src/lib/menuItems.js')
  const schema = readSource('supabase/003_pos_schema.sql')
  const migration = readSource('supabase/053_hidden_menu_categories.sql')
  const health = readSource('scripts/check-db-health.js')

  assert.match(menuItems, /function isHiddenMenuCategory/)
  assert.match(menuItems, /function isCustomerMenuCategory/)
  assert.match(adminMenu, /checked=\{publicVisible\}/)
  assert.match(adminMenu, /hidden: !event\.target\.checked/)
  assert.match(adminMenu, /checked=\{waiterVisible\}/)
  assert.match(adminMenu, /waiter_hidden: !event\.target\.checked/)
  assert.match(adminMenu, /Waiter menu/)
  assert.match(adminMenu, /Hidden from public menu/)
  assert.match(adminMenu, /cat\.hidden \? 'bg-red-50 text-red-500'/)
  assert.match(publicMenu, /isCustomerMenuCategory\(category, now\)/)
  assert.match(publicMenu, /categoryIds\.has\(item\.category_id\)/)
  assert.match(menuItems, /function isWaiterHiddenMenuCategory/)
  assert.match(menuItems, /function isWaiterMenuCategory/)
  assert.match(waiterOrder, /isWaiterMenuCategory\(category, visibilityNow, staffUserId\)/)
  assert.match(waiterOrder, /visibleCategoryIds\.has\(item\.category_id\)/)
  assert.match(telegram, /isCustomerMenuCategory\(category, now\)/)
  assert.match(migration, /add column if not exists hidden boolean not null default false/)
  assert.match(migration, /coalesce\(c\.hidden, false\) = false/)
  assert.match(migration, /exists \([\s\S]*from public\.menu_categories c[\s\S]*c\.id = menu_items\.category_id/)
  assert.match(schema, /hidden\s+boolean\s+not null default false/)
  assert.match(schema, /waiter_hidden\s+boolean\s+not null default false/)
  assert.match(health, /menu_categories', 'id, name_uz, name_ru, name_en, hidden, waiter_hidden, tourist_hidden, visible_from_time, visible_until_time, sort_order, deleted_at'/)
})

test('waiter-hidden menu categories are hidden from waiter table ordering only', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const waiterOrder = readSource('src/pages/WaiterOrder.jsx')
  const telegram = readSource('src/pages/TelegramMiniApp.jsx')
  const menuItems = readSource('src/lib/menuItems.js')
  const migration = readSource('supabase/080_menu_category_waiter_hidden.sql')
  const health = readSource('scripts/check-db-health.js')

  assert.match(menuItems, /function isWaiterHiddenMenuCategory/)
  assert.match(menuItems, /function isWaiterMenuCategory/)
  assert.match(adminMenu, /waiter_hidden/)
  assert.match(adminMenu, /checked=\{waiterVisible\}/)
  assert.match(adminMenu, /waiter_hidden: !event\.target\.checked/)
  assert.match(adminMenu, /Waiter menu/)
  assert.match(adminMenu, /Hidden from waiter menu/)
  assert.match(waiterOrder, /isWaiterMenuCategory/)
  assert.match(waiterOrder, /isWaiterMenuCategory\(category, visibilityNow, staffUserId\)/)
  assert.match(publicMenu, /isCustomerMenuCategory\(category, now\)/)
  assert.match(telegram, /isCustomerMenuCategory\(category, now\)/)
  assert.match(migration, /add column if not exists waiter_hidden boolean not null default false/)
  assert.match(health, /waiter_hidden/)
})

test('selected categories can be hidden only from Tourist-priced menus', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const waiterOrder = readSource('src/pages/WaiterOrder.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const guestCart = readSource('src/lib/guestCart.js')
  const menuItems = readSource('src/lib/menuItems.js')
  const schema = readSource('supabase/003_pos_schema.sql')
  const migration = readSource('supabase/133_menu_category_tourist_visibility.sql')
  const health = readSource('src/lib/dbHealth.js')

  assert.match(menuItems, /function isTouristHiddenMenuCategory/)
  assert.match(adminMenu, /tourist_hidden: !event\.target\.checked/)
  assert.match(adminMenu, /Tourist menu/)
  assert.match(waiterOrder, /priceMode !== PRICE_MODE_TOURIST \|\| !isTouristHiddenMenuCategory\(category\)/)
  assert.match(publicMenu, /premium \? categories\.filter\(category => !isTouristHiddenMenuCategory\(category\)\) : categories/)
  assert.match(guestCart, /normalizedPriceMode !== PRICE_MODE_TOURIST \|\| !isTouristHiddenMenuCategory\(category\)/)
  assert.match(schema, /tourist_hidden\s+boolean\s+not null default false/)
  assert.match(migration, /add column if not exists tourist_hidden boolean not null default false/)
  assert.match(health, /tourist_hidden/)
})

test('menu item availability controls waiter visibility without a redundant waiter-hide setting', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const waiterOrder = readSource('src/pages/WaiterOrder.jsx')
  const telegram = readSource('src/pages/TelegramMiniApp.jsx')
  const menuItems = readSource('src/lib/menuItems.js')
  const migration = readSource('supabase/082_menu_visibility_windows.sql')
  const health = readSource('scripts/check-db-health.js')

  assert.match(menuItems, /function isWithinMenuTimeWindow/)
  assert.match(menuItems, /function isWaiterMenuItem[\s\S]*isMenuItemOrderable\(item\)[\s\S]*isWithinMenuTimeWindow\(item, date\)/)
  assert.doesNotMatch(functionBody(menuItems, 'isWaiterMenuItem'), /waiter_hidden|isWaiterHiddenMenuItem/)
  assert.match(menuItems, /function isCustomerMenuItem[\s\S]*isWithinMenuTimeWindow\(item, date\)/)
  assert.match(adminMenu, /visible_from_time/)
  assert.match(adminMenu, /visible_until_time/)
  assert.doesNotMatch(adminMenu, /Hide from waiter menu/)
  assert.doesNotMatch(adminMenu, /filterAvail === 'waiter_hidden'/)
  assert.doesNotMatch(adminMenu, /id="(?:modal-product-)?waiter-hidden"/i)
  assert.match(waiterOrder, /isWaiterMenuItem\(item, visibilityNow\)/)
  assert.match(waiterOrder, /isWaiterMenuCategory\(category, visibilityNow, staffUserId\)/)
  assert.match(publicMenu, /isCustomerMenuItem\(item, now\)/)
  assert.match(publicMenu, /isCustomerMenuCategory\(category, now\)/)
  assert.match(telegram, /isCustomerMenuItem\(item, now\)/)
  assert.match(telegram, /isCustomerMenuCategory\(category, now\)/)
  assert.match(migration, /add column if not exists waiter_hidden boolean not null default false/)
  assert.match(migration, /add column if not exists visible_from_time time/)
  assert.match(migration, /menu_time_window_is_visible/)
  assert.match(migration, /timezone\('Asia\/Tashkent', now\(\)\)::time/)
  assert.match(health, /waiter_hidden, visible_from_time, visible_until_time/)
})

test('selected staff can bypass category schedules only in waiter ordering', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const waiterOrder = readSource('src/pages/WaiterOrder.jsx')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const telegram = readSource('src/pages/TelegramMiniApp.jsx')
  const menuItems = readSource('src/lib/menuItems.js')
  const db = readSource('src/lib/db.js')
  const migration = readSource('supabase/132_menu_category_user_schedule_overrides.sql')
  const health = readSource('scripts/check-db-health.js')

  assert.match(migration, /create table if not exists public\.menu_category_user_schedule_overrides/)
  assert.match(migration, /primary key \(category_id, profile_id\)/)
  assert.match(migration, /viewer\.role::text = 'owner'/)
  assert.match(migration, /actor\.role::text = 'owner'/)
  assert.match(migration, /Only owners can manage category schedule overrides/)
  assert.match(migration, /set_menu_category_user_schedule_overrides/)
  assert.match(db, /menu_category_user_schedule_overrides/)
  assert.match(db, /always_visible_profile_ids/)
  assert.match(adminMenu, /Visible outside schedule/)
  assert.match(adminMenu, /\{isOwner && <div className="rounded-xl border border-blue-200/)
  assert.match(adminMenu, /toggleCategoryScheduleOverride/)
  assert.match(adminMenu, /\.\.\.\(isOwner \? \{[\s\S]*always_visible_profile_ids/)
  assert.match(waiterOrder, /isWaiterMenuCategory\(category, visibilityNow, staffUserId\)/)
  assert.match(menuItems, /hasMenuCategoryScheduleOverride\(category, profileId\)/)
  assert.match(publicMenu, /isCustomerMenuCategory\(category, now\)/)
  assert.match(telegram, /isCustomerMenuCategory\(category, now\)/)
  assert.match(health, /menu_category_user_schedule_overrides/)
})

test('availability affects only waiter visibility while public-hidden remains customer-only', () => {
  const menuItems = readSource('src/lib/menuItems.js')
  const publicMenu = readSource('src/pages/PublicMenu.jsx')
  const telegram = readSource('src/pages/TelegramMiniApp.jsx')
  const productCards = readSource('src/components/MenuProductCards.jsx')
  const waiterOrder = readSource('src/pages/WaiterOrder.jsx')
  const cartPanel = readSource('src/components/CartPanel.jsx')
  const migration = readSource('supabase/118_show_unavailable_menu_items.sql')

  assert.doesNotMatch(functionBody(menuItems, 'isCustomerMenuItem'), /item\?\.available/)
  assert.match(functionBody(menuItems, 'isWaiterMenuItem'), /isMenuItemOrderable\(item\)/)
  assert.match(functionBody(menuItems, 'isMenuItemOrderable'), /item\?\.available === true/)
  assert.doesNotMatch(publicMenu, /\.eq\('available', true\)/)
  assert.doesNotMatch(telegram, /\.eq\('available', true\)/)
  assert.equal((productCards.match(/const unavailable = !readOnly && item\?\.available === false/g) || []).length, 2)
  assert.match(productCards, /grayscale opacity-55/)
  assert.match(productCards, /disabled=\{unavailable\}/)
  assert.doesNotMatch(functionBody(telegram, 'ProductCard'), /item\?\.available|unavailable/)
  assert.match(functionBody(waiterOrder, 'handleAdd'), /item\?\.available === false/)
  assert.match(functionBody(waiterOrder, 'handleIncrement'), /item\?\.available === false/)
  assert.match(functionBody(waiterOrder, 'handleProductDetailAdd'), /item\?\.available === false/)
  assert.match(cartPanel, /const unavailableCartItems = useMemo/)
  assert.match(cartPanel, /disabled=\{isSending \|\| \(!hasPendingSubmission && \(cart\.length === 0 \|\| hasUnavailableCartItems/)
  assert.match(migration, /create policy "Public: read customer menu items"/)
  assert.match(migration, /i\.deleted_at is null/)
  assert.match(migration, /c\.deleted_at is null/)
  assert.doesNotMatch(migration, /\bi\.available\s*=\s*true\b/)
})

test('AdminMenu visibility badges name the affected menu scope', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const itemStatus = functionBody(adminMenu, 'itemVisibilityStatusLabel')
  const categoryStatus = functionBody(adminMenu, 'categoryVisibilityStatusLabel')

  assert.match(adminMenu, /function hiddenFromPublicMenuLabel/)
  assert.match(adminMenu, /Hidden from public menu/)
  assert.match(adminMenu, /Скрыто в публичном меню/)
  assert.match(adminMenu, /Ommaviy menyuda yashirin/)
  assert.match(adminMenu, /function hiddenFromWaiterMenuLabel/)
  assert.match(adminMenu, /Hidden from waiter menu/)
  assert.match(adminMenu, /Скрыто в меню официанта/)
  assert.match(adminMenu, /Ofitsiant menyusida yashirin/)
  assert.match(itemStatus, /Unavailable/)
  assert.doesNotMatch(itemStatus, /'Hidden'/)
  assert.match(categoryStatus, /hiddenFromPublicMenuLabel\(lang\)/)
  assert.match(adminMenu, /cat\.hidden[\s\S]*hiddenFromPublicMenuLabel\(lang\)/)
  assert.match(adminMenu, /cat\.waiter_hidden[\s\S]*hiddenFromWaiterMenuLabel\(lang\)/)
  assert.doesNotMatch(adminMenu, /'Public hidden'/)
  assert.doesNotMatch(adminMenu, /'Waiter hidden'/)
})

test('AdminMenu read-only category rows keep their columns aligned', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const categoryRow = functionBody(adminMenu, 'SortableCatRow')

  assert.match(adminMenu, /const CAT_EDIT_GRID =/)
  assert.match(adminMenu, /const CAT_READ_ONLY_GRID =/)
  assert.match(categoryRow, /readOnly \? CAT_READ_ONLY_GRID : CAT_EDIT_GRID/)
  assert.match(adminMenu, /canEditMenu \? CAT_EDIT_GRID : CAT_READ_ONLY_GRID/)
  assert.match(categoryRow, /\{!readOnly && \(\s*<div className="flex gap-1\.5 justify-end">/)
  assert.doesNotMatch(categoryRow, /text-gray-300">—/)
})

test('AdminMenu visibility toggles show scoped loading feedback', () => {
  const source = readSource('src/pages/AdminMenu.jsx')
  const toggleButton = functionBody(source, 'VisibilityToggleButton')
  const adminMenu = functionBody(source, 'AdminMenu')

  assert.match(source, /Eye, EyeOff/)
  assert.match(toggleButton, /const Icon = visible \? EyeOff : Eye/)
  assert.match(toggleButton, /disabled=\{pending\}/)
  assert.match(toggleButton, /pending \? <Loader2 size=\{14\} className="animate-spin" \/> : <Icon size=\{14\} \/>/)
  assert.match(adminMenu, /const \[savingItemId, setSavingItemId\] = useState\(''\)/)
  assert.match(adminMenu, /const \[savingCatId, setSavingCatId\] = useState\(''\)/)
  assert.match(adminMenu, /async function toggleItemVisibility\(item\)/)
  assert.match(adminMenu, /async function toggleCategoryVisibility\(cat\)/)
  assert.match(source, /visibilityPending=\{savingItemId === item\.id\}/)
  assert.match(source, /visibilityPending=\{savingCatId === cat\.id\}/)
  assert.match(adminMenu, /return \(matchAvail \|\| savingItemId === item\.id\) && matchSearch/)
  assert.match(source, /closeDisabled=\{savingItemForm\}/)
  assert.match(source, /onClick=\{closeCatModal\}[\s\S]*disabled=\{savingCatForm\}/)
})

test('meal availability changes require Manage Menu access in the UI and database', () => {
  const source = readSource('src/pages/AdminMenu.jsx')
  const permissions = readSource('src/lib/permissions.js')
  const db = readSource('src/lib/db.js')
  const migration = readSource('supabase/122_menu_item_availability_manage_menu_access.sql')
  const adminMenu = functionBody(source, 'AdminMenu')
  const ownerOnlyField = functionBody(source, 'OwnerOnlyMenuItemCheckbox')
  const itemCard = functionBody(source, 'SortableItemCard')
  const itemRow = functionBody(source, 'SortableItemRow')
  const deleteMenuItem = db.slice(
    db.indexOf("case 'DELETE_MENU_ITEM'"),
    db.indexOf("case 'REORDER_MENU_ITEM'")
  )
  const primaryArchivePayload = deleteMenuItem.slice(
    deleteMenuItem.indexOf('const payload = {'),
    deleteMenuItem.indexOf("const { error }")
  )

  assert.match(permissions, /function canChangeMenuItemAvailability\(profileOrRole\)/)
  assert.match(permissions, /function canChangeMenuItemAvailability\(profileOrRole\)\s*\{\s*return canEditMenu\(profileOrRole\)/)
  assert.match(source, /const canChangeAvailability = canChangeMenuItemAvailability\(profile \|\| \{ role: state\.user\?\.role \}\)/)
  assert.match(ownerOnlyField, /disabled=\{disabled \|\| locked\}/)
  assert.match(ownerOnlyField, /\{ownerOnlyBadgeLabel\(lang\)\}/)
  assert.match(itemCard, /canChangeAvailability \? \(\s*<VisibilityToggleButton/)
  assert.match(itemRow, /canChangeAvailability \? \(\s*<VisibilityToggleButton/)
  assert.equal((source.match(/canChange=\{canChangeAvailability\}/g) || []).length, 2)
  assert.match(adminMenu, /const savedAvailability = canChangeAvailability[\s\S]*existingItem \? existingItem\.available !== false : true/)
  assert.match(adminMenu, /available: savedAvailability/)
  assert.match(adminMenu, /async function toggleItemVisibility\(item\) \{\s*if \(!canChangeAvailability/)

  assert.match(primaryArchivePayload, /deleted_at: deletedAt/)
  assert.doesNotMatch(primaryArchivePayload, /available:/)
  assert.match(migration, /auth\.uid\(\) is null/)
  assert.match(migration, /current_staff_can_write\('menu'\)/)
  assert.doesNotMatch(migration, /is_owner\(\)/)
  assert.match(migration, /using errcode = '42501'/)
})

test('public menu hiding is owner-only in the product editor and database', () => {
  const source = readSource('src/pages/AdminMenu.jsx')
  const permissions = readSource('src/lib/permissions.js')
  const migration = readSource('supabase/121_owner_only_menu_item_public_visibility.sql')
  const adminMenu = functionBody(source, 'AdminMenu')
  const ownerOnlyField = functionBody(source, 'OwnerOnlyMenuItemCheckbox')

  assert.match(permissions, /function canChangeMenuItemPublicVisibility\(profileOrRole\)/)
  assert.match(source, /const canChangePublicVisibility = canChangeMenuItemPublicVisibility\(profile \|\| \{ role: state\.user\?\.role \}\)/)
  assert.match(ownerOnlyField, /disabled=\{disabled \|\| locked\}/)
  assert.equal((source.match(/canChange=\{canChangePublicVisibility\}/g) || []).length, 2)
  assert.match(source, /id="product-public-hidden"/)
  assert.match(source, /id="modal-product-public-hidden"/)
  assert.match(adminMenu, /const savedPublicHidden = canChangePublicVisibility[\s\S]*existingItem \? isPublicHiddenMenuItem\(existingItem\) : false/)
  assert.match(adminMenu, /public_hidden: savedPublicHidden/)
  assert.doesNotMatch(adminMenu, /public_hidden: !!form\.public_hidden/)

  assert.match(migration, /auth\.uid\(\) is null/)
  assert.match(migration, /new\.public_hidden is distinct from false and not public\.is_owner\(\)/)
  assert.match(migration, /old\.public_hidden is distinct from new\.public_hidden and not public\.is_owner\(\)/)
  assert.match(migration, /before update of public_hidden on public\.menu_items/)
  assert.match(migration, /when \(old\.public_hidden is distinct from new\.public_hidden\)/)
  assert.match(migration, /using errcode = '42501'/)
})

test('menu catalog archival is owner-only in the UI and database', () => {
  const source = readSource('src/pages/AdminMenu.jsx')
  const permissions = readSource('src/lib/permissions.js')
  const migration = readSource('supabase/167_owner_only_menu_catalog_archival.sql')
  const adminMenu = functionBody(source, 'AdminMenu')
  const itemCard = functionBody(source, 'SortableItemCard')
  const itemRow = functionBody(source, 'SortableItemRow')
  const categoryRow = functionBody(source, 'SortableCatRow')

  assert.match(permissions, /function canDeleteMenuCatalog\(profileOrRole\)[\s\S]*normalizeRole\(profileOrRole\?\.role \|\| profileOrRole\) === 'owner'[\s\S]*canEditMenu\(profileOrRole\)/)
  assert.match(source, /canDeleteMenuCatalog as canDeleteMenuCatalogForProfile/)
  assert.match(adminMenu, /const canDeleteMenuCatalog = canDeleteMenuCatalogForProfile\(profile \|\| \{ role: state\.user\?\.role \}\)/)
  assert.equal((source.match(/canDelete=\{canDeleteMenuCatalog\}/g) || []).length, 8)
  assert.match(itemCard, /\{canDelete && \([\s\S]*onClick=\{\(\) => onDelete\(item\)\}/)
  assert.match(itemRow, /\{canDelete && \([\s\S]*onClick=\{\(\) => onDelete\(item\)\}/)
  assert.match(categoryRow, /\{canDelete && \([\s\S]*onClick=\{\(\) => onDelete\(cat\.id\)\}/)
  assert.match(functionBody(source, 'deleteItem'), /if \(!canDeleteMenuCatalog \|\| savingItemId\) return/)
  assert.match(functionBody(source, 'requestDeleteItem'), /if \(!canDeleteMenuCatalog \|\| savingItemId \|\| !item\?\.id\) return/)
  assert.match(functionBody(source, 'deleteCat'), /if \(!canDeleteMenuCatalog\) return/)
  assert.match(source, /\{canDeleteMenuCatalog && deleteItemCandidate && \(/)

  assert.match(migration, /security definer/)
  assert.match(migration, /auth\.uid\(\) is null/)
  assert.match(migration, /new\.deleted_at is not null and not public\.is_owner\(\)/)
  assert.match(migration, /old\.deleted_at is distinct from new\.deleted_at and not public\.is_owner\(\)/)
  assert.match(migration, /using errcode = '42501'/)
  assert.match(migration, /before insert on public\.menu_items/)
  assert.match(migration, /before insert on public\.menu_categories/)
  assert.match(migration, /before update of deleted_at on public\.menu_items/)
  assert.match(migration, /before update of deleted_at on public\.menu_categories/)
  assert.equal((migration.match(/when \(old\.deleted_at is distinct from new\.deleted_at\)/g) || []).length, 2)
  assert.doesNotMatch(migration, /(?:create|drop) policy/)
})

test('AdminMenu edit save stays disabled until product fields change', () => {
  const source = readSource('src/pages/AdminMenu.jsx')
  const adminMenu = functionBody(source, 'AdminMenu')

  assert.match(source, /function getItemFormFingerprint\(form = \{\}\)/)
  assert.match(adminMenu, /const \[originalItemFormFingerprint, setOriginalItemFormFingerprint\] = useState\(''\)/)
  assert.match(adminMenu, /currentItemFormFingerprint !== originalItemFormFingerprint/)
  assert.match(adminMenu, /const canSaveItemForm = !savingItemForm[\s\S]*&& isItemFormDirty/)
  assert.match(adminMenu, /if \(savingItemForm \|\| !canEditMenu \|\| !isItemFormDirty\) return/)
  assert.match(source, /disabled=\{!canSaveItemForm\}/)
  assert.match(source, /disabled:bg-gray-300 disabled:text-gray-500/)
})

test('menu management uses one logical feature access without a duplicate edit toggle', () => {
  const permissions = readSource('src/lib/permissions.js')
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const team = readSource('src/pages/AdminUsers.jsx')
  const imageAuth = readSource('api/menu-image/_lib/auth.js')
  const imageUpload = readSource('api/menu-image/upload.js')
  const imageDelete = readSource('api/menu-image/delete.js')
  const logicalMigration = readSource('supabase/092_logical_feature_access.sql')
  const readOnlyMenuMigration = readSource('supabase/095_read_only_menu_catalog_access.sql')

  assert.doesNotMatch(permissions, /key: 'edit_menu_items'/)
  assert.match(permissions, /key: 'menu',[\s\S]*kind: 'action'/)
  assert.match(permissions, /if \(page === 'menu'\) return EDITOR_ROLES\.includes\(role\) \|\| role === 'viewer'/)
  assert.match(permissions, /function canEditMenu[\s\S]*canEditFeature\(profileOrRole, 'menu'\)/)
  assert.match(permissions, /function canEditFeature[\s\S]*featureAccessForProfile\(profileOrRole\)\.includes\(featureKey\)/)
  assert.match(permissions, /function updateFeatureAccessSelection/)
  assert.match(adminMenu, /canEditMenu as canEditMenuForProfile/)
  assert.match(adminMenu, /const canEditMenu = canEditMenuForProfile\(profile \|\| \{ role: state\.user\?\.role \}\)/)
  assert.match(team, /feature\.kind === 'page'/)
  assert.match(team, /feature\.kind !== 'action'/)
  assert.match(team, /updateFeatureAccessSelection\(currentAccess, featureKey, enabled\)/)
  assert.match(team, /\{l\.pageAccess\}/)
  assert.match(team, /\{l\.extraActions\}/)
  assert.match(team, /if \(!\['owner', 'admin'\]\.includes\(user\.role\)\) return false/)
  assert.match(imageAuth, /function requireMenuEditAccess/)
  assert.match(imageAuth, /ALLOWED_ROLES\.has\(profile\?\.role\) && access\?\.includes\('menu'\)/)
  assert.doesNotMatch(functionBody(imageAuth, 'requireMenuEditAccess'), /hasLegacyMenuWrite/)
  assert.match(imageUpload, /requireMenuEditAccess\(req\)/)
  assert.match(imageDelete, /requireMenuEditAccess\(req\)/)
  assert.match(readOnlyMenuMigration, /profile\.role in \('owner', 'admin', 'viewer'\)/)
  assert.match(readOnlyMenuMigration, /feature_access_read_menu_items/)
  assert.doesNotMatch(readOnlyMenuMigration, /feature_access_write_menu/)
  assert.match(logicalMigration, /array_append\(feature_access, 'menu'\)/)
  assert.match(logicalMigration, /array_remove\(feature_access, 'edit_menu_items'\)/)
  assert.match(logicalMigration, /when 'move_back_to_table' then 'cashier' = any\(profile\.feature_access\)/)
  assert.match(logicalMigration, /when 'delete_paid_orders' then profile\.feature_access && array\['dashboard','cashier','reports'\]/)
  assert.match(logicalMigration, /not \('move_back_to_table' = any\(feature_access\)\)[\s\S]*'cashier' = any\(feature_access\)/)
  assert.match(logicalMigration, /not \('delete_paid_orders' = any\(feature_access\)\)[\s\S]*feature_access && array\['dashboard','cashier','reports'\]/)
  assert.match(logicalMigration, /current_staff_can_write\('menu'\)/)
  assert.match(logicalMigration, /feature_key in \('move_back_to_table', 'delete_paid_orders'\)[\s\S]*profile\.role not in \('owner', 'admin'\)/)
  assert.match(logicalMigration, /drop policy if exists staff_all_orders on public\.orders/)
  assert.match(logicalMigration, /drop policy if exists staff_all_order_items on public\.order_items/)
  assert.match(logicalMigration, /public\.recall_table_from_cashier\(p_table_id text\)/)
  assert.match(readSource('src/lib/dbHealth.js'), /recall_table_from_cashier/)
  assert.match(readSource('scripts/check-db-health.js'), /recall_table_from_cashier/)
})

test('menu and category writes surface Supabase errors', () => {
  const db = readSource('src/lib/db.js')
  const atomicMenuCreation = readSource('supabase/102_atomic_menu_item_cost_creation.sql')
  const mediaGalleryMigration = readSource('supabase/103_menu_item_media_gallery.sql')

  assert.match(db, /case 'ADD_MENU_ITEM': \{[\s\S]*getRequiredMenuItemCost\(costPrice \?\? _costPriceAlias\)/)
  assert.match(db, /case 'ADD_MENU_ITEM': \{[\s\S]*supabase\.rpc\('create_menu_item_with_media_and_cost'/)
  assert.match(db, /case 'ADD_MENU_ITEM': \{[\s\S]*Database migration 103 is required before creating menu products with media\./)
  assert.doesNotMatch(db, /case 'ADD_MENU_ITEM': \{[\s\S]*supabase\.from\('menu_items'\)\.insert\(fields\)/)
  assert.match(db, /case 'UPDATE_MENU_ITEM': \{[\s\S]*const \{ error \} = await supabase\.from\('menu_items'\)\.update\(normalizedFields\)\.eq\('id', id\)[\s\S]*if \(error\) throw error/)
  assert.match(db, /case 'UPDATE_MENU_ITEM': \{[\s\S]*\.from\('menu_item_costs'\)\.upsert\([\s\S]*if \(costError\) throw costError/)
  assert.match(atomicMenuCreation, /create or replace function public\.create_menu_item_with_cost\(payload jsonb\)/)
  assert.match(atomicMenuCreation, /real_cost <= 0/)
  assert.match(atomicMenuCreation, /insert into public\.menu_items[\s\S]*insert into public\.menu_item_costs/)
  assert.match(atomicMenuCreation, /drop policy if exists "feature_access_write_menu_items"/)
  assert.doesNotMatch(atomicMenuCreation, /create policy "feature_access_insert_menu_items"/)
  assert.match(mediaGalleryMigration, /add column if not exists media_urls text\[\]/)
  assert.match(mediaGalleryMigration, /create or replace function public\.create_menu_item_with_media_and_cost\(payload jsonb\)/)
  assert.match(mediaGalleryMigration, /public\.create_menu_item_with_cost\(/)
  assert.match(mediaGalleryMigration, /image_url = coalesce\(normalized_media_urls\[1\], ''\)/)
  assert.match(mediaGalleryMigration, /media_urls = normalized_media_urls/)
  assert.match(db, /case 'ADD_CATEGORY': \{[\s\S]*const \{ error \} = await supabase\.from\('menu_categories'\)\.insert\(categoryFields\)[\s\S]*if \(error\) throw error/)
  assert.match(db, /case 'ADD_CATEGORY': \{[\s\S]*set_menu_category_user_schedule_overrides[\s\S]*if \(overrideError\) throw overrideError/)
  assert.match(db, /case 'ADD_CATEGORY': \{[\s\S]*if \(hasScheduleOverrides\) \{[\s\S]*set_menu_category_user_schedule_overrides/)
  assert.match(db, /case 'UPDATE_CATEGORY': \{[\s\S]*const \{ error \} = await supabase\.from\('menu_categories'\)\.update\(fields\)\.eq\('id', id\)[\s\S]*if \(error\) throw error/)
  assert.match(db, /case 'UPDATE_CATEGORY': \{[\s\S]*set_menu_category_user_schedule_overrides[\s\S]*if \(overrideError\) throw overrideError/)
  assert.match(db, /case 'UPDATE_CATEGORY': \{[\s\S]*if \(hasScheduleOverrides\) \{[\s\S]*set_menu_category_user_schedule_overrides/)
  assert.match(db, /const results = await Promise\.all\(updates\.map\(update =>[\s\S]*supabase\.from\('menu_items'\)\.update\(\{ sort_order:[\s\S]*const error = results\.find\(result => result\.error\)\?\.error[\s\S]*if \(error\) throw error/)
  assert.match(db, /const results = await Promise\.all\(updates\.map\(update =>[\s\S]*supabase\.from\('menu_categories'\)\.update\(\{ sort_order:[\s\S]*const error = results\.find\(result => result\.error\)\?\.error[\s\S]*if \(error\) throw error/)
})

test('menu item titles and descriptions are trimmed in the editor, app writes, and database', () => {
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const db = readSource('src/lib/db.js')
  const i18n = readSource('src/lib/i18n.js')
  const migration = readSource('supabase/104_trim_menu_item_text.sql')

  assert.match(adminMenu, /function trimF\(key\)/)
  assert.match(adminMenu, /onBlur=\{trimF\('name_uz'\)\}/)
  assert.match(adminMenu, /onBlur=\{trimF\('description_uz'\)\}/)
  assert.match(db, /const normalizedFields = trimMenuItemTextFields\(fields\)/)
  assert.match(db, /create_menu_item_with_media_and_cost[\s\S]*\.\.\.normalizedFields/)
  assert.match(db, /\.from\('menu_items'\)\.update\(normalizedFields\)/)
  assert.match(i18n, /firstMenuItemText\(item\?\.\[`name_\$\{lang\}`\]/)
  assert.match(i18n, /firstMenuItemText\([\s\S]*item\?\.\[`description_\$\{lang\}`\]/)
  assert.match(migration, /create or replace function public\.trim_menu_item_text_columns\(\)/)
  assert.match(migration, /before insert or update of[\s\S]*name_uz[\s\S]*description_en/)
  assert.match(migration, /create trigger trg_trim_menu_item_text/)
  assert.match(migration, /update public\.menu_items/)
})

test('menu item deletion is soft-delete only so history analytics keep lookup context', () => {
  const db = readSource('src/lib/db.js')
  const menuReducer = readSource('src/store/menuReducer.js')
  const appContext = readSource('src/store/AppContext.jsx')
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const cartPanel = readSource('src/components/CartPanel.jsx')
  const menuItems = readSource('src/lib/menuItems.js')
  const migration = readSource('supabase/078_menu_item_safe_delete.sql')
  const health = readSource('scripts/check-db-health.js')
  const archiveCase = db.slice(
    db.indexOf("case 'DELETE_MENU_ITEM':"),
    db.indexOf("case 'REORDER_MENU_ITEM':")
  )
  const itemCard = functionBody(adminMenu, 'SortableItemCard')
  const itemRow = functionBody(adminMenu, 'SortableItemRow')
  const deleteHandler = functionBody(adminMenu, 'deleteItem')

  assert.match(archiveCase, /\.from\('menu_items'\)[\s\S]*\.update\(payload\)[\s\S]*\.eq\('id', action\.payload\)/)
  assert.match(archiveCase, /deleted_at: deletedAt/)
  assert.doesNotMatch(archiveCase, /\.delete\(\)/)
  assert.match(archiveCase, /\.select\('id, deleted_at'\)/)
  assert.match(archiveCase, /if \(!data\?\.length\) throw new Error/)
  assert.doesNotMatch(archiveCase, /update\(\{ available: false/)
  assert.match(menuReducer, /case 'DELETE_MENU_ITEM': \{[\s\S]*available: false,[\s\S]*deleted_at: deletedAt/)
  assert.match(appContext, /'DELETE_MENU_ITEM'/)
  assert.match(adminMenu, /filter\(isActiveMenuItem\)/)
  assert.match(adminMenu, /const \[deleteItemCandidate, setDeleteItemCandidate\] = useState\(null\)/)
  assert.match(adminMenu, /role="dialog"[\s\S]*aria-modal="true"[\s\S]*aria-busy=/)
  assert.match(adminMenu, /role="alert"[\s\S]*\{deleteItemError\}/)
  assert.match(adminMenu, /max-h-\[calc\(100dvh-2rem\)\][\s\S]*overflow-y-auto/)
  assert.match(adminMenu, /document\.body\.style\.overflow = 'hidden'/)
  assert.match(adminMenu, /onKeyDown=\{handleDeleteDialogKeyDown\}/)
  assert.match(itemCard, /onPointerDown=\{event => event\.stopPropagation\(\)\}/)
  assert.match(itemCard, /onClick=\{\(\) => onDelete\(item\)\}/)
  assert.match(itemCard, /touch-manipulation flex h-11 w-11/)
  assert.match(itemRow, /sm:flex-nowrap/)
  assert.match(itemRow, /onPointerDown=\{event => event\.stopPropagation\(\)\}/)
  assert.match(itemRow, /onClick=\{\(\) => onDelete\(item\)\}/)
  assert.match(itemRow, /touch-manipulation flex h-11 w-11/)
  assert.match(functionBody(adminMenu, 'requestDeleteItem'), /setDeleteItemCandidate\(item\)/)
  assert.match(deleteHandler, /dispatch\(\{ type: 'DELETE_MENU_ITEM', payload: id \}\)/)
  assert.match(deleteHandler, /setDeleteItemError\(message\)/)
  assert.match(deleteHandler, /setDeleteItemCandidate\(null\)/)
  assert.doesNotMatch(deleteHandler, /window\.confirm/)
  assert.match(cartPanel, /import \{ isMenuItemOrderable \} from '\.\.\/lib\/menuItems'/)
  assert.equal((cartPanel.match(/!isMenuItemOrderable\(menuItem\)/g) || []).length, 2)
  assert.match(menuItems, /function isDeletedMenuItem/)
  assert.match(menuItems, /function isActiveMenuItem/)
  assert.match(migration, /add column if not exists deleted_at timestamptz/)
  assert.match(health, /deleted_at/)
})

test('category deletion archives report context and hard catalog deletes are blocked', () => {
  const db = readSource('src/lib/db.js')
  const menuReducer = readSource('src/store/menuReducer.js')
  const appContext = readSource('src/store/AppContext.jsx')
  const adminMenu = readSource('src/pages/AdminMenu.jsx')
  const menuItems = readSource('src/lib/menuItems.js')
  const migration = readSource('supabase/115_archive_menu_catalog_deletions.sql')

  assert.match(db, /case 'DELETE_CATEGORY': \{[\s\S]*\.from\('menu_categories'\)\.update\(\{[\s\S]*deleted_at: deletedAt/)
  assert.doesNotMatch(db, /case 'DELETE_CATEGORY': \{[\s\S]{0,500}\.delete\(\)/)
  assert.match(menuReducer, /case 'DELETE_CATEGORY': \{[\s\S]*hidden: true,[\s\S]*waiter_hidden: true,[\s\S]*deleted_at: deletedAt/)
  assert.match(appContext, /WRITE_BEFORE_LOCAL_ACTIONS[\s\S]*'DELETE_CATEGORY'/)
  assert.match(adminMenu, /realSortedCats[\s\S]*isActiveMenuCategory\(c\)/)
  assert.match(menuItems, /function isDeletedMenuCategory/)
  assert.match(menuItems, /function isActiveMenuCategory/)
  assert.match(migration, /alter table public\.menu_categories[\s\S]*add column if not exists deleted_at timestamptz/)
  assert.match(migration, /before delete on public\.menu_categories/)
  assert.match(migration, /before delete on public\.menu_items/)
})
