import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { functionBody, readSource, root, sourceFiles } from './helpers/sourceGuard.js'

test('cashier waits for authenticated POS hydration before showing totals', () => {
  const appContext = readSource('src/store/AppContext.jsx')
  const cashierTables = readSource('src/pages/CashierTables.jsx')
  const db = readSource('src/lib/db.js')

  assert.match(appContext, /const \{ loading: authLoading, session \} = useAuth\(\)/)
  assert.match(appContext, /if \(authLoading\) return undefined/)
  assert.match(appContext, /dispatch\(\{ type: 'SET_LOADING' \}\)/)
  assert.match(appContext, /activeSession\?\.user\?\.id !== sessionUserId/)
  assert.match(appContext, /\.catch\(err => \{\s*if \(!mounted\) return\s*console\.error\('\[db\] initial load failed:'/)
  assert.match(cashierTables, /useAppDataStatus\(\)/)
  assert.match(cashierTables, /if \(!loaded \|\| loadError\)/)
  assert.match(cashierTables, /OperationalLoading/)
  assert.match(cashierTables, /OperationalError/)
  assert.doesNotMatch(db, /catch \{\s*return null\s*\}/)
})

test('delete-paid-orders editors can change completed-order payment methods individually', () => {
  const reports = readSource('src/pages/Reports.jsx')
  const permissions = readSource('src/lib/permissions.js')
  const appContext = readSource('src/store/AppContext.jsx')
  const db = readSource('src/lib/db.js')
  const migration = readSource('supabase/090_owner_change_completed_order_payment_method.sql')
  const individualMigration = readSource('supabase/117_owner_change_individual_payment_methods.sql')
  const featureAccessMigration = readSource('supabase/173_paid_order_edit_feature_access.sql')

  assert.match(permissions, /function canChangeCompletedOrderPaymentMethod/)
  assert.match(permissions, /function canChangeCompletedOrderPaymentMethod[\s\S]*canDeletePaidOrders\(profileOrRole\)/)
  assert.match(reports, /Change payment method/)
  assert.match(reports, /Each payment method can be changed separately\. Amounts and loyalty data stay unchanged\./)
  assert.match(reports, /function PaymentMethodBadges/)
  assert.match(reports, /getOrderPaymentBreakdown\(order\)/)
  assert.match(reports, /<PaymentMethodBadges order=\{order\} lang=\{lang\} showAmounts \/>/)
  assert.match(reports, /type: 'CHANGE_PAID_ORDER_PAYMENT_METHODS'/)
  assert.match(reports, /paymentId: payment\.id/)
  assert.match(reports, /payment\.method !== 'loyalty_card'/)
  assert.match(reports, /setHistoryOrders\(current => current\.map\(row =>/)
  assert.doesNotMatch(reports, /Edit completed order/)
  assert.match(appContext, /'CHANGE_PAID_ORDER_PAYMENT_METHOD'/)
  assert.match(appContext, /'CHANGE_PAID_ORDER_PAYMENT_METHODS'/)
  assert.doesNotMatch(appContext, /'REOPEN_PAID_ORDERS'/)
  assert.match(db, /case 'CHANGE_PAID_ORDER_PAYMENT_METHOD':[\s\S]*supabase\.rpc\('change_paid_order_payment_method_owner'/)
  assert.match(db, /case 'CHANGE_PAID_ORDER_PAYMENT_METHODS':[\s\S]*supabase\.rpc\('change_paid_order_payment_methods_owner'/)
  assert.doesNotMatch(db, /case 'REOPEN_PAID_ORDERS'/)
  assert.match(migration, /drop function if exists public\.reopen_paid_orders_owner\(text\[\]\)/)
  assert.match(migration, /Only owner can change a completed order payment method/)
  assert.match(migration, /old\.payment_method is distinct from new\.payment_method[\s\S]*current_staff_has_role\(array\['owner'\]\)/)
  assert.match(migration, /update public\.order_payments\s+set method = normalized_method/)
  assert.match(migration, /and method <> 'loyalty_card'/)
  assert.match(migration, /update public\.orders\s+set payment_method = normalized_method/)
  assert.match(migration, /'payment_method_changed'/)
  assert.match(migration, /grant execute on function public\.change_paid_order_payment_method_owner\(text\[\], text\) to authenticated/)
  assert.doesNotMatch(migration, /set_config\('app\.owner_paid_order_reopen'/)
  assert.doesNotMatch(migration, /delete from public\.(order_payments|loyalty_transactions)/)
  assert.match(individualMigration, /Only owner can change a completed order payment method/)
  assert.match(individualMigration, /method <> 'loyalty_card'/)
  assert.match(individualMigration, /set payment_method = summary_method/)
  assert.match(individualMigration, /when method_count > 1 then 'mixed'/)
  assert.match(individualMigration, /grant execute on function public\.change_paid_order_payment_methods_owner\(jsonb\) to authenticated/)
  assert.doesNotMatch(individualMigration, /delete from public\.(order_payments|loyalty_transactions)/)
  assert.match(featureAccessMigration, /current_staff_can_access\(''delete_paid_orders''\)/)
  assert.match(featureAccessMigration, /guard_and_audit_order_payment\(\)/)
  assert.match(featureAccessMigration, /change_paid_order_payment_method_owner\(text\[\],text\)/)
  assert.match(featureAccessMigration, /change_paid_order_payment_methods_owner\(jsonb\)/)
})

test('completed order payment metadata uses a full-width responsive amount layout', () => {
  const reports = readSource('src/pages/Reports.jsx')
  const metaStart = reports.indexOf('{/* Order meta */}')
  const meta = reports.slice(metaStart, reports.indexOf('{/* Items */}', metaStart))
  const badges = reports.slice(reports.indexOf('function PayBadge'), reports.indexOf('function KpiCard'))

  assert.match(meta, /value: <PaymentMethodBadges order=\{order\} lang=\{lang\} showAmounts \/>, fullWidth: true/)
  assert.match(meta, /\.map\(\(\{ label, value, fullWidth = false \}\) =>/)
  assert.match(meta, /min-w-0 rounded-xl bg-gray-50/)
  assert.match(meta, /fullWidth \? 'col-span-2 p-4' : 'p-3'/)
  assert.match(badges, /showAmounts \? 'flex w-full flex-wrap items-center gap-2'/)
  assert.match(badges, /min-w-\[170px\] flex-1 justify-between/)
  assert.match(badges, /hasAmount && <span className="whitespace-nowrap font-black tabular-nums">\{formatCurrency\(amount\)\}<\/span>/)
})

test('reports use the shared Daily Bazaar range calendar', () => {
  const reports = readSource('src/pages/Reports.jsx')
  const rangePicker = readSource('src/components/DateRangePicker.jsx')

  assert.match(reports, /import DateRangePicker from '\.\.\/components\/DateRangePicker'/)
  assert.match(reports, /<DateRangePicker[\s\S]*rangeKey=\{activeRangeKey\}[\s\S]*onPreset=\{selectQuickRange\}[\s\S]*onApply=\{setCustomRange\}/)
  assert.match(reports, /getAccountingQuickRange\(key, todayStr\(\)\)/)
  assert.match(rangePicker, /role="dialog" aria-label=\{l\.selectDateRange\}/)
  assert.match(rangePicker, /function MonthCalendar/)
  assert.doesNotMatch(reports, /function DateInput/)
})

test('reports closeout localizes labels and date while filter controls stay aligned', () => {
  const reports = readSource('src/pages/Reports.jsx')
  const exportCloseout = functionBody(reports, 'exportCloseout')

  assert.match(reports, /cash: 'Наличные'/)
  assert.match(reports, /<SummaryRow label=\{l\.cash\}/)
  assert.match(reports, /getDailyCloseout\(reportOrders,\s*dateFrom,\s*dateTo,\s*\{/)
  assert.match(reports, /tableId:\s*tableFilter/)
  assert.match(reports, /waiterName:\s*waiterFilter/)
  assert.match(reports, /\[reportOrders,\s*dateFrom,\s*dateTo,\s*tableFilter,\s*waiterFilter\]/)
  assert.doesNotMatch(reports, /getDailyCloseout\(reportOrders,\s*dateTo\)/)
  assert.match(reports, /tableFilter\s+=== 'all' \|\| o\.table_id === tableFilter/)
  assert.match(reports, /waiterFilter === 'all' \|\| o\.waiter_name === waiterFilter/)
  assert.match(reports, /formatLongDate\(closeout\.dateFrom, lang, closeout\.dateFrom\)/)
  assert.match(reports, /formatLongDate\(closeout\.dateTo, lang, closeout\.dateTo\)/)
  assert.match(exportCloseout, /closeout\.dateFrom/)
  assert.match(exportCloseout, /closeout\.dateTo/)
  assert.match(reports, /mt-2 flex flex-wrap items-stretch justify-end gap-2/)
  assert.match(reports, /className="flex h-11 items-center gap-1\.5 px-4/)
  assert.equal((reports.match(/className="h-11 bg-white border/g) || []).length, 2)
})

test('QR is retired from payment, reporting, accounting, dashboard, and receipt surfaces', () => {
  const visibleSurfaces = [
    'src/pages/CashierBill.jsx',
    'src/pages/CashierTables.jsx',
    'src/pages/Reports.jsx',
    'src/pages/AdminDashboard.jsx',
    'src/pages/Expenses.jsx',
    'src/pages/MonthlyEstimate.jsx',
    'src/pages/Receipt.jsx',
  ].map(readSource).join('\n')
  const analytics = readSource('src/lib/analytics.js')
  const closeout = readSource('src/lib/closeout.js')

  assert.doesNotMatch(visibleSurfaces, /QrCode|QR Code|QR Kod|QR Код|QR-код|Instagram QR|api\.qrserver/)
  assert.doesNotMatch(visibleSurfaces, /key: 'qr'|value="qr"/)
  assert.match(analytics, /raw === 'qr'[\s\S]*return 'terminal'/)
  assert.doesNotMatch(closeout, /\['QR'/)
})

test('expenses use the shared Daily Bazaar range calendar while entry dates stay native', () => {
  const expenses = readSource('src/pages/Expenses.jsx')
  const rangePicker = readSource('src/components/DateRangePicker.jsx')
  const dateInput = functionBody(expenses, 'DateInput')

  assert.match(dateInput, /const inputRef = useRef\(null\)/)
  assert.match(dateInput, /onPointerDown=\{openPicker\}/)
  assert.match(dateInput, /input\.showPicker\(\)/)
  assert.match(dateInput, /formatLongDate\(value, lang, value\)/)
  assert.match(dateInput, /type="date"/)
  assert.match(dateInput, /native-date-input/)
  assert.match(dateInput, /left-3 right-9/)
  assert.match(dateInput, /overflow-hidden text-ellipsis whitespace-nowrap/)
  assert.match(expenses, /const DATE_INPUT_CLASS = .*text-transparent caret-transparent/)
  assert.match(expenses, /import DateRangePicker from '\.\.\/components\/DateRangePicker'/)
  assert.match(expenses, /<DateRangePicker[\s\S]*rangeKey=\{activeRangeKey\}[\s\S]*onPreset=\{selectQuickRange\}[\s\S]*onApply=\{setCustomRange\}/)
  assert.match(rangePicker, /role="dialog" aria-label=\{l\.selectDateRange\}/)
  assert.match(rangePicker, /function MonthCalendar/)
  assert.match(rangePicker, /previousCurrentWeek/)
  assert.match(rangePicker, /currentNextWeek/)
})

test('CashierBill uses loyalty wallet controls instead of percent card discounts', () => {
  const source = readSource('src/pages/CashierBill.jsx')
  const payMethodsBlock = source.slice(source.indexOf('const PAY_METHODS = ['), source.indexOf('function payLabel'))

  assert.match(source, /Loyalty Card/)
  assert.match(source, /Cashback balance/)
  assert.match(source, /Loyalty amount to use/)
  assert.match(source, /loyalty_used_amount/)
  assert.match(source, /cashback_earned/)
  assert.match(source, /getMaxLoyaltyRedeemAmount/)
  assert.match(source, /clampMoneyInput/)
  assert.match(source, /getMaxPaymentAmount/)
  assert.match(source, /getLoyaltyCardCashbackPercent\(loyaltyCard\)/)
  assert.match(source, /getLoyaltyCardCashbackType\(loyaltyCard\)/)
  assert.match(source, /function fillMaxLoyaltyRedeem\(\)/)
  assert.match(source, /setLoyaltyRedeemAmount\(String\(clampMoneyInput\(maxLoyaltyRedeemAmount, maxLoyaltyRedeemAmount\)\)\)/)
  assert.match(source, /inputMode="numeric"/)
  assert.match(source, /Tap balance to use max available/)
  assert.match(source, /No loyalty balance available to use/)
  assert.doesNotMatch(source, /LOYALTY_PRESETS/)
  assert.doesNotMatch(source, /setLoyaltyPct/)
  assert.doesNotMatch(source, /loyalty_discount_pct/)
  assert.doesNotMatch(source, /Custom %/)
  assert.doesNotMatch(source, /lbl\.cashbackEarned/)
  assert.doesNotMatch(payMethodsBlock, /loyalty_card/)
  assert.doesNotMatch(payMethodsBlock, /Лояльность/)
})

test('new cashier payments use cash or terminal while historical card reporting stays intact', () => {
  const cashier = readSource('src/pages/CashierBill.jsx')
  const reports = readSource('src/pages/Reports.jsx')
  const expenses = readSource('src/lib/expenses.js')
  const payMethodsBlock = cashier.slice(cashier.indexOf('const PAY_METHODS = ['), cashier.indexOf('function payLabel'))
  const correctionStart = reports.indexOf('{paymentMethodOrderId === order.id ? (')
  const correctionEnd = reports.indexOf('{canDeleteOrder &&', correctionStart)
  const correctionBlock = reports.slice(correctionStart, correctionEnd)

  assert.match(payMethodsBlock, /key: 'cash'/)
  assert.match(payMethodsBlock, /key: 'terminal'/)
  assert.doesNotMatch(payMethodsBlock, /key: 'card'/)
  assert.match(correctionBlock, /row\.method === 'card'/)
  assert.match(correctionBlock, /<option value="card" disabled>/)
  assert.doesNotMatch(correctionBlock, /<option value="card">/)
  assert.match(reports, /card:\s+\{ label:/)
  assert.match(reports, /<option value="card">\{lang === 'uz' \? 'Karta'/)
  assert.match(expenses, /ACCOUNTING_CASHFLOW_METHODS = \['cash', 'card', 'terminal', 'loyalty_card'\]/)
})

test('active cashback calculation uses card type resolver instead of hardcoded default percent', () => {
  const analytics = readSource('src/lib/analytics.js')
  const loyalty = readSource('src/lib/loyalty.js')
  const db = readSource('src/lib/db.js')
  const paymentMigration = readSource('supabase/083_atomic_order_payment_settlement.sql')
  const cashier = readSource('src/pages/CashierBill.jsx')
  const reducer = readSource('src/store/ordersReducer.js')

  assert.match(loyalty, /getLoyaltyCardCashbackType/)
  assert.match(loyalty, /cashbackType/)
  assert.match(db, /settle_orders_payment/)
  assert.match(paymentMigration, /card_type := lower\(coalesce\(card_row\.cashback_type, 'bronze'\)\)/)
  assert.match(paymentMigration, /when 'platinum' then 30/)
  assert.match(paymentMigration, /when 'special' then 40/)
  assert.match(paymentMigration, /for update/)
  assert.match(paymentMigration, /'redeemed', -loyalty_for_order::integer/)
  assert.match(cashier, /getLoyaltyCardCashbackPercent/)
  assert.match(reducer, /getLoyaltyCardCashbackPercent/)
  assert.doesNotMatch(analytics, /calculateLoyaltyCashback\(order, items = getOrderItems\(order\), cashbackPercent = 5\)/)
  assert.doesNotMatch(analytics, /fallbackPct = 5/)
  assert.doesNotMatch(cashier, /state\.settings\?\.cashbackPercent/)
  assert.doesNotMatch(db, /state\.settings\?\.cashbackPercent/)
})

test('CashierBill keeps cashback preview visually after payable totals', () => {
  const source = readSource('src/pages/CashierBill.jsx')
  const mainSummary = source.slice(source.indexOf('Items footer: subtotal strip'), source.indexOf('{/* Loyalty card */}'))
  const paymentSummary = source.slice(source.indexOf('{/* Payment Summary */}'), source.indexOf('{/* Split Payment */}'))
  const loyaltyCard = source.slice(source.indexOf('{/* Loyalty card */}'), source.indexOf('{/* ══ RIGHT: payment panel'))

  assert.ok(mainSummary.indexOf('lbl.totalAmt') < mainSummary.indexOf('lbl.cashbackToBeEarned'))
  assert.ok(paymentSummary.indexOf('lbl.totalAmt') < paymentSummary.indexOf('lbl.cashbackToBeEarned'))
  assert.ok(loyaltyCard.indexOf('lbl.loyalty') < loyaltyCard.indexOf('lbl.cashbackToBeEarned'))
  assert.match(source, /Cashback to be earned/)
  assert.doesNotMatch(source, /Cashback earned/)
})

test('CashierBill keeps counter items in main content above loyalty and out of payment sidebar', () => {
  const source = readSource('src/pages/CashierBill.jsx')
  const orderDetailsEnd = source.indexOf('{/* Counter Items */}')
  const counterStart = source.indexOf('{/* Counter Items */}')
  const loyaltyStart = source.indexOf('{/* Loyalty card */}')
  const paymentPanelStart = source.indexOf('{/* ══ RIGHT: payment panel')
  const splitStart = source.indexOf('{/* Split Payment */}')
  const quickAmountStart = source.indexOf('{lbl.quickAmt}', splitStart)
  const splitPayment = source.slice(splitStart, quickAmountStart)

  assert.ok(orderDetailsEnd > source.indexOf('Items footer: subtotal strip'))
  assert.ok(counterStart < loyaltyStart)
  assert.ok(loyaltyStart < paymentPanelStart)
  assert.match(source, /Add quick cashier items to this bill/)
  assert.match(source, /grid grid-cols-1 gap-2 sm:grid-cols-2 xl:grid-cols-3/)
  assert.doesNotMatch(splitPayment, /quickItems\.length > 0/)
  assert.doesNotMatch(splitPayment, /lbl\.counterItems/)
})

test('loyalty cashback wallet migration and admin route are wired', () => {
  const migration = readSource('supabase/022_loyalty_cashback_wallet.sql')
  const specialCardMigration = readSource('supabase/061_loyalty_special_card.sql')
  const platinumCardMigration = readSource('supabase/065_loyalty_platinum_card.sql')
  const adminCreateMigration = readSource('supabase/041_admin_create_loyalty_cards.sql')
  const deleteTransactionMigration = readSource('supabase/042_delete_loyalty_transaction.sql')
  const removeCardMigration = readSource('supabase/051_remove_loyalty_cards_preserve_history.sql')
  const roleAccessMigration = readSource('supabase/077_four_role_feature_access.sql')
  const app = readSource('src/App.jsx')
  const admin = readSource('src/pages/AdminLoyalty.jsx')
  const loyalty = readSource('src/lib/loyalty.js')
  const db = readSource('src/lib/db.js')
  const paymentMigration = readSource('supabase/083_atomic_order_payment_settlement.sql')

  assert.match(migration, /create table if not exists public\.loyalty_cards/)
  assert.match(migration, /create table if not exists public\.loyalty_transactions/)
  assert.match(migration, /cashback_type/)
  assert.match(migration, /prevent_loyalty_card_type_change/)
  assert.match(migration, /Cashback type cannot be changed after card registration/)
  assert.match(migration, /cashback_percent_used/)
  assert.match(migration, /card_type_at_transaction/)
  assert.match(migration, /special/)
  assert.match(migration, /card_number_at_transaction/)
  assert.match(migration, /on delete set null/)
  assert.match(migration, /owner_create_loyalty_cards/)
  assert.match(adminCreateMigration, /owner_admin_create_loyalty_cards/)
  assert.match(adminCreateMigration, /array\['owner','admin'\]/)
  assert.match(deleteTransactionMigration, /delete_loyalty_transaction/)
  assert.match(deleteTransactionMigration, /current_staff_has_role\(array\['owner'\]\)/)
  assert.match(deleteTransactionMigration, /delete from public\.loyalty_transactions/)
  assert.match(deleteTransactionMigration, /total_redeemed/)
  assert.match(removeCardMigration, /remove_loyalty_card/)
  assert.match(removeCardMigration, /card_number_at_transaction/)
  assert.match(removeCardMigration, /on delete set null/)
  assert.match(removeCardMigration, /delete from public\.loyalty_cards/)
  assert.doesNotMatch(removeCardMigration, /delete from public\.loyalty_transactions/)
  assert.match(roleAccessMigration, /feature_access_create_loyalty_cards/)
  assert.match(roleAccessMigration, /public\.current_staff_can_write\('loyalty'\)/)
  assert.match(roleAccessMigration, /feature_access_update_loyalty_cards/)
  assert.match(roleAccessMigration, /public\.current_staff_can_write\('loyalty'\) or public\.current_staff_can_write\('cashier'\)/)
  assert.match(roleAccessMigration, /feature_access_insert_loyalty_transactions/)
  assert.doesNotMatch(migration, /staff_all_loyalty_cards on public\.loyalty_cards\s+for all/)
  assert.match(migration, /loyalty_used_amount/)
  assert.match(migration, /cashback_earned/)
  assert.match(app, /\/admin\/loyalty/)
  assert.match(app, /\/admin\/discount-cards/)
  assert.match(admin, /Manual balance adjustment/)
  assert.match(admin, /Balance transaction history/)
  assert.match(admin, /canCreateLoyaltyCard/)
  assert.match(admin, /canAdjustLoyaltyBalance/)
  assert.match(admin, /canRemoveLoyaltyCard/)
  assert.match(admin, /canDeleteLoyaltyTransaction/)
  assert.match(admin, /delete_loyalty_transaction/)
  assert.match(admin, /remove_loyalty_card/)
  assert.match(admin, /isMissingLoyaltySchemaColumn/)
  assert.match(admin, /setSupportsCashbackType\(false\)/)
  assert.match(admin, /formatUzPhoneNumberInput/)
  assert.match(admin, /cardFormRequired/)
  assert.match(admin, /replace\(\/\\D\/g, ''\)\.slice\(0, 8\)/)
  assert.match(admin, /Register loyalty card/)
  assert.match(admin, /form\.customer_name/)
  assert.match(admin, /Remove card/)
  assert.doesNotMatch(admin, /Deactivate/)
  assert.doesNotMatch(admin, /function updateCashbackType/)
  assert.match(db, /settle_orders_payment/)
  assert.match(paymentMigration, /card_number_at_transaction/)
  assert.match(paymentMigration, /customer_name_at_transaction/)
  assert.match(paymentMigration, /phone_number_at_transaction/)
  assert.match(loyalty, /bronze: \{ label: 'Bronze', percent: 3 \}/)
  assert.match(loyalty, /black: \{ label: 'Black', percent: 15 \}/)
  assert.match(loyalty, /platinum: \{ label: 'Platinum', percent: 30 \}/)
  assert.match(loyalty, /special: \{ label: 'Special card', percent: 40 \}/)
  assert.match(specialCardMigration, /loyalty_cards_cashback_type_check/)
  assert.match(specialCardMigration, /special/)
  assert.match(platinumCardMigration, /loyalty_cards_cashback_type_check/)
  assert.match(platinumCardMigration, /platinum/)
  assert.match(loyalty, /removeLoyaltyCardRecord/)
  assert.match(loyalty, /deleteLoyaltyTransactionRecord/)
})

test('AdminLoyalty selected card uses compact profile and detailed transaction layout', () => {
  const admin = readSource('src/pages/AdminLoyalty.jsx')

  assert.match(admin, /CARD_PAGE_SIZE = 20/)
  assert.match(admin, /CARD_SELECT_COLUMNS/)
  assert.match(admin, /TRANSACTION_SELECT_COLUMNS/)
  assert.match(admin, /\.range\(from, to\)/)
  assert.match(admin, /setTimeout\(\(\) => \{[\s\S]*searchCards\(query, \{ page: 0 \}\)[\s\S]*250/)
  assert.match(admin, /cardSearchRequestRef/)
  assert.match(admin, /select\(CARD_SELECT_COLUMNS, \{ count: 'exact' \}\)/)
  assert.match(admin, /totalCardPages/)
  assert.match(admin, /visibleCardPages/)
  assert.match(admin, /aria-current=\{page === cardPage \? 'page' : undefined\}/)
  assert.doesNotMatch(admin, /hasMoreCards|l\.loadMore/)
  assert.doesNotMatch(admin, /\.select\('\*'\)/)
  assert.match(admin, /Customer Loyalty Profile/)
  assert.match(admin, /No customer name/)
  assert.match(admin, /No phone number/)
  assert.match(admin, /<AppShell title=\{selected \? l\.detailsTitle : l\.title\}>/)
  assert.match(admin, /selected \? 'hidden lg:block' : ''/)
  assert.match(admin, /selected \? '' : 'hidden lg:block'/)
  assert.match(admin, /setSelected\(null\)/)
  assert.match(admin, /ChevronRight/)
  assert.match(admin, /xl:grid-cols-\[minmax\(320px,430px\)_minmax\(0,1fr\)\]/)
  assert.match(admin, /selectedName\(selected\)/)
  assert.match(admin, /selectedPhone\(selected\)/)
  assert.match(admin, /l\.cardNo/)
  assert.match(admin, /l\.balance/)
  assert.match(admin, /l\.ownerActions/)
  assert.match(admin, /l\.adjustmentHelper/)
  assert.match(admin, /l\.ownerAdjustOnly/)
  assert.match(admin, /l\.ownerTypeOnly/)
  assert.match(admin, /updateCustomerProfile/)
  assert.match(admin, /l\.saveCustomer/)
  assert.match(admin, /transactionAmount\(tx\)/)
  assert.match(admin, /transactionCardType\(tx\)/)
  assert.match(admin, /tx\.balance_before/)
  assert.match(admin, /tx\.balance_after/)
  assert.match(admin, /l\.noTransactions/)
  assert.match(admin, /disabled=\{!canAdjust\}/)
  assert.match(admin, /disabled=\{!canRemoveCard\}/)
  assert.match(admin, /l\.removeCardHelp/)
  const createSection = admin.slice(admin.indexOf('<h2 className="mb-3 text-sm font-black text-[#1F2937]">{l.createTitle}</h2>'), admin.indexOf('<div className="mt-5">'))
  assert.match(createSection, /form\.card_number/)
  assert.match(createSection, /form\.customer_name/)
  assert.match(createSection, /form\.phone_number/)
  assert.match(createSection, /form\.cashback_type/)
  const cashbackSection = admin.slice(admin.indexOf('<p className="text-xs font-black uppercase tracking-widest text-[#9CA3AF]">{l.cashbackType}</p>'))
  assert.doesNotMatch(cashbackSection, /<select value=\{selected\.cashback_type/)
})

test('AdminAudit localizes money audit labels statuses and payment methods', () => {
  const audit = readSource('src/pages/AdminAudit.jsx')

  assert.match(audit, /function paymentMethodLabel/)
  assert.match(audit, /function statusLabel/)
  assert.match(audit, /function groupAuditRows\(rows\)/)
  assert.match(audit, /function orderAuditLabel\(row, lang\)/)
  assert.match(audit, /fmtDate\(value, lang = 'ru'\)/)
  assert.match(audit, /before: 'Oldin'/)
  assert.match(audit, /before: 'Было'/)
  assert.match(audit, /before: 'Before'/)
  assert.match(audit, /cash: \{ uz: 'Naqd', ru: 'Наличные', en: 'Cash' \}/)
  assert.match(audit, /loyalty_card: \{ uz: 'Sodiqlik kartasi', ru: 'Карта лояльности', en: 'Loyalty card' \}/)
  assert.match(audit, /settle_loyalty_wallet_payment: \{ uz: 'Sodiqlik to‘lovi hisoblandi', ru: 'Расчёт оплаты лояльностью', en: 'Loyalty wallet payment settled' \}/)
  assert.match(audit, /paid: \{ uz: 'To‘landi', ru: 'Оплачен', en: 'Paid' \}/)
  assert.match(audit, /take_away: ORDER_TYPE_LABELS\.take_away/)
  assert.match(audit, /delivery: ORDER_TYPE_LABELS\.delivery/)
  assert.match(audit, /statusLabel\(status, lang\)/)
  assert.match(audit, /\.from\('orders'\)[\s\S]*order_number[\s\S]*\.in\('id', orderIds\)/)
  assert.match(audit, /order\.order_number \|\| row\.order_id/)
  assert.match(audit, /const groupedRows = useMemo\(\(\) => groupAuditRows\(filteredRows\), \[filteredRows\]\)/)
  assert.match(audit, /<details key=\{group\.orderId\}/)
  assert.match(audit, /paymentMethodLabel\(row\.old_payment_method, lang\)/)
  assert.match(audit, /beforeLabel=\{l\.before\}/)
})

test('AdminSettings does not expose obsolete cashback percent setting', () => {
  const settings = readSource('src/pages/AdminSettings.jsx')
  const reducerDefaults = readSource('src/store/reducerHelpers.js')
  const db = readSource('src/lib/db.js')

  assert.doesNotMatch(settings, /Cashback Percent/)
  assert.doesNotMatch(settings, /cashbackPercent/)
  assert.doesNotMatch(reducerDefaults, /cashbackPercent/)
  assert.doesNotMatch(db, /settings\.cashbackPercent/)
  assert.doesNotMatch(db, /cashback_percent:\s*Number\.isFinite\(Number\(settings\.cashbackPercent\)\)/)
})

test('AdminSettings persists service rate immediately when a preset is selected', () => {
  const settings = readSource('src/pages/AdminSettings.jsx')

  assert.match(settings, /async function saveSettings\(overrides = \{\}\)/)
  assert.match(settings, /async function handleServiceRateChange\(nextRate\)/)
  assert.match(settings, /setServiceRate\(nextRate\)/)
  assert.match(settings, /saveSettings\(\{ serviceRate: nextRate \}\)/)
  assert.match(settings, /onClick=\{\(\) => handleServiceRateChange\(v\)\}/)
})

test('AdminSettings exposes monthly rent as a UZS billing setting', () => {
  const settings = readSource('src/pages/AdminSettings.jsx')
  const defaults = readSource('src/store/reducerHelpers.js')
  const db = readSource('src/lib/db.js')
  const migration = readSource('supabase/073_business_settings_monthly_rent.sql')
  const health = readSource('scripts/check-db-health.js')
  const dbHealth = readSource('src/lib/dbHealth.js')

  assert.match(settings, /const \[monthlyRentUzs, setMonthlyRentUzs\] = useState\(String\(settings\.monthlyRentUzs \|\| ''\)\)/)
  assert.match(settings, /monthlyRentUzs: Number\(normalizeMoneyInput\(monthlyRentUzs\) \|\| 0\)/)
  assert.match(settings, /formatMoneyInput\(monthlyRentUzs\)/)
  assert.match(settings, /setMonthlyRentUzs\(normalizeMoneyInput\(event\.target\.value\)\)/)
  assert.match(settings, /monthlyRentSub/)
  assert.match(defaults, /monthlyRentUzs:\s*0/)
  assert.match(db, /monthlyRentUzs: Math\.max\(0, Math\.round\(Number\(row\.monthly_rent_uzs\) \|\| 0\)\)/)
  assert.match(db, /monthly_rent_uzs: Math\.max\(0, Math\.round\(Number\(settings\.monthlyRentUzs\) \|\| 0\)\)/)
  assert.match(migration, /monthly_rent_uzs bigint not null default 0/)
  assert.match(health, /monthly_rent_uzs/)
  assert.match(dbHealth, /monthly_rent_uzs/)
})

test('AdminSettings exposes monthly utilities as a UZS billing setting', () => {
  const settings = readSource('src/pages/AdminSettings.jsx')
  const defaults = readSource('src/store/reducerHelpers.js')
  const db = readSource('src/lib/db.js')
  const migration = readSource('supabase/126_business_settings_monthly_utilities.sql')
  const health = readSource('scripts/check-db-health.js')
  const dbHealth = readSource('src/lib/dbHealth.js')

  assert.match(settings, /const \[monthlyUtilitiesUzs, setMonthlyUtilitiesUzs\] = useState\(String\(settings\.monthlyUtilitiesUzs \|\| ''\)\)/)
  assert.match(settings, /monthlyUtilitiesUzs: Number\(normalizeMoneyInput\(monthlyUtilitiesUzs\) \|\| 0\)/)
  assert.match(settings, /formatMoneyInput\(monthlyUtilitiesUzs\)/)
  assert.match(settings, /setMonthlyUtilitiesUzs\(normalizeMoneyInput\(event\.target\.value\)\)/)
  assert.match(settings, /monthlyUtilitiesSub/)
  assert.match(defaults, /monthlyUtilitiesUzs:\s*0/)
  assert.match(db, /monthlyUtilitiesUzs: Math\.max\(0, Math\.round\(Number\(row\.monthly_utilities_uzs\) \|\| 0\)\)/)
  assert.match(db, /monthly_utilities_uzs: Math\.max\(0, Math\.round\(Number\(settings\.monthlyUtilitiesUzs\) \|\| 0\)\)/)
  assert.match(migration, /monthly_utilities_uzs bigint not null default 0/)
  assert.match(health, /monthly_utilities_uzs/)
  assert.match(dbHealth, /monthly_utilities_uzs/)
})

test('AdminSettings persists the average daily employee meal and forecasts present employee-days', () => {
  const settings = readSource('src/pages/AdminSettings.jsx')
  const defaults = readSource('src/store/reducerHelpers.js')
  const db = readSource('src/lib/db.js')
  const migration = readSource('supabase/141_average_daily_employee_meal.sql')
  const financialHistoryMigration = readSource('supabase/147_financial_report_history_snapshots.sql')
  const health = readSource('scripts/check-db-health.js')
  const dbHealth = readSource('src/lib/dbHealth.js')
  const monthlyEstimate = readSource('src/pages/MonthlyEstimate.jsx')
  const salaryMessages = readSource('api/telegram/_lib/salaryMessages.js')
  const reports = readSource('src/pages/Reports.jsx')
  const accounting = readSource('src/pages/Expenses.jsx')
  const accountingHistory = readSource('src/pages/AccountingHistory.jsx')
  const expenses = readSource('src/lib/expenses.js')
  const dailySalary = readSource('api/telegram/daily-salary.js')

  assert.match(settings, /const \[averageDailyEmployeeMealUzs, setAverageDailyEmployeeMealUzs\] = useState\(String\(settings\.averageDailyEmployeeMealUzs \|\| ''\)\)/)
  assert.match(settings, /averageDailyEmployeeMealUzs: Number\(normalizeMoneyInput\(averageDailyEmployeeMealUzs\) \|\| 0\)/)
  assert.match(settings, /formatMoneyInput\(averageDailyEmployeeMealUzs\)/)
  assert.match(settings, /setAverageDailyEmployeeMealUzs\(normalizeMoneyInput\(event\.target\.value\)\)/)
  assert.match(defaults, /averageDailyEmployeeMealUzs:\s*0/)
  assert.match(db, /averageDailyEmployeeMealUzs: Math\.max\(0, Math\.round\(Number\(row\.average_daily_employee_meal_uzs\) \|\| 0\)\)/)
  assert.match(db, /average_daily_employee_meal_uzs: Math\.max\(0, Math\.round\(Number\(settings\.averageDailyEmployeeMealUzs\) \|\| 0\)\)/)
  assert.match(migration, /average_daily_employee_meal_uzs bigint not null default 0/)
  assert.match(health, /average_daily_employee_meal_uzs/)
  assert.match(dbHealth, /average_daily_employee_meal_uzs/)
  assert.match(monthlyEstimate, /getEmployeeMealExpenseEstimate\(/)
  assert.match(monthlyEstimate, /buildFinalizedEmployeeMealExpenseRows\(employeeMealSnapshots\)/)
  assert.match(monthlyEstimate, /allActualExpenseRows = \[\.\.\.salaryPaymentRows, \.\.\.salaryBonusRows, \.\.\.finalizedEmployeeMealRows, \.\.\.manualExpenseRows\]/)
  assert.match(monthlyEstimate, /\+ employeeMealEstimate\.total/)
  assert.match(salaryMessages, /employeeMealTotal = employeeMealPerEmployeeTotal \* presentEmployeeCount/)
  assert.match(salaryMessages, /normalizedGrossProfit - salaryTotal - kpiBonusTotal - rentTotal - utilitiesTotal - employeeMealTotal/)
  assert.match(salaryMessages, /presentEmployeeCount\} × \$\{formatSalaryNotificationAmount\(employeeMealPerEmployeeTotal\)/)
  assert.match(expenses, /export function buildEmployeeMealExpenseRows/)
  assert.match(expenses, /export function buildFinalizedEmployeeMealExpenseRows/)
  assert.match(expenses, /payment_method: 'calculated'/)
  assert.match(reports, /buildFinalizedEmployeeMealExpenseRows\(employeeMealSnapshots\)/)
  assert.match(reports, /\.from\('employee_daily_meal_expenses'\)/)
  assert.match(reports, /expenseSummary\.byCategory\.employee_meals/)
  assert.match(accounting, /buildFinalizedEmployeeMealExpenseRows\(employeeMealSnapshots\)/)
  assert.match(accounting, /\.from\('employee_daily_meal_expenses'\)/)
  assert.match(accounting, /formatCurrency\(employeeMealExpensesTotal\)/)
  assert.match(accountingHistory, /buildFinalizedEmployeeMealExpenseRows\(employeeMealResult\.data \|\| \[\]\)/)
  assert.match(accountingHistory, /\.from\('employee_daily_meal_expenses'\)/)
  assert.match(financialHistoryMigration, /create table if not exists public\.employee_daily_meal_expenses/i)
  assert.match(financialHistoryMigration, /Finalized employee meal expenses are immutable/i)
  assert.match(financialHistoryMigration, /average_daily_amount::bigint \* present_employee_count::bigint/i)
  assert.match(dailySalary, /loadInvestorGroupTarget/)
  assert.match(dailySalary, /generate_employee_daily_meal_expense/)
  assert.match(dailySalary, /ZarKebab Investor Telegram group/)
})

test('AdminSettings does not expose receipt footer editing', () => {
  const settings = readSource('src/pages/AdminSettings.jsx')

  assert.doesNotMatch(settings, /Receipt Footer/)
  assert.doesNotMatch(settings, /receiptFooterL/)
  assert.doesNotMatch(settings, /setReceiptFooter/)
  assert.doesNotMatch(settings, /payload: \{ restaurantName, serviceRate, receiptFooter, autoPrint \}/)
})

test('Auto-print bill saves immediately and prints after a successful move to cashier', () => {
  const app = readSource('src/App.jsx')
  const settings = readSource('src/pages/AdminSettings.jsx')
  const billHandoff = readSource('src/lib/billHandoff.js')
  const waiterTables = readSource('src/pages/WaiterTables.jsx')
  const waiterOrder = readSource('src/pages/WaiterOrder.jsx')
  const cashierBill = readSource('src/pages/CashierBill.jsx')
  const receipt = readSource('src/pages/Receipt.jsx')

  assert.match(settings, /async function handleAutoPrintChange\(nextValue\)/)
  assert.match(settings, /await saveSettings\(\{ autoPrint: nextValue \}\)/)
  assert.match(settings, /onChange=\{handleAutoPrintChange\}/)
  assert.match(settings, /Print the bill immediately when an order moves to cashier/)
  assert.match(billHandoff, /navigate\(`\/cashier\/bill\/\$\{encodedTableId\}`\)/)
  assert.match(billHandoff, /function getBillReceiptPath[\s\S]*\/receipt\/\$\{encodeURIComponent\(orderId\)\}\?print=1[\s\S]*\/receipt\/table\/\$\{encodeURIComponent\(tableId\)\}\?print=1/)
  assert.match(billHandoff, /function completeBillHandoff[\s\S]*completeBillPrint\(\{ tableId, printWindow, browserWindow \}\)/)
  assert.match(waiterTables, /prepareBillPrintWindow\(autoPrint\)[\s\S]*MARK_TABLE_NEEDS_BILL[\s\S]*completeBillHandoff/)
  assert.match(waiterOrder, /prepareBillPrintWindow\(autoPrintBill\)[\s\S]*MARK_TABLE_NEEDS_BILL[\s\S]*onMovedToCashier\?\.\(printWindow\)/)
  assert.match(receipt, /new URLSearchParams\(location\.search\)\.get\('print'\) === '1'/)
  assert.doesNotMatch(receipt, /settings\.autoPrint \|\| new URLSearchParams/)
  assert.match(cashierBill, /async function handlePrintBill\(\)[\s\S]*prepareBillPrintWindow\(true\)[\s\S]*refreshCurrentBill\(\)[\s\S]*getFreshCashierPaymentQuote\([\s\S]*completeBillPrint/)
  assert.match(cashierBill, /catch \(error\) \{[\s\S]*cancelBillPrintWindow\(printWindow\)/)
  assert.match(cashierBill, /onClick=\{handlePrintBill\}/)
  assert.match(app, /path="\/cashier\/bill\/:tableId"[\s\S]*page=\{\['cashier', 'tables'\]\}><CashierBill \/>/)
  assert.match(app, /page=\{\['cashier', 'tables'\]\}><Receipt \/>/)
  assert.match(app, /page=\{\['cashier', 'tables'\]\}><TableReceipt \/>/)
  assert.match(functionBody(app, 'ProtectedRoute'), /Array\.isArray\(page\)[\s\S]*page\.some\(pageKey => canViewPage\(profile, pageKey\)\)/)
})

test('Receipt hides payment methods and uses contributing order metadata with paid timestamps', () => {
  const receipt = readSource('src/pages/Receipt.jsx')
  const db = readSource('src/lib/db.js')
  const receiptPaper = functionBody(receipt, 'ReceiptPaper')
  const tableReceiptRoute = functionBody(receipt, 'TableReceipt')

  assert.doesNotMatch(receipt, /payment:\s*['"]/)
  assert.doesNotMatch(receipt, /function payMethodLabel/)
  assert.doesNotMatch(receiptPaper, /labels\.payment/)
  assert.doesNotMatch(receiptPaper, /payments\?\.length/)
  assert.doesNotMatch(receiptPaper, /Payment ·/)
  assert.match(receipt, /const isOffPremise = isOffPremiseOrderType\(inferOrderType\(order\)\)/)
  assert.match(receipt, /const allOrders = isOffPremise\s*\?\s*\[order\]/)
  assert.match(receipt, /o\.table_id === order\.table_id && o\.payment_status !== 'paid'/)
  assert.match(receipt, /receiptAt:\s+order\.paid_at \|\| order\.created_at/)
  assert.match(tableReceiptRoute, /receiptAt:\s+primaryOrder\?\.paid_at \|\| primaryOrder\?\.created_at/)
  assert.doesNotMatch(receipt, /menuType/)
  assert.doesNotMatch(receiptPaper, /getPriceModeLabel/)
  assert.match(receipt, /filter\(item => !isCancelledOrderItem\(item\)\)/)
  assert.match(receipt, /getOrderGroupPaymentQuote/)
  assert.match(receipt, /import \{ formatDateTime \} from '\.\.\/lib\/dateFormat'/)
  assert.match(receipt, /dateStr=\{formatDateTime\(data\.receiptAt\)\}/)
  assert.match(receipt, /loadReceiptOrderGroup\(orderId\)/)
  assert.match(receipt, /const receiptOrders = localOrder \? state\.orders : historicalOrders/)
  assert.match(db, /export async function loadReceiptOrderGroup\(orderId, options = \{\}\)/)
  assert.match(db, /payments:order_payments\(\*\)/)
  assert.match(db, /\.gte\('paid_at', minuteStart\)/)
  assert.match(db, /\.lt\('paid_at', minuteEnd\)/)
  assert.doesNotMatch(receipt, /function formatDate\(/)
})

test('Tourist receipts select English once and keep the cashier language controls available', () => {
  const receipt = readSource('src/pages/Receipt.jsx')
  const languageDefault = functionBody(receipt, 'useTouristReceiptEnglish')
  const tableReceiptRoute = functionBody(receipt, 'TableReceipt')
  const receiptShell = functionBody(receipt, 'ReceiptShell')

  assert.match(receipt, /import \{ getOrderItemUnitPrice, PRICE_MODE_TOURIST \} from '\.\.\/lib\/priceModes'/)
  assert.match(languageDefault, /priceMode !== PRICE_MODE_TOURIST/)
  assert.match(languageDefault, /dispatch\(\{ type: 'SET_LANG', payload: 'en' \}\)/)
  assert.match(languageDefault, /\[dispatch, priceMode, receiptKey\]/)
  assert.match(tableReceiptRoute, /useTouristReceiptEnglish\(data\?\.priceMode, tableId, dispatch\)/)
  assert.match(receipt, /export default function Receipt\(\)[\s\S]*useTouristReceiptEnglish\(data\?\.priceMode, orderId, dispatch\)/)
  assert.match(receiptShell, /\['uz', 'ru', 'en'\]\.map/)
  assert.match(receiptShell, /onClick=\{\(\) => dispatch\(\{ type: 'SET_LANG', payload: l \}\)\}/)
})

test('cashier payment waits for one atomic database settlement before local success', () => {
  const cashier = readSource('src/pages/CashierBill.jsx')
  const appContext = readSource('src/store/AppContext.jsx')
  const db = readSource('src/lib/db.js')
  const paymentMigration = readSource('supabase/083_atomic_order_payment_settlement.sql')

  assert.match(cashier, /const \[isProcessingPayment, setProcessingPayment\]/)
  assert.match(cashier, /async function handlePaid\(\)/)
  assert.match(cashier, /const result = await dispatch\(\{/)
  assert.match(cashier, /if \(result\?\.error\) return/)
  assert.match(cashier, /navigate\('\/cashier\/tables'\)/)
  assert.match(cashier, /processingPay/)
  assert.match(cashier, /hasLoyaltyCardEntry/)
  assert.match(cashier, /loyalty_card_number: loyaltyCard\?\.card_number \|\| null/)
  assert.match(cashier, /cardOwner:/)
  assert.match(cashier, /loyaltyCard\.customer_name \|\| lbl\.unnamedCardOwner/)
  assert.match(cashier, /async function pasteLoyaltyCardNumber\(\)/)
  assert.match(cashier, /navigator\.clipboard\.readText\(\)/)
  assert.match(cashier, /await checkLoyaltyCard\(cardNumber\)/)
  assert.match(cashier, /<ClipboardPaste size=\{16\}/)
  assert.match(appContext, /WRITE_BEFORE_LOCAL_ACTIONS\.has\(enriched\.type\)/)
  assert.match(appContext, /'MARK_ORDER_PAID'/)
  assert.match(db, /case 'MARK_ORDER_PAID':[\s\S]*supabase\.rpc\('settle_orders_payment', \{ payload \}\)[\s\S]*notifyTelegramOrderStatus\(paidOrderIds, 'completed'\)/)
  assert.doesNotMatch(db, /case 'MARK_ORDER_PAID':[\s\S]*\.from\('orders'\)[\s\S]*case 'DELETE_ORDER':/)
  assert.match(paymentMigration, /security definer/)
  assert.match(paymentMigration, /public\.current_staff_can_write\('cashier'\)/)
  assert.match(paymentMigration, /delete from public\.order_payments/)
  assert.match(paymentMigration, /update public\.orders/)
  assert.match(paymentMigration, /update public\.loyalty_cards/)
  assert.match(paymentMigration, /update public\.restaurant_tables/)
})

test('table payment atomically skips empty unpaid order shells', () => {
  const migration = readSource('supabase/087_skip_empty_order_shells_on_payment.sql')

  assert.match(migration, /rename to settle_orders_payment_strict/)
  assert.match(migration, /target_table_id is not null/)
  assert.match(migration, /not exists \([\s\S]*from public\.order_items oi[\s\S]*oi\.order_id = o\.id/)
  assert.match(migration, /set status = 'cancelled'/)
  assert.match(migration, /return public\.settle_orders_payment_strict\(payload\)/)
  assert.match(migration, /revoke all on function public\.settle_orders_payment_strict\(jsonb\) from authenticated/)
})

test('cashier bill verification is targeted bounded and explains disabled checkout', () => {
  const cashier = readSource('src/pages/CashierBill.jsx')
  const db = readSource('src/lib/db.js')
  const timeout = readSource('src/lib/writeTimeout.js')
  const appContext = readSource('src/store/AppContext.jsx')

  assert.match(cashier, /loadCashierBillOrders\(\{ tableId, orderId, signal \}\)/)
  assert.match(cashier, /withReadTimeout\(/)
  assert.doesNotMatch(cashier, /refreshPOSData\(\)/)
  assert.match(cashier, /SYNC_CASHIER_BILL_ORDERS/)
  assert.match(cashier, /resolveLoyaltyBeforePayment/)
  assert.match(cashier, /clearLoyaltyEntry/)
  assert.match(cashier, /checkoutBlockMessage/)
  assert.match(cashier, /value=\{formatMoneyInput\(row\.amount\)\}/)
  assert.match(cashier, /amount: normalizeMoneyInput\(e\.target\.value\)/)
  assert.match(db, /export async function loadCashierBillOrders/)
  assert.match(timeout, /export const POS_READ_TIMEOUT_MS = \d+/)
  assert.match(timeout, /POSReadTimeoutError/)
  assert.match(appContext, /'SYNC_CASHIER_BILL_ORDERS'/)
})

test('paid order deletion is routed through feature-gated RPC and wired to cashier and reports', () => {
  const appContext = readSource('src/store/AppContext.jsx')
  const reducer = readSource('src/store/ordersReducer.js')
  const db = readSource('src/lib/db.js')
  const migration = readSource('supabase/043_owner_delete_orders.sql')
  const loyaltyCleanupMigration = readSource('supabase/046_owner_delete_orders_loyalty_cleanup.sql')
  const reservationResetMigration = readSource('supabase/047_fix_owner_delete_order_reservation_reset.sql')
  const featureAccessMigration = readSource('supabase/066_delete_paid_orders_feature_access.sql')
  const moveBackFeatureMigration = readSource('supabase/067_move_back_to_table_feature_access.sql')
  const permissions = readSource('src/lib/permissions.js')
  const dashboard = readSource('src/pages/AdminDashboard.jsx')
  const cashier = readSource('src/pages/CashierBill.jsx')
  const cashierTables = readSource('src/pages/CashierTables.jsx')
  const reports = readSource('src/pages/Reports.jsx')

  assert.match(appContext, /'DELETE_ORDER'/)
  assert.match(reducer, /case 'DELETE_ORDER'/)
  assert.match(db, /case 'DELETE_ORDER':[\s\S]*delete_order_owner/)
  assert.match(migration, /delete_order_owner/)
  assert.match(migration, /current_staff_has_role\(array\['owner'\]\)/)
  assert.match(migration, /disable trigger guard_paid_order_items/)
  assert.match(migration, /delete from public\.loyalty_transactions/)
  assert.match(migration, /where order_id = p_order_id/)
  assert.match(migration, /total_redeemed = v_total_redeemed/)
  assert.match(migration, /delete from public\.orders/)
  assert.match(migration, /status = 'available'/)
  assert.match(migration, /reserved_for_name = ''/)
  assert.match(migration, /reserved_for_phone = ''/)
  assert.match(migration, /reservation_notes = ''/)
  assert.match(loyaltyCleanupMigration, /delete from public\.loyalty_transactions/)
  assert.match(loyaltyCleanupMigration, /where order_id = p_order_id/)
  assert.match(loyaltyCleanupMigration, /update public\.loyalty_cards/)
  assert.match(loyaltyCleanupMigration, /reserved_for_name = ''/)
  assert.match(loyaltyCleanupMigration, /reserved_for_phone = ''/)
  assert.match(loyaltyCleanupMigration, /reservation_notes = ''/)
  assert.match(reservationResetMigration, /delete_order_owner/)
  assert.match(reservationResetMigration, /reserved_for_name = ''/)
  assert.match(reservationResetMigration, /reserved_for_phone = ''/)
  assert.match(reservationResetMigration, /reservation_notes = ''/)
  assert.doesNotMatch(reservationResetMigration, /reserved_for_name = null/)
  assert.doesNotMatch(reservationResetMigration, /reserved_for_phone = null/)
  assert.doesNotMatch(reservationResetMigration, /reservation_notes = null/)
  assert.match(permissions, /delete_paid_orders/)
  assert.match(permissions, /function canDeletePaidOrders/)
  assert.match(permissions, /function canMoveBackToTable[\s\S]*canEditFeature\(profileOrRole, 'cashier'\)/)
  assert.match(featureAccessMigration, /delete_paid_orders/)
  assert.match(featureAccessMigration, /current_staff_can_access\('delete_paid_orders'\)/)
  assert.match(featureAccessMigration, /delete from public\.orders/)
  assert.match(moveBackFeatureMigration, /move_back_to_table/)
  assert.match(dashboard, /canDeletePaidOrders/)
  assert.match(dashboard, /function RecentOrderRow\(\{[\s\S]*canDelete[\s\S]*onDelete[\s\S]*confirmDelete/)
  assert.match(dashboard, /type: 'DELETE_ORDER'/)
  assert.match(cashier, /canDeletePaidOrders/)
  assert.match(cashier, /confirmDeleteOrder/)
  assert.match(cashier, /type: 'DELETE_ORDER'/)
  assert.match(cashierTables, /useAuth/)
  assert.match(cashierTables, /canDeletePaidOrders/)
  assert.match(cashierTables, /canMoveBackToTable/)
  assert.match(cashierTables, /function BillCard\(\{[\s\S]*canDelete[\s\S]*onDelete[\s\S]*confirmDelete/)
  assert.match(cashierTables, /type: 'DELETE_ORDER'/)
  assert.match(cashierTables, /confirmDeleteOrderId === order\.id/)
  assert.match(reports, /canDeleteOrder/)
  assert.match(reports, /canDeletePaidOrders/)
  assert.match(reports, /type: 'DELETE_ORDER'/)
  assert.match(reports, /setHistoryOrders\(current => current\.filter\(row => row\.id !== order\.id\)\)/)
})

test('owner and admin Cashier access includes moving bills back to tables', () => {
  const permissions = readSource('src/lib/permissions.js')
  const migration = readSource('supabase/094_admin_cashier_recall_access.sql')
  const cashierTables = readSource('src/pages/CashierTables.jsx')

  assert.match(permissions, /function canMoveBackToTable[\s\S]*canEditFeature\(profileOrRole, 'cashier'\)/)
  assert.doesNotMatch(permissions, /key: 'move_back_to_table'/)
  assert.match(migration, /array_remove\(feature_access, 'move_back_to_table'\)/)
  assert.match(migration, /auth\.uid\(\) is not null[\s\S]*not public\.is_owner\(\)/)
  assert.match(migration, /not public\.current_staff_can_write\('cashier'\)/)
  assert.doesNotMatch(migration, /current_staff_can_access\('move_back_to_table'\)/)
  assert.match(cashierTables, /onRecall=\{canEditCashier && canRecallTable \? handleRecallTable : null\}/)
})
