-- Immutable audit history for accounting records that may be corrected or deleted.
-- The source row can be removed, but its complete financial snapshot remains here.

create table if not exists public.accounting_record_audit (
  id              bigint generated by default as identity primary key,
  entity_type     text not null
                  check (entity_type in ('expense', 'salary_payment', 'salary_bonus')),
  entity_id       text not null,
  action          text not null
                  check (action in ('insert', 'update', 'delete')),
  old_record      jsonb,
  new_record      jsonb,
  changed_by      uuid references public.profiles(id) on delete set null,
  changed_by_name text not null default '',
  changed_at      timestamptz not null default now()
);

create index if not exists idx_accounting_record_audit_entity
  on public.accounting_record_audit(entity_type, entity_id, changed_at desc);

create index if not exists idx_accounting_record_audit_changed_at
  on public.accounting_record_audit(changed_at desc);

create or replace function public.capture_accounting_record_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entity_type text;
  v_entity_id text;
  v_actor_name text := '';
begin
  v_entity_type := case tg_table_name
    when 'expenses' then 'expense'
    when 'employee_salary_payments' then 'salary_payment'
    when 'employee_salary_bonuses' then 'salary_bonus'
    else null
  end;

  if v_entity_type is null then
    raise exception 'Unsupported accounting audit table: %', tg_table_name;
  end if;

  if tg_op = 'DELETE' then
    v_entity_id := to_jsonb(old) ->> 'id';
  else
    v_entity_id := to_jsonb(new) ->> 'id';
  end if;

  select coalesce(nullif(trim(p.full_name), ''), nullif(trim(p.email), ''), '')
  into v_actor_name
  from public.profiles p
  where p.id = auth.uid();

  insert into public.accounting_record_audit (
    entity_type,
    entity_id,
    action,
    old_record,
    new_record,
    changed_by,
    changed_by_name
  ) values (
    v_entity_type,
    v_entity_id,
    lower(tg_op),
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end,
    auth.uid(),
    coalesce(v_actor_name, '')
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists audit_expenses_records on public.expenses;
create trigger audit_expenses_records
after insert or update or delete on public.expenses
for each row execute function public.capture_accounting_record_audit();

drop trigger if exists audit_salary_payment_records on public.employee_salary_payments;
create trigger audit_salary_payment_records
after insert or update or delete on public.employee_salary_payments
for each row execute function public.capture_accounting_record_audit();

drop trigger if exists audit_salary_bonus_records on public.employee_salary_bonuses;
create trigger audit_salary_bonus_records
after insert or update or delete on public.employee_salary_bonuses
for each row execute function public.capture_accounting_record_audit();

create or replace function public.prevent_accounting_audit_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'Accounting audit records are immutable';
end;
$$;

drop trigger if exists accounting_record_audit_is_immutable on public.accounting_record_audit;
create trigger accounting_record_audit_is_immutable
before update or delete on public.accounting_record_audit
for each row execute function public.prevent_accounting_audit_mutation();

alter table public.accounting_record_audit enable row level security;

drop policy if exists "accounting_feature_read_audit" on public.accounting_record_audit;
create policy "accounting_feature_read_audit"
  on public.accounting_record_audit for select
  to authenticated
  using (public.current_staff_can_access('expenses'));

revoke all on table public.accounting_record_audit from public;
grant select on table public.accounting_record_audit to authenticated;
revoke all on function public.capture_accounting_record_audit() from public;
revoke all on function public.prevent_accounting_audit_mutation() from public;
